'use strict';

/* AML Analytical Workbench v0.16 enhancement layer.
   Loaded after app.js. It deliberately reuses the authenticated Supabase client,
   RLS session and audit helpers from v0.15, while replacing the analytical views. */

const V16='0.16.0';
const FINDING_LABELS_V16={ENTITY_CONVERGENCE:'Convergencia multifuente',PRUDENTIAL_SANCTION:'Sanción prudencial en sujeto obligado',CONTEXTUAL_ANOMALY:'Anomalía contextual',REGULATORY_GAP:'Brecha regulatoria / screening',SUPERVISORY_GAP:'Brecha potencial de supervisión',DIRECT_AML_SIGNAL:'Señal AML directa',SANCTION_CONVERGENCE:'Convergencia sancionatoria',TERRITORIAL_CONVERGENCE:'Convergencia territorial',NETWORK_CONTEXT:'Contexto de red'};
const FINDING_RULES_V16={
ENTITY_CONVERGENCE:'Cruza un mismo Entity ID canónico entre productores independientes. La prioridad aumenta con amplitud de evidencia, independencia de fuentes, recurrencia, contexto de red y reglas observables.',
PRUDENTIAL_SANCTION:'Cruza la condición de sujeto obligado observada en UAF con una sanción administrativa resuelta a la misma entidad por identidad fuerte (por ejemplo, RUT exacto). No convierte la sanción en señal LA/FT.',
CONTEXTUAL_ANOMALY:'Agrupa banderas contextuales determinísticas provenientes de los radares —por ejemplo, cambios o amplitud de domicilios SII— para evitar alertas redundantes. Anomalía contextual no equivale a señal AML.',
REGULATORY_GAP:'Compara actividad/sector observado en fuentes económicas con cobertura pública UAF. El resultado es candidato de screening, nunca prueba de no inscripción.',
SUPERVISORY_GAP:'Combina evidencia regulatoria observable para priorizar revisión de cobertura. Requiere corroboración antes de cualquier conclusión sobre obligación o incumplimiento.',
DIRECT_AML_SIGNAL:'Hallazgo sustentado en una señal explícitamente gobernada por el Signals Registry AML y su evidencia de origen.',
SANCTION_CONVERGENCE:'Cruza recurrencia o convergencia de eventos sancionatorios resueltos a una misma entidad. Las sanciones administrativas no acreditan LA/FT por sí solas.',
TERRITORIAL_CONVERGENCE:'Cruza señales o hallazgos dentro de una unidad territorial para priorización comparativa. El contexto territorial no se hereda a cada entidad.',
NETWORK_CONTEXT:'Usa únicamente relaciones observadas y trazables para describir contexto de red. Una relación no transmite automáticamente el riesgo o señal de una contraparte.'};
const PATTERN_RULES_V16={
OUTLIER_INTENSIDAD_ROS:'Cruce sectorial: volumen de ROS / entidades registradas. Compara la intensidad por entidad entre sectores con base suficiente (al menos 10 entidades) y alerta la cola o decil superior.',
ACELERACION_ROS:'Cruce temporal sectorial: variación interanual de ROS 2025 versus 2024. Compara el crecimiento entre sectores con base 2024 suficiente y prioriza la cola superior.',
CONCENTRACION_SANCIONES:'Cruce sectorial: conteo de eventos sancionatorios observados por sector y comparación de su posición relativa frente a los demás sectores.',
OUTLIER_DENSIDAD_ANOMALIAS:'Cruce territorial: anomalías contextuales por 1.000 entidades Fusion en cada región. Prioriza regiones en la cola superior de la distribución.',
OUTLIER_DENSIDAD_BRECHA:'Cruce territorial: candidatos de screening/brecha potencial por 1.000 entidades Fusion. Prioriza la cola superior regional.',
RECURRENCIA_SANCIONATORIA:'Cruce por identidad: un mismo Entity ID canónico aparece en múltiples eventos sancionatorios resueltos del snapshot. La fuerza aumenta con la recurrencia relativa.',
CONCENTRACION_TERRITORIAL:'Cruce sector-territorio: calcula qué proporción del universo SII fuerte observado del sector se concentra en sus tres regiones principales; alerta una concentración muy alta (por ejemplo, superior a 90%).',
CONVERGENCIA_MULTIFUENTE:'Cruce de fuentes independientes sobre un mismo ámbito o entidad para identificar acumulación de evidencia observable.',
PERSISTENCIA_HALLAZGOS:'Cruce temporal: evalúa repetición o persistencia del mismo tipo de hallazgo en ventanas sucesivas.',
DENSIDAD_SANCIONES:'Cruce normalizado: eventos sancionatorios por unidad de exposición observable (entidades, sector o territorio según el alcance).',
OUTLIER_REPORTABILIDAD:'Cruce comparativo de una métrica pública de reportabilidad contra pares con base suficiente; identifica valores en la cola de distribución, no incumplimientos individuales.'};
const SII_SIGNAL_LABELS_V16={SALES_BAND_JUMP:'Salto relevante de tramo de ventas',HIGH_SALES_LOW_WORKFORCE:'Tramo alto de ventas con baja dotación publicada',RECENT_START_HIGH_SALES:'Inicio reciente con tramo alto de ventas',HIGH_SALES_NEGATIVE_EQUITY:'Tramo alto con capital propio tributario negativo publicado',WORKFORCE_DROP_STABLE_SALES:'Caída de dotación con tramo de ventas estable o mayor',MAIN_ACTIVITY_CHANGE:'Cambio de actividad económica principal',REGION_CHANGE:'Cambio de región publicada',ACTIVITY_BREADTH:'Amplitud de actividades económicas',ADDRESS_HISTORY_BREADTH:'Amplitud del historial de domicilios',REACTIVATION_PATTERN:'Patrón de reactivación tributaria'};
const SII_SIGNAL_RULES_V16={SALES_BAND_JUMP:'El tramo SII aumenta al menos tres niveles entre años comerciales consecutivos con información.',HIGH_SALES_LOW_WORKFORCE:'Tramo SII de gran empresa coexistiendo con hasta dos trabajadores dependientes informados.',RECENT_START_HIGH_SALES:'Entidad con hasta dos años desde el inicio publicado que alcanza un tramo SII de gran empresa.',HIGH_SALES_NEGATIVE_EQUITY:'Tramo SII alto coexistiendo con un tramo de capital propio tributario negativo informado.',WORKFORCE_DROP_STABLE_SALES:'La dotación cae al 20% o menos del año anterior, partiendo desde al menos diez trabajadores, sin disminución del tramo de ventas.',MAIN_ACTIVITY_CHANGE:'La actividad económica principal publicada cambia respecto del año comercial anterior.',REGION_CHANGE:'La región publicada cambia respecto del año comercial anterior.',ACTIVITY_BREADTH:'Se observan seis o más actividades económicas vigentes/publicadas.',ADDRESS_HISTORY_BREADTH:'Se observa un historial amplio de domicilios o regiones publicadas.',REACTIVATION_PATTERN:'Coexiste término de giro histórico con estado activo en la nómina actual publicada.'};
const SALES_BAND_V16={1:'Sin información',2:'0,01–200 UF',3:'200,01–600 UF',4:'600,01–2.400 UF',5:'2.400,01–5.000 UF',6:'5.000,01–10.000 UF',7:'10.000,01–25.000 UF',8:'25.000,01–50.000 UF',9:'50.000,01–100.000 UF',10:'100.000,01–200.000 UF',11:'200.000,01–600.000 UF',12:'600.000,01–1.000.000 UF',13:'Más de 1.000.000 UF'};

function v16Tag(text,kind=''){return `<span class="tag ${kind}">${esc(text)}</span>`;}
function v16Datum(label,value,sub=''){return `<div class="datum"><span>${esc(label)}</span><strong>${esc(value??'—')}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`;}
function v16FindingLabel(type){return FINDING_LABELS_V16[type]||String(type||'Hallazgo').replaceAll('_',' ');}
function v16FindingRule(f){return FINDING_RULES_V16[f.finding_type]||f.payload?.explanation||'Regla determinística y trazable del motor Fusion.';}
function v16PatternRule(p){return PATTERN_RULES_V16[p.pattern_type]||'Regla determinística de Pattern Intelligence v0.12. La fuerza se calcula comparativamente dentro de su universo de pares.';}
function v16Sector(entity,findings){const arr=(findings||[]).flatMap(f=>Array.isArray(f.payload?.sector_names)?f.payload.sector_names:[]).filter(Boolean);if(arr.length)return arr[0];const roles=entity?.profile?.roles||[];if(roles.includes('OBLIGED_ENTITY')&&String(entity?.name||'').toUpperCase().includes('BANCO'))return 'Bancos';return null;}

shell=function(title,subtitle){const role=state.access?.role||'viewer';const email=state.user?.email||'usuario';app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">AML</div><div class="brand-copy"><strong>Analytical Workbench</strong><span>Fusion Intelligence</span></div></div><nav class="nav">${navButton('overview','Resumen','01')}${navButton('entities','Entity 360','02')}${navButton('findings','Hallazgos','03')}${navButton('sanctions','Sanciones','04')}${navButton('patterns','Patrones','05')}</nav><div class="sidebar-foot"><div class="small muted">${esc(email)}</div><span class="role">${esc(role)}</span><button class="ghost" id="logout">Cerrar sesión</button></div></aside><main class="main"><header class="topbar"><div><div class="eyebrow">AML Analytical Workbench · v${V16}</div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div><div class="status"><span class="status-pill good">● Entra + Auth</span><span class="status-pill good">● RLS</span><span class="status-pill">${esc(role)}</span></div></header><div class="notice">Prioridad analítica ≠ probabilidad de delito. Ausencia de dato ≠ cero. “No observado UAF” ≠ “no inscrito”. El contexto sectorial, territorial o relacional no se hereda como riesgo individual.</div><section id="content"><div class="loading">Consultando Fusion…</div></section></main></div>`;document.querySelector('#logout').onclick=signOut;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));};

function v16FindingCards(rows,compact=false){if(!rows.length)return empty('Sin hallazgos','No hay hallazgos vinculados en este corte.');return `<div class="explain-list">${rows.map(f=>{const p=f.payload||{};const facts=p.decision_facts||{};const features=p.decision_features||{};const producers=p.producer_ids||[];const evidence=p.evidence_ids||[];const supports=p.supporting_factors||[];const contradicts=p.contradicting_factors||[];const next=p.suggested_next_steps||[];return `<article class="explain-card"><div class="explain-top"><div><div class="card-kicker">${esc(v16FindingLabel(f.finding_type))}</div><h3>${esc(f.title||v16FindingLabel(f.finding_type))}</h3></div><div class="score-pills"><span class="score ${scoreClass(f.score_explore)}">Explorar ${fmtScore(f.score_explore)}</span><span class="score ${scoreClass(f.score_supervise)}">Fiscalizar ${fmtScore(f.score_supervise)}</span><span class="score ${scoreClass(f.score_investigate)}">Investigar ${fmtScore(f.score_investigate)}</span></div></div><p>${esc(p.explanation||'Hallazgo determinístico generado a partir de hechos observables.')}</p><div class="rule-box"><strong>Algoritmo / cruce</strong><p>${esc(v16FindingRule(f))}</p><small>Modelo: ${esc(p.score_model||'IPA / regla Fusion')} · evidencias: ${fmtNum(f.evidence_count||evidence.length)} · fuentes independientes: ${esc(facts.independent_sources??p.source_independence_count??'—')}</small></div>${compact?'':`<div class="explain-grid"><div><span>Fuentes</span><div class="chips">${producers.map(x=>v16Tag(x,'info')).join('')||'—'}</div></div><div><span>Hechos observados</span><p>${esc(Object.entries(facts).filter(([,v])=>v!==null&&v!==undefined).map(([k,v])=>`${k}: ${v}`).join(' · ')||'—')}</p></div><div><span>Features de decisión</span><p>${esc(Object.entries(features).map(([k,v])=>`${k}: ${v}`).join(' · ')||'—')}</p></div><div><span>Evidencia</span><p class="mono small">${esc(evidence.join(' · ')||'—')}</p></div></div>${supports.length?`<div class="factor good-factor"><strong>Factores que soportan</strong><ul>${supports.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${contradicts.length?`<div class="factor guard-factor"><strong>Contrapesos / guardrails</strong><ul>${contradicts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${next.length?`<div class="factor"><strong>Siguientes verificaciones</strong><ul>${next.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}`}</article>`;}).join('')}</div>`;}

function v16SanctionCards(rows,canonicalName=null){if(!rows.length)return empty('Sin sanciones','No hay eventos sancionatorios vinculados en este corte.');return `<div class="explain-list">${rows.map(s=>{const a=s.payload?.attributes||{};return `<article class="explain-card sanction-card"><div class="explain-top"><div><div class="card-kicker">${esc(s.regulator||a.supervisor||'Regulador')} · ${fmtDate(s.event_date)}</div><h3>${esc(canonicalName||s.entity_name||'Entidad')}</h3></div>${s.laft_direct?v16Tag('Vínculo LA/FT directo','warn'):v16Tag('Sin vínculo LA/FT directo clasificado')}</div><p>${esc(a.summary||s.subject||'Evento sancionatorio administrativo.')}</p><div class="explain-grid"><div><span>Resolución</span><strong>${esc(a.resolution||'—')}</strong></div><div><span>Materia</span><strong>${esc(a.category||'—')}</strong></div><div><span>Identidad</span><strong>${esc(s.identity_status||'—')}</strong></div><div><span>Monto UF</span><strong>${s.amount_uf!=null?fmtNum(s.amount_uf):'No extraído / no disponible'}</strong></div></div><div class="rule-box"><strong>Interpretación</strong><p>${s.laft_direct?'El clasificador observa vínculo directo con materia LA/FT en el contenido del evento. Debe revisarse la evidencia fuente.':'Sanción administrativa usada como contexto regulatorio. Por sí sola no acredita LA/FT.'}</p></div></article>`;}).join('')}</div>`;}

function v16PatternCards(rows,contextOnly=false){if(!rows.length)return empty('Sin patrones','No hay patrones en el alcance actual.');return `<div class="explain-list">${rows.map(p=>`<article class="explain-card pattern-card"><div class="explain-top"><div><div class="card-kicker">${esc(p.family||'Patrón')} · ${esc(p.scope_type||'')}</div><h3>${esc(p.title||p.pattern_type)}</h3></div><div>${v16Tag(p.priority||'—',String(p.priority||'').includes('ALTA')?'warn':'info')} ${v16Tag(`Fuerza ${fmtScore(p.strength)}`,'info')}</div></div><p>${esc(p.summary||'')}</p><div class="rule-box"><strong>Algoritmo / cruce que genera la alerta</strong><p>${esc(v16PatternRule(p))}</p><small>Tipo técnico: ${esc(p.pattern_type)} · alcance: ${esc(p.scope_label||p.scope_id||'—')} · fuente v${esc(p.payload?.source_version||'0.12.0')}</small></div>${contextOnly?'<div class="data-status">Patrón sectorial mostrado como contexto. No se atribuye automáticamente a esta entidad.</div>':''}<div class="guardline">Fuerza/strength = intensidad o posición comparativa de una regla. <strong>No es probabilidad de LA/FT ni score de culpabilidad.</strong></div></article>`).join('')}</div>`;}

function v16Regulatory(e,sector,obliged,rule){const status=obliged?'<span class="status-big good">Sí · observado en corte público UAF</span>':'<span class="status-big neutral">No observado en corte público UAF</span>';const block=rule?`<div class="report-grid"><div><span>ROS</span><strong>${rule.ros_required?'Aplicable':'No materializado'}</strong><p>${esc(rule.ros_trigger||'—')}</p></div><div><span>ROE</span><strong>${rule.roe_required?esc(rule.roe_frequency||'Aplicable'):'No aplicable/materializado'}</strong><p>${rule.roe_threshold_usd?`Operaciones en efectivo sobre USD ${fmtNum(rule.roe_threshold_usd)} o equivalente. `:''}${esc(rule.roe_deadline||'')}</p></div></div><div class="rule-box"><strong>Base y alcance</strong><p>${esc(rule.legal_basis||'')}</p><p>${esc(rule.notes||'')}</p><small>Corte de regla: ${fmtDate(rule.as_of_date)}</small></div>`:`<div class="data-status">La condición UAF está disponible, pero la regla detallada de reportabilidad de este sector aún no está materializada en el catálogo.</div>`;return `<section class="info-card"><div class="card-kicker">Condición UAF y reportabilidad</div><h3>${esc(sector||'Sector UAF no determinado')}</h3>${status}<p class="muted">${obliged?'La entidad aparece observada como sujeto obligado en el corte público integrado.':'La ausencia en el corte público no acredita no inscripción ni ausencia de obligación legal.'}</p>${block}${rule?`<div class="source-links"><a href="${esc(rule.source_url_ros)}" target="_blank" rel="noopener noreferrer">Fuente UAF · ROS</a><a href="${esc(rule.source_url_roe)}" target="_blank" rel="noopener noreferrer">Fuente UAF · ROE</a></div>`:''}</section>`;}

function v16TaxProfile(t){if(!t)return `<section class="info-card wide"><div class="card-kicker">Perfil tributario SII</div><h3>Perfil compacto aún no materializado</h3><div class="data-status">Radar SII dispone de historia empresa-año, tramo de ventas, trabajadores, actividad, vigencia, domicilios y relaciones societarias. Para este Entity ID el perfil no está presente en Supabase. <strong>Ausencia de integración ≠ ausencia de dato.</strong></div></section>`;const code=Number(t.sales_band_code||t.sales_band_rank||t.sales_band);const band=SALES_BAND_V16[code]||t.sales_band||`Tramo ${t.sales_band_code||'—'}`;const sigs=String(t.signal_types||'').split('|').map(s=>s.trim()).filter(Boolean);return `<section class="info-card wide"><div class="card-kicker">Perfil tributario SII</div><h3>Año comercial ${esc(t.commercial_year||'—')}</h3><div class="detail-core tax-grid">${v16Datum('Tramo de ventas',`Tramo ${code||'—'} · ${band}`,'Clasificación tributaria SII, no monto exacto')}${v16Datum('Trabajadores dependientes',t.workers_numeric,'Dotación publicada; contextual según industria')}${v16Datum('Actividad principal',t.main_activity)}${v16Datum('Sector económico',t.economic_sector)}${v16Datum('Subsector',t.economic_subsector)}${v16Datum('Tipo contribuyente',t.taxpayer_type)}${v16Datum('Subtipo',t.taxpayer_subtype)}${v16Datum('Estado publicado',t.current_status)}${v16Datum('Inicio de actividades',fmtDate(t.activity_start_date))}${v16Datum('Término de giro',fmtDate(t.termination_date))}${v16Datum('Capital propio positivo',t.positive_equity_band)}${v16Datum('Capital propio negativo',t.negative_equity_band)}${v16Datum('Actividades registradas',t.activity_count)}${v16Datum('Domicilios históricos',t.address_count,`${fmtNum(t.current_address_count)} marcados vigentes/publicados`)}${v16Datum('Relaciones societarias',t.ownership_edge_count)}${v16Datum('Sociedades donde figura como socio',t.societies_as_partner_count)}</div><div class="rule-box"><strong>Lectura correcta del nivel de ventas</strong><p>El SII publica un <em>tramo</em> de ventas, no el monto exacto. El tramo/código 1 significa “Sin información” y nunca debe tratarse como cero.</p></div>${sigs.length?`<div class="signal-block"><h4>Señales contextuales SII</h4>${sigs.map(s=>`<div class="signal-row"><strong>${esc(SII_SIGNAL_LABELS_V16[s]||s)}</strong><p>${esc(SII_SIGNAL_RULES_V16[s]||'Regla determinística del Radar SII.')}</p></div>`).join('')}<small>Estas señales priorizan revisión contextual; no constituyen hallazgo tributario, penal ni AML.</small></div>`:''}<div class="source-foot">Radar SII · source run ${esc(t.source_run_id||'—')} · actualizado ${esc(fmtDateTime(t.updated_at))}</div></section>`;}

function v16Relations(rows){return `<section class="info-card"><div class="card-kicker">Relaciones observadas</div><h3>${fmtNum(rows.length)} relación(es)</h3>${rows.length?`<div class="list compact">${rows.map(r=>`<div class="list-item"><strong>${esc(r.contraparte_nombre||r.contraparte_id||'Contraparte')}</strong><div class="meta"><span>${esc(r.tipo_es||r.tipo||'Relación')}</span><span>${esc(r.sentido_es||'')}</span><span>${esc(r.assertion_type_es||r.assertion_type||'')}</span><span>Confianza ${Math.round(Number(r.confidence??0)*100)}%</span></div></div>`).join('')}</div>`:empty('Sin relaciones materializadas','No hay relaciones observadas en el perfil compacto actual.')}<p class="muted small">Una relación observada no transmite señales o riesgo de la contraparte.</p></section>`;}
function v16Coverage(profile,e){const sources=profile.fuentes||[];const flags=profile.contexto?.sii_flags_es||[];return `<section class="info-card"><div class="card-kicker">Cobertura y evidencia</div><h3>${fmtNum(e.source_count)} productores convergentes</h3><div class="chips">${sources.map(s=>v16Tag(s,'info')).join('')}</div>${flags.length?`<p><strong>Contexto SII:</strong> ${esc(flags.join(' · '))}</p>`:''}<p class="small muted mono">${(profile.evidence_ids||[]).map(x=>esc(x)).join(' · ')||'Sin IDs compactos en perfil'}</p></section>`;}

openEntity=async function(entityId){state.selectedEntity=entityId;shell('Entity 360','Perfil AML explicable: condición UAF, reportabilidad, tributación, reglas, evidencia y relaciones.');try{const [entityRes,findingsRes,sanctionsRes,directPatternsRes,taxRes]=await Promise.all([sb.from('aml_entities').select('*').eq('entity_id',entityId).maybeSingle(),sb.from('aml_findings').select('finding_key,finding_id,finding_type,title,region,commune,score_explore,score_supervise,score_investigate,source_count,evidence_count,snapshot_id,updated_at,payload').eq('entity_id',entityId).order('score_investigate',{ascending:false,nullsFirst:false}).limit(100),sb.from('aml_sanctions').select('sanction_id,event_date,regulator,entity_name,entity_id,identity_status,laft_direct,amount_uf,subject,snapshot_id,updated_at,payload').eq('entity_id',entityId).order('event_date',{ascending:false,nullsFirst:false}).limit(100),sb.from('aml_pattern_alerts').select('alert_id,family,pattern_type,scope_type,scope_id,scope_label,strength,priority,title,summary,snapshot_id,updated_at,payload').eq('scope_id',entityId).order('strength',{ascending:false,nullsFirst:false}).limit(100),sb.from('aml_entity_tax_profile').select('*').eq('entity_id',entityId).maybeSingle()]);[entityRes,findingsRes,sanctionsRes,directPatternsRes,taxRes].forEach(r=>{if(r.error)throw r.error;});if(!entityRes.data)throw new Error('Entidad no disponible bajo la política actual.');const sector=v16Sector(entityRes.data,findingsRes.data||[]);let reporting=null,sectorPatterns=[];if(sector){const [ruleRes,sectorPatRes]=await Promise.all([sb.from('aml_reporting_rules').select('*').eq('sector_name',sector).maybeSingle(),sb.from('aml_pattern_alerts').select('alert_id,family,pattern_type,scope_type,scope_id,scope_label,strength,priority,title,summary,snapshot_id,updated_at,payload').eq('scope_type','SECTOR').eq('scope_label',sector).order('strength',{ascending:false,nullsFirst:false}).limit(50)]);if(!ruleRes.error)reporting=ruleRes.data;if(!sectorPatRes.error)sectorPatterns=sectorPatRes.data||[];}await audit('OPEN_ENTITY',{objectType:'entity',objectId:entityId,payload:{version:V16,findings:findingsRes.data?.length||0,sanctions:sanctionsRes.data?.length||0,sector,tax_profile:Boolean(taxRes.data)}});v16RenderEntity(entityRes.data,findingsRes.data||[],sanctionsRes.data||[],directPatternsRes.data||[],taxRes.data,sector,reporting,sectorPatterns);}catch(e){showContentError(e);}};

function v16RenderEntity(e,findings,sanctions,directPatterns,tax,sector,reporting,sectorPatterns){const profile=e.profile||{};const obliged=e.is_uaf_observed||profile.contexto?.sujeto_obligado===true||(profile.roles||[]).includes('OBLIGED_ENTITY');const evidenceCount=findings.reduce((a,r)=>a+Number(r.evidence_count||0),0);content().innerHTML=`<button class="ghost" id="back-entities">← Volver a búsqueda</button><div class="detail-head"><div><div class="eyebrow">${esc(profile.tipo_entidad_es||e.entity_type||'Entidad')}</div><h2>${esc(e.name)}</h2><div class="muted mono small">${esc(e.entity_id)}</div></div><div class="entity-flags">${obliged?v16Tag('Sujeto obligado UAF observado','good'):v16Tag('No observado en corte UAF')}${e.is_sanctioned?v16Tag('Eventos sancionatorios','warn'):''}${v16Tag(`${fmtNum(e.source_count)} fuentes`,'info')}</div></div><div class="detail-core">${v16Datum('RUT',e.rut)}${v16Datum('Identidad',profile.identity_method_es||'Identidad Fusion',profile.identity_confidence!=null?`Confianza ${Math.round(Number(profile.identity_confidence)*100)}%`:'')}${v16Datum('Región',e.region)}${v16Datum('Comuna',e.commune)}</div><div class="kpis">${kpi('Hallazgos',findings.length,'reglas vinculadas')}${kpi('Sanciones',sanctions.length,'eventos resueltos')}${kpi('Evidencias',evidenceCount,'referencias en hallazgos')}${kpi('Patrones directos',directPatterns.length,'atribuidos al Entity ID')}</div><div class="section-grid">${v16Regulatory(e,sector,obliged,reporting)}${v16Coverage(profile,e)}${v16TaxProfile(tax)}${v16Relations(profile.relaciones||[])}</div><section class="panel gap-top"><div class="panel-head"><h2>Hallazgos explicados</h2><span>${findings.length}</span></div><div class="panel-body">${v16FindingCards(findings,false)}</div></section><section class="panel gap-top"><div class="panel-head"><h2>Sanciones y contexto regulatorio</h2><span>${sanctions.length}</span></div><div class="panel-body">${v16SanctionCards(sanctions,e.name)}</div></section><section class="panel gap-top"><div class="panel-head"><h2>Pattern Intelligence</h2><span>directo + contexto sectorial</span></div><div class="panel-body"><h3 class="subhead">Patrones directamente vinculados a la entidad</h3>${directPatterns.length?v16PatternCards(directPatterns):empty('Sin patrones directos','No hay una regla Pattern Intelligence atribuida directamente a este Entity ID.')}<h3 class="subhead">Patrones del sector ${esc(sector||'no determinado')} — contexto, no atribución</h3>${sectorPatterns.length?v16PatternCards(sectorPatterns,true):empty('Sin patrones sectoriales materializados','No se encontraron patrones para la clasificación disponible.')}</div></section><div class="footer-note">Snapshot ${esc(e.snapshot_id||'—')} · entidad actualizada ${esc(fmtDateTime(e.updated_at))}. El contexto sectorial, territorial o relacional no se hereda como riesgo individual.</div>`;document.querySelector('#back-entities').onclick=loadEntities;}

loadFindings=async function(){state.view='findings';shell('Hallazgos','Qué se observó, qué regla lo generó, qué evidencia lo soporta y qué no permite concluir.');try{const {data,error}=await sb.from('aml_findings').select('finding_key,finding_id,finding_type,entity_id,title,region,commune,score_explore,score_supervise,score_investigate,source_count,evidence_count,snapshot_id,updated_at,payload').order('score_investigate',{ascending:false,nullsFirst:false}).limit(100);if(error)throw error;content().innerHTML=`<section class="panel"><div class="panel-head"><h2>Top 100 hallazgos</h2><span>prioridad investigativa</span></div><div class="panel-body">${v16FindingCards(data||[],false)}</div></section>`;}catch(e){showContentError(e);}};
loadSanctions=async function(){state.view='sanctions';shell('Sanciones','Eventos administrativos con identidad, materia y alcance LA/FT explícitamente diferenciados.');try{const {data,error}=await sb.from('aml_sanctions').select('sanction_id,event_date,regulator,entity_name,entity_id,identity_status,laft_direct,amount_uf,subject,snapshot_id,updated_at,payload').order('event_date',{ascending:false,nullsFirst:false}).limit(150);if(error)throw error;content().innerHTML=`<section class="panel"><div class="panel-head"><h2>Sanciones recientes</h2><span>150 eventos</span></div><div class="panel-body">${v16SanctionCards(data||[])}</div></section>`;}catch(e){showContentError(e);}};
loadPatterns=async function(){state.view='patterns';shell('Patrones','Alertas en español con regla, universo de comparación, alcance y guardrail metodológico.');try{const {data,error,count}=await sb.from('aml_pattern_alerts').select('alert_id,family,pattern_type,scope_type,scope_id,scope_label,strength,priority,title,summary,snapshot_id,updated_at,payload',{count:'exact'}).order('strength',{ascending:false,nullsFirst:false}).limit(150);if(error)throw error;content().innerHTML=`<section class="panel"><div class="panel-head"><h2>Pattern Intelligence</h2><span>${fmtNum(count||0)} alertas</span></div><div class="panel-body">${v16PatternCards(data||[])}</div></section>`;}catch(e){showContentError(e);}};

loadOverview=async function(){state.view='overview';shell('Resumen operativo','Cobertura y señales disponibles en el corte Fusion protegido.');try{const [entities,findings,sanctions,patterns,uafObserved,taxProfiles,topRes,recentRes]=await Promise.all([countRows('aml_entities'),countRows('aml_findings'),countRows('aml_sanctions'),countRows('aml_pattern_alerts'),countRows('aml_entities',q=>q.eq('is_uaf_observed',true)),countRows('aml_entity_tax_profile'),sb.from('aml_findings').select('finding_key,finding_type,entity_id,title,score_explore,score_supervise,score_investigate,evidence_count,payload').order('score_investigate',{ascending:false,nullsFirst:false}).limit(6),sb.from('aml_sanctions').select('sanction_id,event_date,regulator,entity_name,entity_id,identity_status,laft_direct,subject,payload').order('event_date',{ascending:false,nullsFirst:false}).limit(6)]);if(topRes.error)throw topRes.error;if(recentRes.error)throw recentRes.error;content().innerHTML=`<div class="kpis">${kpi('Entidades Fusion',entities,'Entity 360')}${kpi('Hallazgos',findings,'reglas explicables')}${kpi('Patrones',patterns,'Pattern Intelligence')}${kpi('Perfiles SII',taxProfiles,'enriquecimiento tributario')}</div><div class="grid-2"><section class="panel"><div class="panel-head"><h2>Hallazgos prioritarios</h2><span>algoritmo visible</span></div><div class="panel-body">${v16FindingCards(topRes.data||[],true)}</div></section><section class="panel"><div class="panel-head"><h2>Cobertura</h2><span>snapshot actual</span></div><div class="panel-body"><div class="list"><div class="list-item"><strong>${fmtNum(uafObserved)} entidades observadas en corte público UAF</strong><div class="meta">Observación pública; no reemplaza padrón operacional.</div></div><div class="list-item"><strong>${fmtNum(taxProfiles)} perfiles tributarios SII materializados</strong><div class="meta">Sólo universo Fusion, no los millones de registros SII.</div></div><div class="list-item"><strong>${fmtNum(patterns)} patrones explicables</strong><div class="meta">Strength es fuerza comparativa de regla, no probabilidad.</div></div></div></div></section><section class="panel"><div class="panel-head"><h2>Sanciones recientes</h2></div><div class="panel-body">${v16SanctionCards(recentRes.data||[])}</div></section><section class="panel"><div class="panel-head"><h2>Lectura metodológica</h2></div><div class="panel-body"><div class="rule-box"><strong>Hecho → regla → evidencia → interpretación</strong><p>La interfaz v0.16 hace visible la lógica de cada hallazgo y patrón, incluyendo factores de soporte y guardrails.</p></div></div></section></div>`;}catch(e){showContentError(e);}};

/* Re-render after the v0.15 bootstrap finishes, so the enhancement layer wins the race. */
setTimeout(()=>{if(state.user&&state.access)loadOverview();},0);
