(()=>{
'use strict';
const D=window.WB_CORE;
const A=window.WB_ADVANCED||{};
const $=s=>document.querySelector(s);
const fmt=n=>new Intl.NumberFormat('es-CL').format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const TYPE_LABEL={ENTITY_CONVERGENCE:'Convergencia multifuente',CONTEXTUAL_ANOMALY:'Anomalía contextual',SUPERVISORY_GAP:'Brecha supervisiva',PRUDENTIAL_SANCTION:'Sanción supervisor prudencial',GOVERNED_AML_SIGNAL:'Señal AML gobernada'};
const PROD_LABEL={RADAR_SII:'SII',RADAR_UAF:'UAF',RADAR_SANCIONES:'Sanciones',RADAR_CGR:'CGR',RADAR_DELICTUAL:'Delictual',RADAR_OSFL:'OSFL'};
const REGION_ALIAS={"Libertador Gral. Bernardo O'Higgins":"Libertador General Bernardo O'Higgins"};
const FINDING_FILE={ENTITY_CONVERGENCE:'ENTITY_CONVERGENCE',CONTEXTUAL_ANOMALY:'CONTEXTUAL_ANOMALY',SUPERVISORY_GAP:'SUPERVISORY_GAP',PRUDENTIAL_SANCTION:'PRUDENTIAL_SANCTION',GOVERNED_AML_SIGNAL:'GOVERNED_AML_SIGNAL'};
const loaded=new Set(['core']);
const cache={search:null,searchById:new Map(),entity:new Map(),geo:new Map(),evidence:null,anomalies:null,sanctions:null,cgr:null,findingsByType:{},fiscalSector:new Map(),fiscalRegion:new Map()};
const idx={sectorById:new Map(),sectorByName:new Map(),regionByName:new Map()};
let state={mode:'discovery',sector:null,region:null,entity:null,findingType:null};
let gapState={records:[],meta:null,query:'',commune:'',sectorId:'',page:1,pageSize:100};
let sanState={query:'',year:'',supervisor:'',identity:'',laft:'',page:1,pageSize:100};
let anomState={query:'',code:'',region:'',page:1,pageSize:100};
const CASE_KEY='aml_workbench_cases_v090';

function canonRegion(x){return REGION_ALIAS[x]||x||''}
function status(t,busy=false){const el=$('#dataStatus');if(el)el.innerHTML=`<span class="dot" style="background:${busy?'#e8a34b':'#54c78f'}"></span>${esc(t)}`}
function showError(target,msg){const el=typeof target==='string'?$(target):target;if(el)el.innerHTML=`<div class="missing"><b>No se pudo cargar este detalle.</b><br>${esc(msg)}<br><small>La mesa principal sigue operativa.</small></div>`}
function loadScript(src,key){
 if(loaded.has(key))return Promise.resolve();
 return new Promise((resolve,reject)=>{const sc=document.createElement('script');sc.src=src;sc.async=true;sc.onload=()=>{loaded.add(key);resolve()};sc.onerror=()=>reject(new Error(`No se pudo leer ${src}. Mantenga la carpeta data junto a index.html.`));document.head.appendChild(sc)});
}
async function ensureSearch(){if(cache.search)return;status('Cargando índice de entidades…',true);await loadScript('./data/search.js','search');cache.search=window.WB_SEARCH||[];cache.searchById=new Map(cache.search.map(x=>[x[0],x]));status('Listo')}
async function ensureEntity(id){if(cache.entity.has(id))return cache.entity.get(id);await ensureSearch();const stub=cache.searchById.get(id);if(!stub)return null;const shard=stub[7];status('Abriendo Entity 360…',true);await loadScript(`./data/entities/${shard}.js`,`entity-${shard}`);for(const e of (window.WB_ENTITY_SHARDS?.[shard]||[]))cache.entity.set(e.entity_id,e);status('Listo');return cache.entity.get(id)||null}
async function ensureEvidence(){if(cache.evidence)return;status('Cargando evidencia…',true);await loadScript('./data/evidence.js','evidence');cache.evidence=new Map((window.WB_EVIDENCE||[]).map(x=>[x.evidence_id,x]));status('Listo')}
async function ensureAnomalies(){if(cache.anomalies)return;status('Cargando anomalías contextuales…',true);await loadScript('./data/anomalies.js','anomalies');cache.anomalies=window.WB_ANOMALIES||[];status('Listo')}
async function ensureSanctions(){if(cache.sanctions)return;status('Cargando sanciones…',true);await loadScript('./data/sanctions.js','sanctions');cache.sanctions=window.WB_SANCTIONS||[];status('Listo')}
async function ensureCGR(){if(cache.cgr)return;status('Cargando eventos CGR…',true);await loadScript('./data/cgr.js','cgr');cache.cgr=window.WB_CGR||[];status('Listo')}

async function ensureFindingType(type){if(cache.findingsByType[type])return cache.findingsByType[type];const fn=FINDING_FILE[type];if(!fn)throw new Error('Tipo de hallazgo no reconocido');status(`Cargando ${TYPE_LABEL[type]||type}…`,true);await loadScript(`./data/findings_${fn}.js`,`finding-${fn}`);cache.findingsByType[type]=window.WB_FINDINGS_BY_TYPE?.[type]||[];status('Listo');return cache.findingsByType[type]}
async function ensureGeo(regionName){const f=(D.geo_regions.features||[]).find(x=>canonRegion(x.properties.region_name)===regionName);if(!f)return null;const code=String(f.properties.region_code).padStart(2,'0');if(cache.geo.has(code))return cache.geo.get(code);status('Cargando cartografía comunal…',true);await loadScript(`./data/geo/${code}.js`,`geo-${code}`);const g=window.WB_GEO?.[code]||null;cache.geo.set(code,g);status('Listo');return g}
async function ensureFiscalSector(sectorId){const sid=String(Number(sectorId)).padStart(2,'0');if(cache.fiscalSector.has(sid))return cache.fiscalSector.get(sid);status('Cargando sociedades candidatas del sector…',true);await loadScript(`./data/fiscalizacion/sector/sector_${sid}.js`,`fiscal-sector-${sid}`);const d=window.WB_FISCAL_SECTORS?.[sid]||{sector_id:Number(sectorId),records:[]};cache.fiscalSector.set(sid,d);status('Listo');return d}
function regionFile(name){return window.WB_FISCAL_MANIFEST?.regions?.[name]||norm(name).replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')}
async function ensureFiscalRegion(name){const key=regionFile(name);if(cache.fiscalRegion.has(key))return cache.fiscalRegion.get(key);status('Cargando sociedades candidatas de la región…',true);await loadScript(`./data/fiscalizacion/region/${key}.js`,`fiscal-region-${key}`);const d=window.WB_FISCAL_REGIONS?.[key]||{region:name,records:[]};cache.fiscalRegion.set(key,d);status('Listo');return d}

function score(f){return Number((f.decision_scores||{}).EXPLORAR||0)}
function kpi(label,value,sub,cls=''){return `<div class="card kpi"><small>${label}</small><b class="${cls}">${value}</b><span>${sub}</span></div>`}
function kpiAction(label,value,sub,onclick,cls=''){return `<div class="card kpi action" onclick="${onclick}" title="Abrir detalle individual"><small>${label}</small><b class="${cls}">${value}</b><span>${sub}</span></div>`}
function answer(title,desc,sv=null,chips=[]){return `<section class="card answer"><div class="answerTop"><div><div class="eyebrow">Respuesta analítica · snapshot real</div><h1>${title}</h1><p>${desc}</p></div><div class="scorebox ${sv==null?'':'clickable'}" ${sv==null?'':`onclick="WB.openScoreInfo(${Number(sv)})" title="Explicar IPA 2.0"`}><b>${sv==null?'—':Number(sv).toFixed(1)}</b><span>${sv==null?'sin score agregado':'IPA 2.0 · pincha para explicar'}</span></div></div><div class="chips">${chips.map((x,i)=>`<span class="chip ${i===0?'blue':''}">${esc(x)}</span>`).join('')}</div></section>`}
function panel(t,s,b){return `<section class="card panel"><div class="ph"><div><b>${t}</b>${s?`<p>${s}</p>`:''}</div></div>${b}</section>`}
function factor(n,v,max,label=null){let p=max?Math.min(100,Math.max(0,Number(v||0)/max*100)):0;return `<div class="factor"><span>${esc(n)}</span><div class="track"><i style="width:${p}%"></i></div><b>${label??fmt(v)}</b></div>`}
function evidenceCoverage(){const e=D.evidence_summary;return `<div class="contextBlock"><h3>Evidencia</h3><p>${fmt(e.total)} referencias · ${fmt(e.con_url)} con URL directa.</p></div>`}
function sourceContext(srcs=null){const cov=D.analytics.cobertura_radares.filter(x=>!srcs||srcs.includes(x.codigo));return `<div class="contextBlock"><h3>Fuentes</h3>${cov.map(x=>`<div class="evidence"><b>${esc(x.nombre)}</b><p>${fmt(x.entidades)} entidades · ${fmt(x.eventos)} eventos.</p></div>`).join('')}</div>${evidenceCoverage()}<div class="warnbox">Sanción ≠ LA/FT; actividad SII ≠ condición jurídica de sujeto obligado; contexto territorial ≠ atribución; missing ≠ cero.</div>`}
function renderFocus(){let S=[...D.sectors].sort((a,b)=>b.potenciales_no_observados_uaf_match_fuerte-a.potenciales_no_observados_uaf_match_fuerte).slice(0,3),R=[...D.regions].filter(x=>x.region!=='Sin información').sort((a,b)=>b.anomalias_contextuales-a.anomalias_contextuales).slice(0,2);$('#focusList').innerHTML=S.map(s=>`<div class="focus ${state.sector===s.sector_uaf?'active':''}" onclick="WB.previewSector(${s.sector_id})"><div class="type">Brecha supervisiva</div><h4>${esc(s.sector_uaf)}</h4><p>${fmt(s.potenciales_no_observados_uaf_match_fuerte)} candidatos · ${fmt(s.anomalias_contextuales)} anomalías.</p><div class="fm"><span class="mini">UAF/SII</span><span class="prio">${s.icp_cobertura_potencial_pct==null?'—':s.icp_cobertura_potencial_pct.toFixed(1)+'%'}</span></div></div>`).join('')+R.map(r=>`<div class="focus ${state.region===r.region?'active':''}" onclick="WB.previewRegion('${esc(r.region).replaceAll("'","\\'")}')"><div class="type">Contexto territorial</div><h4>${esc(r.region)}</h4><p>${fmt(r.anomalias_contextuales)} anomalías · ${fmt(r.entidades_fusion)} entidades.</p><div class="fm"><span class="mini">Territorio</span><span class="prio">${fmt(r.sanciones_observadas)}</span></div></div>`).join('')}
function eventYearChart(){let rows=D.analytics.eventos_por_anio.filter(x=>Number(x.anio)>=2020),W=620,H=205,p=24,max=Math.max(...rows.map(x=>x.total),1),bw=(W-p*2)/rows.length*.58;return `<svg class="chart" viewBox="0 0 ${W} ${H}">${[0,1,2,3,4].map(i=>`<line class="gridline" x1="${p}" x2="${W-p}" y1="${p+i*(H-p*2)/4}" y2="${p+i*(H-p*2)/4}"/>`).join('')}${rows.map((x,i)=>{let xx=p+i*(W-p*2)/rows.length+(W-p*2)/rows.length*.2,h=x.total/max*(H-p*2),yy=H-p-h;return `<rect x="${xx}" y="${yy}" width="${bw}" height="${h}" rx="3" fill="#2b6ff3"><title>${x.anio}: ${x.total}</title></rect><text class="axistext" x="${xx}" y="${H-7}">${String(x.anio).slice(2)}</text>`}).join('')}</svg>`}
function sectorTable(S){return `<div class="tablewrap"><table><thead><tr><th>Sector</th><th>UAF obs.</th><th>SII fuerte</th><th>Brecha*</th><th>ICP</th><th>Anom.</th></tr></thead><tbody>${S.map(s=>`<tr class="click" onclick="WB.openSector(${s.sector_id})"><td><b>${esc(s.sector_uaf)}</b></td><td>${fmt(s.inscritos_uaf_observados)}</td><td>${fmt(s.universo_sii_match_fuerte)}</td><td><button class="breachlink" onclick="event.stopPropagation();WB.openSectorGap(${s.sector_id})">${fmt(s.potenciales_no_observados_uaf_match_fuerte)}</button></td><td>${s.icp_cobertura_potencial_pct==null?'—':s.icp_cobertura_potencial_pct.toFixed(2)+'%'}</td><td>${fmt(s.anomalias_contextuales)}</td></tr>`).join('')}</tbody></table><div class="footer">* candidatos MATCH_FUERTE no observados en el corte público UAF; no equivale a incumplimiento.</div></div>`}
function regionTable(R){return `<div class="tablewrap"><table><thead><tr><th>Región</th><th>Entidades</th><th>UAF obs.</th><th>Brecha*</th><th>Sanc.</th><th>Anom.</th></tr></thead><tbody>${R.map(r=>`<tr class="click" onclick="WB.openRegion('${esc(r.region).replaceAll("'","\\'")}')"><td><b>${esc(r.region)}</b></td><td>${fmt(r.entidades_fusion)}</td><td>${fmt(r.inscritos_uaf_observados)}</td><td><button class="breachlink" onclick="event.stopPropagation();WB.openRegionGap('${esc(r.region).replaceAll("'","\\'")}')">${fmt(r.potenciales_no_observados_uaf_match_fuerte)}</button></td><td>${fmt(r.sanciones_observadas)}</td><td>${fmt(r.anomalias_contextuales)}</td></tr>`).join('')}</tbody></table></div>`}
function renderDiscovery(){setAppActive('home');renderFocus();const S=[...D.sectors].sort((a,b)=>b.potenciales_no_observados_uaf_match_fuerte-a.potenciales_no_observados_uaf_match_fuerte),R=[...D.regions].filter(x=>x.region!=='Sin información').sort((a,b)=>b.anomalias_contextuales-a.anomalias_contextuales),summary=D.workbench_summary.kpis;$('#canvas').innerHTML=answer('Mesa avanzada de inteligencia AML sobre Fusion','El Workbench combina descubrimiento, fiscalización, sanciones, grafos, territorio, evidencia y fichas sin mezclar sus semánticas. Todo lo que aparece debajo proviene del snapshot real o se identifica expresamente como capacidad pendiente.',null,[D.manifest.snapshot_id,`${fmt(summary.entidades_fusion)} entidades`,`${fmt(summary.anomalias_contextuales)} anomalías`,`${fmt(D.analytics.kpis.relaciones)} relaciones`])+`<div class="kpis">${kpi('Entidades Fusion',fmt(summary.entidades_fusion),'universo completo')}${kpi('UAF observados',fmt(summary.inscritos_uaf_observados),'corte público')}${kpi('Brecha · RUT únicos',fmt(summary.candidatos_no_observados_uaf_match_fuerte_unicos),'screening')}${kpi('Sanciones',fmt(A.sanction_summary?.total||974),'eventos')}</div>${panel('Aplicaciones operativas','Selecciona una capacidad; la misma mesa conserva filtros, contexto y drill-down.',appCards())}<div class="grid two" style="margin-top:10px">${panel('Eventos 2020–2026','Serie real por año de publicación/evento.',eventYearChart())}${panel('Principales brechas de screening','No equivalen a incumplimiento.',sectorTable(S.slice(0,10)))}</div><div class="grid equal" style="margin-top:10px">${panel('Sectores','55 actividades UAF.',sectorTable(S.slice(0,18)))}${panel('Regiones','Contexto territorial.',regionTable(R))}</div>`;$('#context').innerHTML=`<div class="contextBlock"><h3>Nuevas capacidades</h3><div class="markbar">${mark('Sanciones 360','alert')}${mark('Redes','context')}${mark('Comparador','info')}${mark('Casos locales','context')}${mark('CGR','info')}${mark('Ficha analítica','good')}</div></div>${sourceContext()}`}

function openSector(id){const s=idx.sectorById.get(Number(id));if(!s)return;state={mode:'sector',sector:s.sector_uaf,region:null,entity:null,findingType:null};$('#sector').value=s.sector_uaf;$('#region').value='';renderSector()}
function renderSector(){renderFocus();const s=idx.sectorByName.get(norm(state.sector));if(!s)return renderDiscovery();const med=[...D.sectors].filter(x=>x.icp_cobertura_potencial_pct!=null).map(x=>x.icp_cobertura_potencial_pct).sort((a,b)=>a-b);const bm=med.length?med[Math.floor(med.length/2)]:null;let rows=D.matrix.filter(x=>x.sector_id===s.sector_id);if(state.region)rows=rows.filter(x=>x.region===state.region);rows.sort((a,b)=>b.sii_match_fuerte-a.sii_match_fuerte);const regionChip=state.region?` · ${state.region}`:'';$('#canvas').innerHTML=answer(s.sector_uaf+regionChip,'Vista sectorial con universo UAF/SII y contexto regional real. La brecha ahora permite individualizar las sociedades que la explican.',null,[`${fmt(s.inscritos_uaf_observados)} UAF observados`,`${fmt(s.universo_sii_match_fuerte)} SII match fuerte`,`${fmt(s.potenciales_no_observados_uaf_match_fuerte)} candidatos`])+`<div class="kpis">${kpi('UAF observados',fmt(s.inscritos_uaf_observados),'corte público')}${kpi('SII match fuerte',fmt(s.universo_sii_match_fuerte),'screening')}${kpiAction('Brecha potencial',fmt(state.region?(rows[0]?.potenciales_no_observados_uaf_match_fuerte||0):s.potenciales_no_observados_uaf_match_fuerte),'pincha para individualizar',`WB.openSectorGap(${s.sector_id}${state.region?`, '${esc(state.region).replaceAll("'","\'")}'`:''})`,'amber')}${kpi('ICP',s.icp_cobertura_potencial_pct==null?'No disponible':s.icp_cobertura_potencial_pct.toFixed(2)+'%',bm==null?'sin benchmark':`mediana sectores ${bm.toFixed(2)}%`)}</div><div class="grid two">${panel('Distribución regional','Matriz real sector × región.',sectorRegionTable(rows.slice(0,35)))}${panel('Contexto disponible','Seleccione qué detalle desea abrir.',`<button class="button" onclick="WB.openSectorGap(${s.sector_id}${state.region?`, '${esc(state.region).replaceAll("'","\'")}'`:''})">Individualizar brecha</button> <button class="button" onclick="WB.loadSectorBreaches(${s.sector_id})">Hallazgos de brecha</button> <button class="button" onclick="WB.loadSectorSanctions(${s.sector_id})">Cargar sanciones</button> <button class="button" onclick="WB.loadSectorAnomalies(${s.sector_id})">Cargar anomalías SII</button><div id="sectorDetail" style="margin-top:9px"><div class="note">La lista individual de screening se carga desde el detalle fiscalización del snapshot, no se reconstruye desde el agregado.</div></div>`)}</div>`;$('#context').innerHTML=sourceContext(['RADAR_UAF','RADAR_SII','RADAR_SANCIONES'])}

function sectorRegionTable(a){return `<div class="tablewrap"><table><thead><tr><th>Región</th><th>SII fuerte</th><th>UAF obs.</th><th>Brecha</th></tr></thead><tbody>${a.map(x=>`<tr class="click" onclick="WB.openRegion('${esc(x.region).replaceAll("'","\'")}')"><td><b>${esc(x.region)}</b></td><td>${fmt(x.sii_match_fuerte)}</td><td>${fmt(x.inscritos_uaf_observados)}</td><td><button class="breachlink" onclick="event.stopPropagation();WB.openSectorRegionGap(${x.sector_id},'${esc(x.region).replaceAll("'","\'")}')">${fmt(x.potenciales_no_observados_uaf_match_fuerte)}</button></td></tr>`).join('')}</tbody></table></div>`}

async function loadSectorFinding(type,sectorId){const el=$('#sectorDetail');el.innerHTML='<div class="loadingmini">Cargando detalle real…</div>';try{const a=await ensureFindingType(type),s=idx.sectorById.get(Number(sectorId));const fs=a.filter(f=>(f.sector_names||[]).includes(s.sector_uaf)&&findingPass(f));el.innerHTML=findingsTable(fs,80)}catch(e){showError(el,e.message)}}
async function loadSectorAnomalies(sectorId){const el=$('#sectorDetail');el.innerHTML='<div class="loadingmini">Cargando anomalías…</div>';try{await ensureAnomalies();const a=cache.anomalies.filter(x=>(x.sector_ids||[]).includes(Number(sectorId)));el.innerHTML=anomalyTable(a.slice(0,120))}catch(e){showError(el,e.message)}}

function openRegion(name){state={mode:'region',sector:null,region:name,entity:null,findingType:null};$('#region').value=name;$('#sector').value='';renderRegion()}
function renderRegion(){renderFocus();const r=idx.regionByName.get(state.region);if(!r)return renderDiscovery();const rows=D.matrix.filter(x=>x.region===r.region).sort((a,b)=>b.sii_match_fuerte-a.sii_match_fuerte);const comm=D.map_commune_metrics.filter(x=>canonRegion(x.region_name)===r.region).sort((a,b)=>b.mapped_entity_count-a.mapped_entity_count);$('#canvas').innerHTML=answer(r.region,'Contexto territorial real. La brecha regional puede abrirse hasta RUT/razón social y mantiene separados los pares sector–entidad de los RUT únicos.',null,[`${fmt(r.entidades_fusion)} entidades`,`${fmt(r.sanciones_observadas)} sanciones`,`${fmt(r.anomalias_contextuales)} anomalías`])+`<div class="kpis">${kpi('Entidades Fusion',fmt(r.entidades_fusion),'identidad fusionada')}${kpi('UAF observados',fmt(r.inscritos_uaf_observados),'corte público')}${kpiAction('Brecha potencial',fmt(r.potenciales_no_observados_uaf_match_fuerte),'pincha para individualizar',`WB.openRegionGap('${esc(r.region).replaceAll("'","\'")}')`,'amber')}${kpi('Anomalías',fmt(r.anomalias_contextuales),'contexto SII')}</div><div class="grid two">${panel('Mapa comunal','La geometría de esta región se carga separadamente.',`<div id="commMap"><button class="button" onclick="WB.loadRegionMap('${esc(r.region).replaceAll("'","\'")}')">Cargar mapa comunal</button></div>`)}${panel('Sectores que explican screening','Cada brecha sectorial también es individualizable.',regionSectorTable(rows.slice(0,30)))}</div><div class="grid equal" style="margin-top:10px">${panel('Comunas · métricas','Disponibles sin cargar geometría.',communeTable(comm.slice(0,45)))}${panel('Hallazgos','Seleccione un tipo para cargar.',`<button class="button" onclick="WB.openRegionGap('${esc(r.region).replaceAll("'","\'")}')">Individualizar brecha</button> <button class="button" onclick="WB.loadRegionFinding('SUPERVISORY_GAP','${esc(r.region).replaceAll("'","\'")}')">Hallazgos agregados</button> <button class="button" onclick="WB.loadRegionFinding('PRUDENTIAL_SANCTION','${esc(r.region).replaceAll("'","\'")}')">Sanciones</button><div id="regionDetail" style="margin-top:9px"><div class="note">La lista individual se carga sólo al solicitarla.</div></div>`)}</div>`;$('#context').innerHTML=sourceContext()+`<div class="contextBlock"><h3>Contexto delictual</h3><p>Último año: ${D.geo_summary.delictual_latest_year}. Sólo contexto territorial.</p></div>`}

function regionSectorTable(a){return `<div class="tablewrap"><table><thead><tr><th>Sector</th><th>SII fuerte</th><th>UAF obs.</th><th>Brecha</th></tr></thead><tbody>${a.map(x=>`<tr class="click" onclick="WB.openSector(${x.sector_id})"><td><b>${esc(x.sector_uaf)}</b></td><td>${fmt(x.sii_match_fuerte)}</td><td>${fmt(x.inscritos_uaf_observados)}</td><td><button class="breachlink" onclick="event.stopPropagation();WB.openSectorRegionGap(${x.sector_id},'${esc(x.region).replaceAll("'","\'")}')">${fmt(x.potenciales_no_observados_uaf_match_fuerte)}</button></td></tr>`).join('')}</tbody></table></div>`}

function communeTable(a){return `<div class="tablewrap"><table><thead><tr><th>Comuna</th><th>Entidades</th><th>SO</th><th>Grafo</th><th>Ctx delictual</th></tr></thead><tbody>${a.map(x=>`<tr><td><b>${esc(x.commune_name)}</b></td><td>${fmt(x.mapped_entity_count)}</td><td>${fmt(x.obliged_entity_count)}</td><td>${fmt(x.graph_connected_entity_count)}</td><td>${x.delictual_predicate_context_value==null?'—':fmt(x.delictual_predicate_context_value)}</td></tr>`).join('')}</tbody></table></div>`}
async function loadRegionMap(name){const el=$('#commMap');el.innerHTML='<div class="loadingmini">Cargando geometría…</div>';try{const g=await ensureGeo(name),metrics=D.map_commune_metrics.filter(x=>canonRegion(x.region_name)===name);el.innerHTML=g?communeMap(g,metrics):'<div class="missing">Geometría no disponible.</div>'}catch(e){showError(el,e.message)}}
async function loadRegionFinding(type,name){const el=$('#regionDetail');el.innerHTML='<div class="loadingmini">Cargando hallazgos…</div>';try{const a=await ensureFindingType(type),fs=a.filter(f=>canonRegion(f.region)===name&&findingPass(f));el.innerHTML=findingsTable(fs,80)}catch(e){showError(el,e.message)}}

function raw(p){let x=p[0]*Math.PI/180,y=Math.max(-85,Math.min(85,p[1]))*Math.PI/180;return[x,Math.log(Math.tan(Math.PI/4+y/2))]}
function walk(g,fn){let c=g.coordinates;if(g.type==='Polygon')c.forEach(r=>r.forEach(fn));else c.forEach(p=>p.forEach(r=>r.forEach(fn)))}
function bounds(fs){let a=Infinity,b=Infinity,c=-Infinity,d=-Infinity;fs.forEach(f=>walk(f.geometry,p=>{let q=raw(p);a=Math.min(a,q[0]);c=Math.max(c,q[0]);b=Math.min(b,q[1]);d=Math.max(d,q[1])}));return[a,b,c,d]}
function projector(z,W=520,H=370){let P=12,dx=z[2]-z[0],dy=z[3]-z[1],s=Math.min((W-2*P)/dx,(H-2*P)/dy),ox=(W-dx*s)/2,oy=(H-dy*s)/2;return p=>{let q=raw(p);return[ox+(q[0]-z[0])*s,H-(oy+(q[1]-z[1])*s)]}}
function path(g,p){let d='',ring=r=>{if(!r.length)return;let q=p(r[0]);d+=`M${q[0].toFixed(1)},${q[1].toFixed(1)}`;for(let i=1;i<r.length;i++){q=p(r[i]);d+=`L${q[0].toFixed(1)},${q[1].toFixed(1)}`}d+='Z'};if(g.type==='Polygon')g.coordinates.forEach(ring);else g.coordinates.forEach(x=>x.forEach(ring));return d}
function heat(v,max){if(!v)return'#e8edf3';let t=Math.sqrt(v/Math.max(max,1));return t>.8?'#9f3944':t>.55?'#d96c3b':t>.3?'#e8a16e':'#dce8fb'}
function communeMap(geo,metrics){const fs=geo.features,z=bounds(fs),p=projector(z),m=new Map(metrics.map(x=>[x.commune_code,x])),vals=fs.map(f=>m.get(f.properties.commune_code)?.mapped_entity_count||0),mx=Math.max(...vals,1);return `<svg class="map" viewBox="0 0 520 370">${fs.map((f,i)=>`<path class="territory" d="${path(f.geometry,p)}" fill="${heat(vals[i],mx)}"><title>${esc(f.properties.commune_name)} · ${fmt(vals[i])} entidades</title></path>`).join('')}</svg>`}

function findingPass(f){const src=$('#source').value,n=Number($('#minsources').value||1),r=$('#region').value,s=$('#sector').value;return (!src||(f.producer_ids||[]).includes(src))&&(f.source_independence_count||1)>=n&&(!r||canonRegion(f.region)===r)&&(!s||(f.sector_names||[]).includes(s))}
function findingsTable(fs,n=80){fs=[...fs].sort((a,b)=>score(b)-score(a)).slice(0,n);if(!fs.length)return'<div class="missing">Sin registros para el filtro actual.</div>';return `<div class="tablewrap"><table><thead><tr><th>Hallazgo</th><th>Tipo</th><th>Región</th><th>Fuentes</th><th>IPA</th></tr></thead><tbody>${fs.map(f=>`<tr class="click" onclick="WB.previewFinding('${f.finding_id}','${f.finding_type}')"><td><b>${esc(f.title)}</b><br><span style="color:#8994a4">${esc(f.entity_rut||f.commune||'')}</span></td><td>${esc(TYPE_LABEL[f.finding_type]||f.finding_type)}</td><td>${esc(f.region||'—')}</td><td>${f.source_independence_count||1}</td><td><b>${score(f).toFixed(1)}</b></td></tr>`).join('')}</tbody></table></div>`}
function anomalyTable(a){if(!a.length)return'<div class="missing">Sin anomalías para este filtro.</div>';return `<div class="tablewrap"><table><thead><tr><th>Entidad</th><th>Indicador</th><th>Región</th></tr></thead><tbody>${a.map(x=>`<tr class="click" onclick="WB.openEntity('${x.entity_id}')"><td><b>${esc(x.nombre||x.rut||x.entity_id)}</b><br>${esc(x.rut||'')}</td><td>${esc(x.titulo)}</td><td>${esc(x.region||'—')}</td></tr>`).join('')}</tbody></table></div>`}
async function renderFindingList(type){state={mode:'finding',sector:null,region:null,entity:null,findingType:type};$('#sector').value='';$('#region').value='';$('#canvas').innerHTML=answer(TYPE_LABEL[type]||type,'Cargando el archivo específico de este tipo de hallazgo…',null)+`<div class="loadingmini">Un momento…</div>`;try{const a=await ensureFindingType(type),fs=a.filter(findingPass);$('#canvas').innerHTML=answer(TYPE_LABEL[type]||type,`Vista sobre ${fmt(fs.length)} hallazgos reales.`,fs.length?Math.max(...fs.map(score)):null,[`${fmt(fs.length)} registros`])+panel('Hallazgos','Ordenados por IPA 2.0.',findingsTable(fs,150));$('#context').innerHTML=sourceContext()}catch(e){showError('#canvas',e.message)}}
async function openFinding(id,type){try{const a=await ensureFindingType(type),f=a.find(x=>x.finding_id===id);if(!f)return;const eid=f.scope?.entity_ids?.[0];if(eid){await openEntity(eid);$('#context').innerHTML=findingContext(f)+$('#context').innerHTML}else{$('#context').innerHTML=findingContext(f)}}catch(e){showError('#context',e.message)}}
function findingContext(f){const features=f.decision_features||{},facts=f.decision_facts||{};return `<div class="contextBlock"><h3>${esc(TYPE_LABEL[f.finding_type]||f.finding_type)}</h3><p>${esc(f.explanation)}</p><div class="actionrow"><button class="actionbtn" onclick="WB.addCase('FINDING','${esc(f.finding_id)}','${esc(f.title).replaceAll("'","\\'")}','${esc(f.region||'').replaceAll("'","\\'")}',{type:'${esc(f.finding_type)}'})">★ Guardar finding</button><button class="actionbtn" onclick="WB.openFindingEvidence('${esc(f.finding_id)}','${esc(f.finding_type)}')">Evidencia</button></div></div><div class="contextBlock"><h3>IPA 2.0 · factores observables</h3>${Object.entries(features).map(([k,v])=>factor(k.replaceAll('_',' '),v,100,Number(v).toFixed(1))).join('')}</div><div class="contextBlock"><h3>Hechos</h3>${Object.entries(facts).map(([k,v])=>`<div class="evidence"><b>${esc(k)}</b><p>${esc(v)}</p></div>`).join('')}</div>${(f.supporting_factors||[]).length?`<div class="contextBlock"><h3>Factores de soporte</h3><p>${f.supporting_factors.map(esc).join(' · ')}</p></div>`:''}${(f.contradicting_factors||[]).length?`<div class="contextBlock"><h3>Limitaciones / contradictores</h3><p>${f.contradicting_factors.map(esc).join(' · ')}</p></div>`:''}${(f.suggested_next_steps||[]).length?`<div class="contextBlock"><h3>Siguientes pasos sugeridos</h3><p>${f.suggested_next_steps.map(esc).join(' · ')}</p></div>`:''}<div class="warnbox">${esc(f.guardrail||'Prioridad analítica no equivale a riesgo o ilegalidad.')}</div>`}

async function runQuery(){const q=$('#query').value.trim();if(!q){state={mode:'discovery',sector:null,region:null,entity:null,findingType:null};return renderDiscovery()}const ql=norm(q);const sec=sectorInQuery(q),reg=regionInQuery(q);if(ql.includes('presupuesto')||ql.includes('gasto publico')||ql.includes('contrato')||ql.includes('proveedor'))return renderPendingSpend();if(ql.includes('cgr')||ql.includes('contraloria'))return WB.showApp('cgr');if(ql.includes('red')||ql.includes('grafo')||ql.includes('relacion'))return WB.showApp('network');if(ql.includes('compar'))return WB.showApp('compare');if(ql.includes('caso')||ql.includes('bandeja'))return WB.showApp('cases');if(ql.includes('brecha')&&sec)return WB.openSectorGap(sec.sector_id,reg?.region||null);if(ql.includes('brecha')&&reg)return WB.openRegionGap(reg.region);if(ql.includes('sancion'))return WB.showApp('sanctions');if(ql.includes('brecha'))return renderFindingList('SUPERVISORY_GAP');if(ql.includes('converg'))return WB.showApp('convergence');if(ql.includes('senal'))return renderFindingList('GOVERNED_AML_SIGNAL');if(ql.includes('anom'))return WB.showApp('anomalies');if(sec){state={mode:'sector',sector:sec.sector_uaf,region:reg?.region||null,entity:null,findingType:null};$('#sector').value=sec.sector_uaf;$('#region').value=reg?.region||'';return renderSector()}if(reg)return WB.openRegion(reg.region);return renderSearch(q)}
function tokens(s){const stop=new Set(['de','del','la','las','los','el','y','o','a','empresas','empresa','dedicadas','dedicada']);return norm(s).replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(x=>x.length>2&&!stop.has(x))}
function sectorInQuery(q){let nq=norm(q),qt=new Set(tokens(q)),best=null,bscore=0;for(const s of D.sectors){let ns=norm(s.sector_uaf);if(nq.includes(ns))return s;let st=tokens(s.sector_uaf),hit=st.filter(x=>qt.has(x)).length,sc=st.length?hit/st.length:0;if(hit&&sc>bscore){best=s;bscore=sc}}return bscore>=.34?best:null}
function regionInQuery(q){let nq=norm(q);return D.regions.find(r=>r.region!=='Sin información'&&nq.includes(norm(r.region)))||null}
async function renderSearch(q){$('#canvas').innerHTML=answer(`Buscando “${esc(q)}”`,'El índice de 47.186 entidades se carga sólo en la primera búsqueda.',null)+`<div class="loadingmini">Cargando índice local…</div>`;try{await ensureSearch();const nq=norm(q);let a=cache.search.filter(e=>norm(e[1]).includes(nq)||norm(e[2]).includes(nq)).slice(0,100);const exact=a.find(e=>norm(e[1])===nq||norm(e[2])===nq);if(exact)return WB.openEntity(exact[0]);$('#canvas').innerHTML=answer(`Resultados para “${esc(q)}”`,'Búsqueda real sobre Entity Hub. El detalle de una entidad se carga desde su fragmento de ~150 KB.',null,[`${fmt(a.length)} mostradas`])+panel('Entidades','Máximo 100 resultados.',`<div class="searchResults">${a.map(e=>`<div class="searchItem" onclick="WB.openEntity('${e[0]}')"><b>${esc(e[2]||e[1]||e[0])}</b><small>${esc(e[1])} · ${esc(e[3])} · ${esc(e[4]||'sin región')} · ${e[6]} fuente(s)</small></div>`).join('')||'<div class="missing">Sin coincidencias.</div>'}</div>`);$('#context').innerHTML=sourceContext()}catch(e){showError('#canvas',e.message)}}
async function openEntity(id){state={mode:'entity',sector:null,region:null,entity:id,findingType:null};$('#sector').value='';$('#region').value='';renderFocus();$('#canvas').innerHTML=answer('Abriendo Entity 360','Se está leyendo sólo el fragmento local de esta entidad.',null)+`<div class="loadingmini">Cargando perfil…</div>`;try{const e=await ensureEntity(id);if(!e)return showError('#canvas','Entidad no disponible en el fragmento esperado.');renderEntity(e)}catch(e){showError('#canvas',e.message)}}
function renderEntity(e){setAppActive('home');const rels=e.relaciones||[],signals=e.senales||[],marks=entityMarks(e),ready=entityReadiness(e);$('#canvas').innerHTML=answer(e.nombre||e.rut,`Entity 360 real. Identidad ${e.identity_method_es||e.identity_method}; cada marca describe información disponible y no se suma como riesgo.`,e.aml?.score??null,[e.rut||e.entity_id,e.tipo_entidad_es||e.tipo_entidad,e.ubicacion?.comuna||'sin comuna',`${(e.fuentes||[]).length} fuente(s)`])+`<div class="markbar">${marks.map(x=>mark(x[0],x[1])).join('')}</div><div class="actionrow"><button class="actionbtn primary" onclick="WB.caseEntity('${e.entity_id}')">★ Guardar en Casos</button><button class="actionbtn" onclick="WB.showEntityBrief('${e.entity_id}')">Ficha analítica</button><button class="actionbtn" onclick="WB.exportEntity('${e.entity_id}')">Exportar JSON</button></div><div class="kpis">${kpi('Eventos',fmt(e.event_count),'asociados')}${kpi('Relaciones',fmt(rels.length),'observadas')}${kpi('Señales',fmt(signals.length),'gobernadas')}${kpi('Evidencias',fmt((e.evidence_ids||[]).length),'referencias')}</div><div class="grid two">${panel('Red observada','Contrapartes reales. Pincha un nodo para cambiar de Entity 360.',entityNetwork(e))}${panel('Timeline','Eventos materializados.',entityTimeline(e.eventos||[]))}</div><div class="grid equal" style="margin-top:10px">${panel('Cobertura de ficha','Disponibilidad de dimensiones; no es score de riesgo.',`${donut(ready)}<div style="margin-top:8px">${entityBriefHTML(e)}</div>`)}${panel('Herramientas de profundización','Carga únicamente lo solicitado.',`<button class="button" onclick="WB.loadEntityAnomalies('${e.entity_id}')">Anomalías SII</button> <button class="button" onclick="WB.loadEntityEvidence('${e.entity_id}')">Evidencia con URL</button><div id="entityExtra" style="margin-top:9px"><div class="note"><b>Roles:</b> ${(e.roles_es||e.roles||[]).map(esc).join(' · ')||'—'}<br><b>Fuentes:</b> ${(e.fuentes||[]).map(x=>PROD_LABEL[x]||x).join(' · ')||'—'}<br><b>Ubicación:</b> ${esc(e.ubicacion?.comuna||'—')} · ${esc(e.ubicacion?.region||'—')}</div></div>`)}</div>`;$('#context').innerHTML=`<div class="contextBlock"><h3>Identidad</h3><p>${esc(e.rut||'')} · confianza ${e.identity_confidence??'—'} · ${esc(e.identity_method_es||e.identity_method)}</p></div><div class="contextBlock"><h3>Marcas de ficha</h3><div class="markbar">${marks.map(x=>mark(x[0],x[1])).join('')}</div></div>${sourceContext(e.fuentes||[])}`}
function entityNetwork(e){let rels=(e.relaciones||[]).slice(0,10),W=520,H=285,cx=260,cy=142,r=95,items=rels.map((x,i)=>{let a=Math.PI*2*i/Math.max(rels.length,1)-Math.PI/2;return {...x,x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r}});return `<svg class="net" viewBox="0 0 ${W} ${H}">${items.map(x=>`<line class="edge" x1="${cx}" y1="${cy}" x2="${x.x}" y2="${x.y}"/>`).join('')}<circle class="node" cx="${cx}" cy="${cy}" r="34" fill="#2b6ff3"/><text class="nlabel" x="${cx}" y="${cy+3}" fill="#fff">ENTIDAD</text>${items.map(x=>`<circle class="node" cx="${x.x}" cy="${x.y}" r="19" fill="#278563" onclick="WB.openEntity('${x.contraparte_id}')"/><text class="nlabel" x="${x.x}" y="${x.y+31}">${esc((x.contraparte_nombre||x.contraparte_id).slice(0,24))}</text>`).join('')}</svg>${rels.length?'':'<div class="missing">Sin relaciones entidad–entidad observadas.</div>'}`}
function entityTimeline(ev){if(!ev.length)return'<div class="missing">No hay eventos con identidad resuelta.</div>';return `<div class="timeline">${[...ev].sort((a,b)=>String(b.fecha||'').localeCompare(String(a.fecha||''))).map(x=>`<div class="event"><small>${esc((x.fecha||'sin fecha').slice(0,10))}</small><b>${esc(x.tipo_es||x.tipo)}</b><p>${esc(PROD_LABEL[x.productor]||x.productor)} · ${esc(x.titulo||'')}</p></div>`).join('')}</div>`}
async function loadEntityAnomalies(id){const el=$('#entityExtra');el.innerHTML='<div class="loadingmini">Cargando anomalías…</div>';try{await ensureAnomalies();const a=cache.anomalies.filter(x=>x.entity_id===id);el.innerHTML=anomalyTable(a.slice(0,120))}catch(e){showError(el,e.message)}}
async function loadEntityEvidence(id){const el=$('#entityExtra');el.innerHTML='<div class="loadingmini">Cargando evidencia…</div>';try{await ensureEvidence();const e=cache.entity.get(id),a=(e.evidence_ids||[]).map(x=>cache.evidence.get(x)).filter(Boolean);el.innerHTML=a.length?a.map(x=>`<div class="evidence"><b>${esc(PROD_LABEL[x.producer_id]||x.producer_id)} · ${esc(x.quality_status||'')}</b><p>${esc(x.excerpt||x.source_id||'')}</p><a href="${esc(x.source_url)}" target="_blank" rel="noopener">Abrir fuente ↗</a></div>`).join(''):`<div class="missing">${fmt((e.evidence_ids||[]).length)} referencia(s), sin URL directa en el índice disponible.</div>`}catch(e){showError(el,e.message)}}

function decodeSectorRec(r){return {sector_id:gapState.meta?.sector_id||null,entity_id:r[0],rut:r[1],nombre:r[2],region:r[3],comuna:r[4],codigos:r[5]||[],in_fusion:!!r[6]}}
function decodeRegionRec(r,regionName){return {sector_id:r[0],entity_id:r[1],rut:r[2],nombre:r[3],region:regionName,comuna:r[4],codigos:r[5]||[],in_fusion:!!r[6]}}
function activityText(codes){return (codes||[]).map(c=>`${c} · ${window.WB_ACTECO?.[c]||'glosa no disponible'}`).join(' | ')}
function uniqueCount(a){return new Set(a.map(x=>x.rut).filter(Boolean)).size}
function gapFiltered(){let a=gapState.records,nq=norm(gapState.query),com=gapState.commune,sid=gapState.sectorId;return a.filter(x=>(!com||(x.comuna||'Sin información')===com)&&(!sid||String(x.sector_id)===String(sid))&&(!nq||norm(`${x.rut} ${x.nombre} ${x.region} ${x.comuna} ${(x.codigos||[]).join(' ')} ${activityText(x.codigos)}`).includes(nq)))}
function gapControls(){const comm=[...new Set(gapState.records.map(x=>x.comuna||'Sin información'))].sort((a,b)=>a.localeCompare(b,'es')),sectorOpts=gapState.meta?.scope==='region'?[...new Set(gapState.records.map(x=>x.sector_id))].sort((a,b)=>Number(a)-Number(b)):[];return `<div class="gapbar"><input id="gapSearch" value="${esc(gapState.query)}" placeholder="Buscar RUT, razón social, código o actividad…" oninput="WB.gapSearch(this.value)"><select onchange="WB.gapCommune(this.value)"><option value="">Todas las comunas</option>${comm.map(x=>`<option ${gapState.commune===x?'selected':''}>${esc(x)}</option>`).join('')}</select>${sectorOpts.length?`<select onchange="WB.gapSector(this.value)"><option value="">Todos los sectores</option>${sectorOpts.map(id=>`<option value="${id}" ${String(gapState.sectorId)===String(id)?'selected':''}>${esc(idx.sectorById.get(Number(id))?.sector_uaf||id)}</option>`).join('')}</select>`:''}<div class="grow"></div><button class="smallbtn" onclick="WB.exportGapCSV()">Exportar CSV</button></div>`}
function gapTable(){const f=gapFiltered(),pages=Math.max(1,Math.ceil(f.length/gapState.pageSize));gapState.page=Math.max(1,Math.min(gapState.page,pages));const start=(gapState.page-1)*gapState.pageSize,rows=f.slice(start,start+gapState.pageSize);return `${gapControls()}<div class="gapHeader"><div class="count">${fmt(f.length)}</div><div class="sub">registros filtrados · ${fmt(uniqueCount(f))} RUT únicos</div></div><div class="tablewrap" style="max-height:520px"><table><thead><tr><th>Sociedad / RUT</th><th>Región / comuna</th>${gapState.meta?.scope==='region'?'<th>Sector UAF</th>':''}<th>Actividad SII</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr class="screeningRow click" onclick="WB.openCandidate('${esc(x.entity_id)}','${esc(x.rut)}')"><td><div class="name">${esc(x.nombre||'—')}</div><div class="rut">${esc(x.rut||'—')}</div></td><td>${esc(x.region||'—')}<br><span style="color:#8994a4">${esc(x.comuna||'—')}</span></td>${gapState.meta?.scope==='region'?`<td>${esc(idx.sectorById.get(Number(x.sector_id))?.sector_uaf||x.sector_id)}</td>`:''}<td class="activitiesMini">${(x.codigos||[]).slice(0,3).map(c=>`<b>${esc(c)}</b> ${esc((window.WB_ACTECO?.[c]||'').slice(0,70))}`).join('<br>')}${(x.codigos||[]).length>3?`<br>+${x.codigos.length-3} actividad(es)`:''}</td><td><span class="screeningTag">No observado UAF</span>${x.in_fusion?'<br><span class="fusionTag" style="margin-top:4px">Entity 360</span>':''}</td><td><button class="smallbtn" onclick="event.stopPropagation();WB.openCandidate('${esc(x.entity_id)}','${esc(x.rut)}')">Ficha</button></td></tr>`).join('')||'<tr><td colspan="6"><div class="emptyState">Sin sociedades para estos filtros.</div></td></tr>'}</tbody></table></div><div class="pager"><span>Página ${gapState.page} de ${pages}</span><button onclick="WB.gapPage(-1)" ${gapState.page<=1?'disabled':''}>← Anterior</button><button onclick="WB.gapPage(1)" ${gapState.page>=pages?'disabled':''}>Siguiente →</button></div>`}
function renderGapView(){const f=gapFiltered(),meta=gapState.meta||{},desc=meta.scope==='sector'?`Sociedades con al menos un MATCH_FUERTE SII para ${meta.sector_uaf} y no observadas en el corte público UAF${meta.region?` en ${meta.region}`:''}.`:`Registros sector–RUT con MATCH_FUERTE SII no observados en UAF para ${meta.region}. Una sociedad puede aparecer en más de un sector.`;$('#canvas').innerHTML=answer(meta.scope==='sector'?`Brecha potencial · ${meta.sector_uaf}${meta.region?` · ${meta.region}`:''}`:`Brecha potencial · ${meta.region}`,desc,null,[`${fmt(gapState.records.length)} registros`,`${fmt(uniqueCount(gapState.records))} RUT únicos`,'MATCH_FUERTE','No observado UAF'])+`<div class="kpis">${kpi('Registros screening',fmt(gapState.records.length),meta.scope==='region'?'pares sector–RUT':'sociedades del sector')}${kpi('RUT únicos',fmt(uniqueCount(gapState.records)),'deduplicados')}${kpi('Con Entity 360',fmt(gapState.records.filter(x=>x.in_fusion).length),'ya canónicos en Fusion')}${kpi('Estado SII','Vigentes','ACTIVE_AS_PUBLISHED')}</div>${panel('Sociedades que explican la brecha','Pincha una fila para ver su ficha de screening.',`<div id="gapTable">${gapTable()}</div>`)}`;$('#context').innerHTML=`<div class="contextBlock"><h3>Semántica de la lista</h3><p>Estos registros provienen directamente del detalle de fiscalización del snapshot. <b>No observado UAF</b> significa que no fue encontrado en el universo público UAF utilizado por el radar; no demuestra jurídicamente falta de inscripción.</p></div><div class="screeningGuard">MATCH_FUERTE identifica correspondencia robusta entre actividad SII y actividad UAF según el crosswalk gobernado. Sigue siendo screening, no determinación de obligación o incumplimiento.</div>${sourceContext(['RADAR_SII','RADAR_UAF'])}`}
async function openSectorGap(sectorId,regionName=null){const s=idx.sectorById.get(Number(sectorId));if(!s)return;state={mode:'gap',sector:s.sector_uaf,region:regionName||null,entity:null,findingType:null};$('#sector').value=s.sector_uaf;$('#region').value=regionName||'';$('#canvas').innerHTML=answer(`Brecha potencial · ${s.sector_uaf}`,'Leyendo detalle individual de fiscalización del snapshot…',null)+`<div class="loadingmini">Cargando sociedades candidatas…</div>`;try{const d=await ensureFiscalSector(sectorId);let recs=(d.records||[]).map(decodeSectorRec);if(regionName)recs=recs.filter(x=>x.region===regionName);gapState={records:recs,meta:{scope:'sector',sector_id:Number(sectorId),sector_uaf:s.sector_uaf,region:regionName||null},query:'',commune:'',sectorId:'',page:1,pageSize:100};renderGapView()}catch(e){showError('#canvas',e.message)}}
function openSectorRegionGap(sectorId,regionName){return openSectorGap(sectorId,regionName)}
async function openRegionGap(regionName){state={mode:'gap',sector:null,region:regionName,entity:null,findingType:null};$('#sector').value='';$('#region').value=regionName;$('#canvas').innerHTML=answer(`Brecha potencial · ${regionName}`,'Leyendo detalle individual de fiscalización del snapshot…',null)+`<div class="loadingmini">Cargando registros sector–sociedad…</div>`;try{const d=await ensureFiscalRegion(regionName),recs=(d.records||[]).map(r=>decodeRegionRec(r,regionName));gapState={records:recs,meta:{scope:'region',region:regionName},query:'',commune:'',sectorId:'',page:1,pageSize:100};renderGapView()}catch(e){showError('#canvas',e.message)}}
function refreshGapTable(){const el=$('#gapTable');if(el)el.innerHTML=gapTable()}
function gapSearch(v){gapState.query=v;gapState.page=1;refreshGapTable()}
function gapCommune(v){gapState.commune=v;gapState.page=1;refreshGapTable()}
function gapSector(v){gapState.sectorId=v;gapState.page=1;refreshGapTable()}
function gapPage(delta){gapState.page+=delta;refreshGapTable()}
function openCandidate(entityId,rut){const x=gapState.records.find(r=>r.entity_id===entityId&&r.rut===rut)||gapState.records.find(r=>r.entity_id===entityId);if(!x)return;const acts=(x.codigos||[]).map(c=>`<div class="activityItem"><b>${esc(c)}</b><p>${esc(window.WB_ACTECO?.[c]||'Glosa no disponible')}</p></div>`).join('')||'<div class="missing">Sin actividades SII en el registro.</div>';const sec=idx.sectorById.get(Number(x.sector_id||gapState.meta?.sector_id));$('#context').innerHTML=`<div class="contextBlock"><div class="candidateTitle">${esc(x.nombre||'—')}</div><div class="candidateRut">${esc(x.rut||'—')}</div><p><b>Sector de screening:</b> ${esc(sec?.sector_uaf||gapState.meta?.sector_uaf||'—')}</p><p><b>Territorio:</b> ${esc(x.region||'—')} · ${esc(x.comuna||'—')}</p></div><div class="contextBlock"><h3>Actividades SII que sustentan el screening</h3><div class="activityList">${acts}</div></div><div class="contextBlock"><h3>Estado</h3><p><span class="screeningTag">MATCH_FUERTE · no observado UAF</span></p><p>Estado SII publicado: ACTIVE_AS_PUBLISHED.</p></div><div class="actionrow"><button class="actionbtn" onclick="WB.caseCandidate('${esc(x.rut)}')">★ Guardar en Casos</button>${x.in_fusion?`<button class="smallbtn primary" onclick="WB.openEntity('${esc(x.entity_id)}')">Abrir Entity 360 →</button>`:`<div class="note">Esta sociedad todavía no está materializada como Entity 360 canónica en el snapshot Fusion. Se mantiene únicamente dentro del perímetro de screening.</div>`}</div><div class="screeningGuard">La ausencia en el corte UAF usado por el radar no equivale a una certificación de “no inscrito”. Requiere verificación supervisiva.</div>`}
function exportGapCSV(){const a=gapFiltered();if(!a.length)return;const head=['RUT','Razon social','Sector UAF','Region','Comuna','Codigos actividad SII','Glosas actividad SII','Observacion UAF','Nivel screening','Entity 360'];const rows=a.map(x=>[x.rut,x.nombre,idx.sectorById.get(Number(x.sector_id||gapState.meta?.sector_id))?.sector_uaf||gapState.meta?.sector_uaf||'',x.region,x.comuna,(x.codigos||[]).join(' | '),(x.codigos||[]).map(c=>window.WB_ACTECO?.[c]||'').join(' | '),'NO OBSERVADO EN CORTE PUBLICO UAF','MATCH_FUERTE',x.in_fusion?'SI':'NO']);const q=v=>'"'+String(v??'').replaceAll('"','""')+'"',csv=[head,...rows].map(r=>r.map(q).join(';')).join('\r\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`brecha_screening_${(gapState.meta?.sector_uaf||gapState.meta?.region||'fusion').replace(/[^a-z0-9]+/gi,'_')}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),500)}


function setAppActive(name){document.querySelectorAll('#appsbar .appbtn').forEach(b=>b.classList.toggle('on',b.dataset.app===name));updateCaseCount()}
function getCases(){try{return JSON.parse(localStorage.getItem(CASE_KEY)||'[]')}catch(e){return[]}}
function saveCases(a){localStorage.setItem(CASE_KEY,JSON.stringify(a));updateCaseCount()}
function updateCaseCount(){const e=$('#caseCount');if(e)e.textContent=getCases().length}
function addCase(kind,id,title,subtitle='',payload={}){let a=getCases();if(a.some(x=>x.kind===kind&&x.id===id)){status('Ya está en Casos');return}a.unshift({kind,id,title,subtitle,payload,status:'REVISAR',note:'',added_at:new Date().toISOString()});saveCases(a);status('Guardado en Casos')}
function caseEntity(id){const e=cache.entity.get(id);if(e)addCase('ENTITY',id,e.nombre||e.rut,`${e.rut||''} · ${e.ubicacion?.region||'sin región'}`,{rut:e.rut,region:e.ubicacion?.region,sources:e.fuentes})}
function caseCandidate(rut){const x=gapState.records.find(r=>r.rut===rut);if(x)addCase('SCREENING',rut,x.nombre||rut,`${x.rut} · ${x.region||''} · ${x.comuna||''}`,{sector_id:x.sector_id||gapState.meta?.sector_id,codes:x.codigos})}
function removeCase(i){let a=getCases();a.splice(i,1);saveCases(a);renderCases()}
function caseNote(i,v){let a=getCases();if(a[i]){a[i].note=v;saveCases(a)}}
function caseStatus(i,v){let a=getCases();if(a[i]){a[i].status=v;saveCases(a)}}
function clearCases(){if(confirm('¿Vaciar la bandeja de casos local?')){saveCases([]);renderCases()}}
function exportCases(){const a=getCases(),blob=new Blob([JSON.stringify({snapshot:D.manifest,cases:a,exported_at:new Date().toISOString()},null,2)],{type:'application/json'}),l=document.createElement('a');l.href=URL.createObjectURL(blob);l.download='aml_workbench_casos.json';l.click();setTimeout(()=>URL.revokeObjectURL(l.href),500)}
async function openCase(i){const c=getCases()[i];if(!c)return;if(c.kind==='ENTITY')return openEntity(c.id);if(c.kind==='SCREENING'){if(c.payload?.sector_id){await openSectorGap(c.payload.sector_id);gapState.query=c.id;gapState.page=1;renderGapView();const x=gapState.records.find(r=>r.rut===c.id);if(x)openCandidate(x.entity_id,x.rut);return}status('El caso de screening no conserva sector suficiente para reabrirlo');return}if(c.kind==='FINDING')return openFinding(c.id,c.payload.type);if(c.kind==='SANCTION'){setAppActive('sanctions');await renderSanctionsApp();return openSanction(c.id)}if(c.kind==='CGR'){setAppActive('cgr');await renderCGRApp();return openCGR(c.id)}showCases()}
function mark(t,k='info',tip=''){return `<span class="mark ${k}" ${tip?`title="${esc(tip)}"`:''}>${esc(t)}</span>`}
function entityMarks(e){let a=[];if(e.contexto?.sujeto_obligado)a.push(['UAF observado','good']);if((e.roles||[]).includes('SANCTIONED_ENTITY'))a.push(['Sancionada','alert']);if((e.senales||[]).length)a.push(['Señal AML gobernada','alert']);if((e.fuentes||[]).length>=2)a.push([`${e.fuentes.length} fuentes`,'info']);if((e.relaciones||[]).length)a.push(['Con red observada','context']);if((e.contexto?.sii_flags||[]).length)a.push([`${e.contexto.sii_flags.length} marcas SII`,'warn']);if((e.identity_confidence||0)>=.99)a.push(['Identidad exacta','good']);if(e.ubicacion?.comuna)a.push(['Territorio resuelto','info']);if((e.evidence_ids||[]).length)a.push([`${e.evidence_ids.length} evidencias`,'info']);if(e.red?.direct_signal_neighbor_count)a.push(['Vecino de señal · contexto','context']);return a}
function entityReadiness(e){const dims=[(e.identity_confidence||0)>=.9,(e.fuentes||[]).length>0,!!e.ubicacion?.comuna,(e.evidence_ids||[]).length>0,e.event_count>0,(e.relaciones||[]).length>0,(e.roles||[]).length>0];return Math.round(dims.filter(Boolean).length/dims.length*100)}
function donut(v){return `<div class="readiness"><div class="donut" style="--p:${v}%"><span>${v}</span></div><div><b>${v}%</b><div style="font-size:7px;color:#7c8798">cobertura de ficha<br>no es score de riesgo</div></div></div>`}
function entityBriefHTML(e){const marks=entityMarks(e).map(x=>x[0]);let next=[];if((e.relaciones||[]).length)next.push('Explorar contrapartes observadas');if(e.event_count)next.push('Revisar cronología y evidencia');if((e.contexto?.sii_flags||[]).length)next.push('Contrastar marcas SII con otra fuente');if((e.senales||[]).length)next.push('Revisar señal gobernada y fuente primaria');if(!next.length)next.push('Mantener como contexto; no hay disparador adicional materializado');return `<div class="brief"><b>Síntesis determinística</b><br>${esc(e.nombre||e.rut)} aparece en ${(e.fuentes||[]).length} fuente(s), con ${e.event_count||0} evento(s), ${(e.relaciones||[]).length} relación(es) y ${(e.evidence_ids||[]).length} evidencia(s). Marcas disponibles: ${esc(marks.join(', ')||'sin marcas adicionales')}.<br><br><b>Siguientes pasos:</b> ${esc(next.join(' · '))}.</div>`}
function exportEntity(id){const e=cache.entity.get(id);if(!e)return;const blob=new Blob([JSON.stringify({snapshot:D.manifest,entity:e,marks:entityMarks(e).map(x=>x[0]),exported_at:new Date().toISOString()},null,2)],{type:'application/json'}),l=document.createElement('a');l.href=URL.createObjectURL(blob);l.download=`entity360_${(e.rut||id).replace(/[^0-9A-Za-z-]/g,'_')}.json`;l.click();setTimeout(()=>URL.revokeObjectURL(l.href),500)}
function showEntityBrief(id){const e=cache.entity.get(id);if(!e)return;$('#context').innerHTML=`<div class="contextBlock"><h3>Ficha analítica rápida</h3>${entityBriefHTML(e)}</div><div class="actionrow"><button class="actionbtn primary" onclick="WB.caseEntity('${id}')">★ Guardar en Casos</button><button class="actionbtn" onclick="WB.exportEntity('${id}')">Exportar JSON</button></div>${sourceContext(e.fuentes||[])}`}
function appCards(){const w=D.workbench_summary.kpis,g=D.graph_summary;return `<div class="appgrid">
<div class="appcard" onclick="WB.showApp('reportability')"><span class="stat">21.828</span><span class="icon">↗</span><b>Reportabilidad UAF</b><p>Intensidad ROS, ROE, silencios sectoriales, calendario y desagregación territorial.</p></div>
<div class="appcard" onclick="WB.showApp('fiscal')"><span class="stat">${fmt(w.candidatos_no_observados_uaf_match_fuerte_unicos)}</span><span class="icon">◎</span><b>Fiscalización UAF</b><p>Perímetro, brecha, sociedades individualizadas y filtros territoriales.</p></div>
<div class="appcard" onclick="WB.showApp('sanctions')"><span class="stat">${fmt(A.sanction_summary?.total||974)}</span><span class="icon">⚖</span><b>Sanciones 360</b><p>Resoluciones, identidad, recurrencia, supervisor y acceso a evidencia.</p></div>
<div class="appcard" onclick="WB.showApp('anomalies')"><span class="stat">${fmt(w.anomalias_contextuales)}</span><span class="icon">⌁</span><b>Anomalías contextuales</b><p>Marcas SII descriptivas, territorio y Entity 360. No son señales AML.</p></div>
<div class="appcard" onclick="WB.showApp('network')"><span class="stat">${fmt(g.connected_entities)}</span><span class="icon">◉</span><b>Redes y rutas</b><p>Hubs, componentes, articulación y caminos contextuales hacia señales.</p></div>
<div class="appcard" onclick="WB.showApp('territory')"><span class="stat">${fmt(D.geo_summary.communes_with_mapped_entities)}</span><span class="icon">⌖</span><b>Inteligencia territorial</b><p>Regiones, comunas, convergencia, sujetos observados y grafo.</p></div>
<div class="appcard" onclick="WB.showApp('compare')"><span class="stat">⇄</span><span class="icon">▤</span><b>Laboratorio comparativo</b><p>Dos sectores o territorios lado a lado usando métricas reales.</p></div></div>`}
function showApp(name){setAppActive(name);if(name==='home'){state={mode:'discovery',sector:null,region:null,entity:null,findingType:null};return renderDiscovery()}if(name==='fiscal')return renderFiscalApp();if(name==='sanctions')return renderSanctionsApp();if(name==='anomalies')return renderAnomalyApp();if(name==='signals')return renderFindingList('GOVERNED_AML_SIGNAL');if(name==='convergence')return renderConvergenceApp();if(name==='network')return renderNetworkApp();if(name==='territory')return renderTerritoryApp();if(name==='cgr')return renderCGRApp();if(name==='compare')return renderCompare();if(name==='cases')return renderCases()}
function renderFiscalApp(){state={mode:'app-fiscal',sector:null,region:null,entity:null,findingType:null};const W=D.workbench_summary,ss=[...D.sectors].sort((a,b)=>b.potenciales_no_observados_uaf_match_fuerte-a.potenciales_no_observados_uaf_match_fuerte),rr=[...D.regions].filter(x=>x.region!=='Sin información').sort((a,b)=>b.potenciales_no_observados_uaf_match_fuerte-a.potenciales_no_observados_uaf_match_fuerte);$('#canvas').innerHTML=answer('Fiscalización UAF · screening operativo','Explora desde el agregado hasta cada sociedad candidata. Se preserva la diferencia entre actividad SII, observación UAF y condición jurídica.',null,[`${fmt(W.kpis.candidatos_no_observados_uaf_match_fuerte)} pares sector–RUT`,`${fmt(W.kpis.candidatos_no_observados_uaf_match_fuerte_unicos)} RUT únicos`,'55 sectores'])+`<div class="kpis">${kpi('RUT únicos',fmt(W.kpis.candidatos_no_observados_uaf_match_fuerte_unicos),'screening')}${kpi('Pares sector–RUT',fmt(W.kpis.candidatos_no_observados_uaf_match_fuerte),'puede haber duplicación sectorial')}${kpi('UAF observados',fmt(W.kpis.inscritos_uaf_observados),'corte público')}${kpi('Alertas supervisor',fmt(W.kpis.alertas_fiscalizacion),'sanciones / contexto')}</div><div class="grid two">${panel('Sectores con mayor brecha','Pincha la brecha para individualizar.',sectorTable(ss.slice(0,25)))}${panel('Regiones con mayor brecha','Pincha la brecha para individualizar.',regionTable(rr))}</div>`;$('#context').innerHTML=`<div class="contextBlock"><h3>Regla supervisiva</h3><p>“No observado UAF” significa ausencia en el corte público empleado, no certificación de falta de inscripción.</p></div>${sourceContext(['RADAR_SII','RADAR_UAF','RADAR_SANCIONES'])}`}
function sanctionDecoded(r){return {id:r[0],date:r[1],supervisor:r[2],subject:r[3],resolution:r[4],category:r[5],identity:r[6],laft:r[7],entity:r[8],summary:r[9],evidence:r[10],amount:r[11],status:r[12]}}
async function renderSanctionsApp(){state={mode:'app-sanctions',sector:null,region:null,entity:null,findingType:null};$('#canvas').innerHTML=answer('Sanciones 360','Cargando los 974 eventos sancionatorios reales del snapshot…',null)+`<div class="loadingmini">Cargando archivo liviano de sanciones…</div>`;try{await ensureSanctions();drawSanctions()}catch(e){showError('#canvas',e.message)}}
function sanctionFiltered(){let a=cache.sanctions.map(sanctionDecoded),q=norm(sanState.query);return a.filter(x=>(!q||norm(`${x.subject} ${x.resolution} ${x.summary}`).includes(q))&&(!sanState.year||x.date.startsWith(sanState.year))&&(!sanState.supervisor||x.supervisor===sanState.supervisor)&&(!sanState.identity||(sanState.identity==='RESOLVED'?!!x.entity:!x.entity))&&(!sanState.laft||x.laft))}
function sanctionControls(){const years=(A.sanction_summary?.by_year||[]).map(x=>x[0]).sort().reverse(),sups=(A.sanction_summary?.by_supervisor||[]).map(x=>x[0]);return `<div class="controlbar"><input placeholder="Buscar entidad, resolución o resumen…" value="${esc(sanState.query)}" oninput="WB.sanFilter('query',this.value)"><select onchange="WB.sanFilter('year',this.value)"><option value="">Todos los años</option>${years.map(y=>`<option ${sanState.year===y?'selected':''}>${y}</option>`).join('')}</select><select onchange="WB.sanFilter('supervisor',this.value)"><option value="">Todos los supervisores</option>${sups.map(s=>`<option ${sanState.supervisor===s?'selected':''}>${esc(s)}</option>`).join('')}</select><select onchange="WB.sanFilter('identity',this.value)"><option value="">Toda identidad</option><option value="RESOLVED" ${sanState.identity==='RESOLVED'?'selected':''}>Identidad resuelta</option><option value="UNRESOLVED" ${sanState.identity==='UNRESOLVED'?'selected':''}>No resuelta</option></select><label style="font-size:7px"><input type="checkbox" ${sanState.laft?'checked':''} onchange="WB.sanFilter('laft',this.checked?'1':'')"> LAFT directa</label></div>`}
function drawSanctions(){let a=sanctionFiltered(),pages=Math.max(1,Math.ceil(a.length/sanState.pageSize));sanState.page=Math.min(Math.max(1,sanState.page),pages);let rows=a.slice((sanState.page-1)*sanState.pageSize,sanState.page*sanState.pageSize),S=A.sanction_summary||{};$('#canvas').innerHTML=answer('Sanciones 360','Explorador de eventos administrativos con resolución de identidad separada de los candidatos no resueltos. Sanción administrativa ≠ LA/FT.',null,[`${fmt(a.length)} filtradas`,`${fmt(S.resolved||0)} resueltas`,`${fmt(S.unresolved||0)} no resueltas`,`${fmt(S.laft_direct||0)} LAFT directa`])+`<div class="kpis">${kpi('Eventos',fmt(S.total),'Radar Sanciones')}${kpi('Identidad resuelta',fmt(S.resolved),'RUT / entidad canónica')}${kpi('No resuelta',fmt(S.unresolved),'se mantiene como candidato','amber')}${kpi('LAFT directa',fmt(S.laft_direct),'clasificación upstream')}</div>${panel('Resoluciones y sujetos','Filtros operativos sobre los 974 eventos.',`${sanctionControls()}<div id="sanTable">${sanctionTable(rows,a.length,pages)}</div>`)}`;$('#context').innerHTML=`<div class="contextBlock"><h3>Supervisores</h3>${(S.by_supervisor||[]).map(x=>`<div class="evidence"><b>${esc(x[0])}</b><p>${fmt(x[1])} evento(s)</p></div>`).join('')}</div>${sourceContext(['RADAR_SANCIONES'])}`}
function sanctionTable(rows,total,pages){return `<div class="tablewrap" style="max-height:530px"><table><thead><tr><th>Fecha</th><th>Sujeto / resolución</th><th>Supervisor</th><th>Identidad</th><th>Marca</th></tr></thead><tbody>${rows.map(x=>`<tr class="click" onclick="WB.openSanction('${x.id}')"><td>${esc(x.date||'—')}</td><td><b>${esc(x.subject||'—')}</b><br><span style="color:#8994a4">${esc(x.resolution||'')}</span></td><td>${esc(x.supervisor)}</td><td>${x.entity?'<span class="resolvedTag">Resuelta</span>':'<span class="unresolvedTag">No resuelta</span>'}</td><td>${x.laft?'<span class="sanctionTag">LAFT directa</span>':'<span class="mini">Administrativa</span>'}</td></tr>`).join('')}</tbody></table></div><div class="pager"><span>${fmt(total)} registros · página ${sanState.page}/${pages}</span><button onclick="WB.sanPage(-1)" ${sanState.page<=1?'disabled':''}>←</button><button onclick="WB.sanPage(1)" ${sanState.page>=pages?'disabled':''}>→</button></div>`}
function sanFilter(k,v){sanState[k]=v;sanState.page=1;drawSanctions()}
function sanPage(d){sanState.page+=d;drawSanctions()}
async function openSanction(id){const x=cache.sanctions.map(sanctionDecoded).find(x=>x.id===id);if(!x)return;$('#context').innerHTML=`<div class="contextBlock"><h3>Evento sancionatorio</h3><p><b>${esc(x.subject)}</b><br>${esc(x.date)} · ${esc(x.supervisor)} · Resolución ${esc(x.resolution||'—')}</p></div><div class="evidence"><b>${esc(x.category||'Sin categoría')}</b><p>${esc(x.summary||'Sin resumen')}</p></div><div class="markbar">${x.entity?mark('Identidad resuelta','good'):mark('Identidad no resuelta','warn')}${x.laft?mark('LAFT directa upstream','alert'):mark('Sanción administrativa','info')}</div><div class="actionrow">${x.entity?`<button class="actionbtn primary" onclick="WB.openEntity('${x.entity}')">Abrir Entity 360</button>`:''}<button class="actionbtn" onclick="WB.addCase('SANCTION','${esc(x.id)}','${esc(x.subject).replaceAll("'","\\'")}','${esc(x.date)} · ${esc(x.supervisor)}',{resolution:'${esc(x.resolution).replaceAll("'","\\'")}'})">★ Guardar</button>${x.evidence?`<button class="actionbtn" onclick="WB.openEvidence('${esc(x.evidence)}')">Abrir evidencia</button>`:''}</div><div class="warnbox">La sanción no acredita por sí sola LA/FT. Si la identidad no está resuelta, no se promueve como entidad canónica.</div>`}
async function openEvidence(id){try{await ensureEvidence();const x=cache.evidence.get(id);if(!x){$('#context').insertAdjacentHTML('beforeend','<div class="missing">Evidencia sin URL directa en el índice liviano.</div>');return}$('#context').insertAdjacentHTML('beforeend',`<div class="evidence"><b>${esc(PROD_LABEL[x.producer_id]||x.producer_id)} · ${esc(x.quality_status||'')}</b><p>${esc(x.excerpt||x.source_id||'')}</p>${x.source_url?`<a href="${esc(x.source_url)}" target="_blank" rel="noopener">Abrir fuente ↗</a>`:''}</div>`)}catch(e){showError('#context',e.message)}}
async function openFindingEvidence(id,type){try{const a=await ensureFindingType(type),f=a.find(x=>x.finding_id===id);if(!f)return;await ensureEvidence();const ev=(f.evidence_ids||[]).map(x=>cache.evidence.get(x)).filter(Boolean);$('#context').insertAdjacentHTML('beforeend',`<div class="contextBlock"><h3>Evidencia del finding</h3>${ev.length?ev.map(x=>`<div class="evidence"><b>${esc(PROD_LABEL[x.producer_id]||x.producer_id)} · ${esc(x.quality_status||'')}</b><p>${esc(x.excerpt||x.source_id||'')}</p>${x.source_url?`<a href="${esc(x.source_url)}" target="_blank" rel="noopener">Abrir fuente ↗</a>`:''}</div>`).join(''):`<div class="missing">${fmt((f.evidence_ids||[]).length)} referencia(s); ninguna con URL directa en el índice liviano.</div>`}</div>`)}catch(e){showError('#context',e.message)}}

async function renderAnomalyApp(){state={mode:'app-anomalies',sector:null,region:null,entity:null,findingType:null};$('#canvas').innerHTML=answer('Anomalías contextuales SII','Cargando marcas descriptivas reales. No constituyen señales AML.',null)+`<div class="loadingmini">Cargando 12.752 anomalías…</div>`;try{await ensureAnomalies();drawAnomalies()}catch(e){showError('#canvas',e.message)}}
function anomalyFiltered(){let q=norm(anomState.query);return cache.anomalies.filter(x=>(!q||norm(`${x.rut} ${x.nombre} ${x.titulo} ${x.region} ${x.comuna}`).includes(q))&&(!anomState.code||x.codigo_tecnico===anomState.code)&&(!anomState.region||x.region===anomState.region))}
function drawAnomalies(){let a=anomalyFiltered(),pages=Math.max(1,Math.ceil(a.length/anomState.pageSize));anomState.page=Math.min(Math.max(1,anomState.page),pages);let rows=a.slice((anomState.page-1)*anomState.pageSize,anomState.page*anomState.pageSize);$('#canvas').innerHTML=answer('Anomalías contextuales SII','Explora cambios y marcas empresariales como contexto. Deben corroborarse con otras fuentes antes de elevar una hipótesis.',null,[`${fmt(a.length)} filtradas`,'Contexto ≠ señal AML'])+`<div class="kpis">${kpi('Anomalías',fmt(D.workbench_summary.kpis.anomalias_contextuales),'universo')}${kpi('Tipos',fmt(A.anomaly_types?.length||0),'códigos técnicos')}${kpi('Top marca',esc(A.anomaly_types?.[0]?.[1]||'—'),fmt(A.anomaly_types?.[0]?.[2]||0)+' casos')}${kpi('Fuente','SII','descriptiva')}</div>${panel('Entidades y marcas','Pincha para abrir Entity 360.',`<div class="controlbar"><input placeholder="RUT, entidad, marca o territorio…" value="${esc(anomState.query)}" oninput="WB.anomFilter('query',this.value)"><select onchange="WB.anomFilter('code',this.value)"><option value="">Todas las marcas</option>${(A.anomaly_types||[]).map(x=>`<option value="${esc(x[0])}" ${anomState.code===x[0]?'selected':''}>${esc(x[1])} · ${fmt(x[2])}</option>`).join('')}</select><select onchange="WB.anomFilter('region',this.value)"><option value="">Todas las regiones</option>${D.regions.filter(x=>x.region!=='Sin información').map(x=>`<option ${anomState.region===x.region?'selected':''}>${esc(x.region)}</option>`).join('')}</select></div><div class="tablewrap" style="max-height:520px"><table><thead><tr><th>Entidad</th><th>Marca</th><th>Territorio</th><th>Nivel</th></tr></thead><tbody>${rows.map(x=>`<tr class="click" onclick="WB.openEntity('${x.entity_id}')"><td><b>${esc(x.nombre||x.rut)}</b><br>${esc(x.rut||'')}</td><td>${esc(x.titulo)}</td><td>${esc(x.region||'—')} · ${esc(x.comuna||'—')}</td><td><span class="mark warn">Contextual</span></td></tr>`).join('')}</tbody></table></div><div class="pager"><span>${fmt(a.length)} registros · página ${anomState.page}/${pages}</span><button onclick="WB.anomPage(-1)" ${anomState.page<=1?'disabled':''}>←</button><button onclick="WB.anomPage(1)" ${anomState.page>=pages?'disabled':''}>→</button></div>`)}`;$('#context').innerHTML=`<div class="contextBlock"><h3>Marcas más frecuentes</h3>${(A.anomaly_types||[]).slice(0,8).map(x=>`<div class="evidence"><b>${esc(x[1])}</b><p>${fmt(x[2])} entidad-marca</p></div>`).join('')}</div>${sourceContext(['RADAR_SII'])}`}
function anomFilter(k,v){anomState[k]=v;anomState.page=1;drawAnomalies()}function anomPage(d){anomState.page+=d;drawAnomalies()}
async function renderConvergenceApp(){state={mode:'app-convergence',sector:null,region:null,entity:null,findingType:'ENTITY_CONVERGENCE'};$('#canvas').innerHTML=answer('Convergencia multifuente','Cargando findings donde productores independientes coinciden sobre una entidad o contexto analítico.',null,[`${fmt(D.workbench_summary.kpis.entidades_fusion)} entidades Fusion`,`${fmt(D.analytics.kpis.productores_distintos)} productores`])+`<div class="loadingmini">Cargando convergencias…</div>`;try{const a=await ensureFindingType('ENTITY_CONVERGENCE'),fs=a.filter(findingPass).sort((a,b)=>score(b)-score(a));const srcCombo=new Map();fs.forEach(f=>{let k=[...(f.producer_ids||[])].sort().join(' + ');srcCombo.set(k,(srcCombo.get(k)||0)+1)});$('#canvas').innerHTML=answer('Convergencia multifuente','La coincidencia entre fuentes aumenta capacidad de análisis; no prueba conducta ilícita.',fs.length?Math.max(...fs.map(score)):null,[`${fmt(fs.length)} findings`,`${fmt(D.workbench_summary.kpis.entidades_fusion)} entidades Fusion`])+`<div class="kpis">${kpi('Convergencias',fmt(fs.length),'findings')}${kpi('Entidades multi-radar',fmt(D.analytics.kpis.entidades),'universo Fusion')}${kpi('Fuentes máximas',Math.max(...fs.map(x=>x.source_independence_count||1)),'en findings')}${kpi('Guardrail','Activo','no inferencia automática','green')}</div><div class="grid two">${panel('Prioridades de convergencia','Ordenadas por IPA existente.',findingsTable(fs,120))}${panel('Combinaciones de fuentes','Independencia observable.',[...srcCombo.entries()].sort((a,b)=>b[1]-a[1]).slice(0,15).map(x=>factor(x[0].split(' + ').map(p=>PROD_LABEL[p]||p).join(' + '),x[1],fs.length,fmt(x[1]))).join(''))}</div>`;$('#context').innerHTML=sourceContext()}catch(e){showError('#canvas',e.message)}}
function renderNetworkApp(){state={mode:'app-network',sector:null,region:null,entity:null,findingType:null};const G=A.graph||{},S=D.graph_summary;$('#canvas').innerHTML=answer('Redes y rutas contextuales','Topología sobre relaciones publicadas. Centralidad, articulación o cercanía a una señal son contexto de red, no riesgo heredado.',null,[`${fmt(S.connected_entities)} conectadas`,`${fmt(S.component_count)} componentes`,`${fmt(S.relationship_records)} relaciones`,`${fmt(S.materialized_signal_paths)} rutas a señales`])+`<div class="kpis">${kpi('Entidades conectadas',fmt(S.connected_entities),'grafo')}${kpi('Componentes',fmt(S.component_count),'subredes')}${kpi('Puntos articulación',fmt(S.articulation_point_count),'topología')}${kpi('Mayor componente',fmt(S.largest_component_size),'entidades')}</div><div class="grid two">${panel('Hubs observados','Grado alto no significa riesgo.',`<div class="searchResults">${(G.top_hubs||[]).slice(0,60).map(h=>`<div class="hub" onclick="WB.openEntity('${h[0]}')"><div class="deg">${h[5]}</div><div><b>${esc(h[2]||h[1]||h[0])}</b><small>${esc(h[1])} · ${esc(h[3]||'sin región')} · componente ${esc(h[7]||'—')}${h[6]?' · articulación':''}</small></div></div>`).join('')}</div>`)}${panel('Componentes mayores','Resumen de topología observada.',`<div class="tablewrap"><table><thead><tr><th>Componente</th><th>Ent.</th><th>Rel.</th><th>Fuentes</th><th>Artic.</th><th>Señales</th></tr></thead><tbody>${(G.top_components||[]).slice(0,45).map(c=>`<tr><td><b>${esc(c[0].slice(-10))}</b></td><td>${c[1]}</td><td>${c[2]}</td><td>${c[3]}</td><td>${c[4]}</td><td>${c[5]}</td></tr>`).join('')}</tbody></table></div>`)}</div><div style="margin-top:10px">${panel('Rutas contextualizadas hacia señales','Shortest path no implica control, conocimiento o complicidad.',(G.signal_paths||[]).slice(0,35).map(p=>`<div class="path"><div class="pathline">${p[4].map((n,i)=>`${i?'<span class="arrow">→</span>':''}<span class="pathnode" onclick="WB.openEntity('${n[0]}')">${esc(n[2]||n[1]||n[0])}</span>`).join('')}</div><div style="font-size:6.5px;color:#8894a4;margin-top:4px">${p[1]} salto(s) · ${esc(p[0])}</div></div>`).join(''))}</div>`;$('#context').innerHTML=`<div class="contextBlock"><h3>Semántica de grafo</h3><p>${esc(S.topology_mode)}</p></div><div class="warnbox">No hay propagación de riesgo. No se crean aristas por nombre, co-localización ni proximidad territorial.</div>${sourceContext(['RADAR_SII'])}`}
function renderTerritoryApp(){state={mode:'app-territory',sector:null,region:null,entity:null,findingType:null};const rr=[...D.map_region_metrics].sort((a,b)=>b.mapped_entity_count-a.mapped_entity_count),cc=[...D.map_commune_metrics].sort((a,b)=>b.mapped_entity_count-a.mapped_entity_count);$('#canvas').innerHTML=answer('Inteligencia territorial','Explora densidad observada, sujetos UAF, conexiones de grafo y contexto delictual sin atribuir conducta a residentes o empresas.',null,[`${D.geo_summary.regions_in_reference} regiones`,`${D.geo_summary.communes_in_reference} comunas`,`${fmt(D.geo_summary.mapped_entities)} entidades mapeadas`])+`<div class="kpis">${kpi('Entidades mapeadas',fmt(D.geo_summary.mapped_entities),'contexto geográfico')}${kpi('Comunas con entidades',fmt(D.geo_summary.communes_with_mapped_entities),'de 345')}${kpi('Convergencia territorial',fmt(D.geo_summary.territories_with_multi_radar_convergence),'territorios')}${kpi('Delictual',String(D.geo_summary.delictual_latest_year),D.geo_summary.delictual_freshness_state,'amber')}</div><div class="grid equal">${panel('Regiones','Pincha para abrir análisis regional.',`<div class="tablewrap"><table><thead><tr><th>Región</th><th>Entidades</th><th>SO</th><th>Grafo</th><th>Eventos</th></tr></thead><tbody>${rr.map(x=>`<tr class="click" onclick="WB.openRegion('${esc(canonRegion(x.region_name)).replaceAll("'","\\'")}')"><td><b>${esc(canonRegion(x.region_name))}</b></td><td>${fmt(x.mapped_entity_count)}</td><td>${fmt(x.obliged_entity_count)}</td><td>${fmt(x.graph_connected_entity_count)}</td><td>${fmt(x.mapped_event_count)}</td></tr>`).join('')}</tbody></table></div>`)}${panel('Comunas con mayor presencia','Métrica de volumen/contexto, no ranking de riesgo.',`<div class="tablewrap"><table><thead><tr><th>Comuna</th><th>Región</th><th>Ent.</th><th>SO</th><th>Grafo</th></tr></thead><tbody>${cc.slice(0,80).map(x=>`<tr><td><b>${esc(x.commune_name)}</b></td><td>${esc(canonRegion(x.region_name))}</td><td>${fmt(x.mapped_entity_count)}</td><td>${fmt(x.obliged_entity_count)}</td><td>${fmt(x.graph_connected_entity_count)}</td></tr>`).join('')}</tbody></table></div>`)}</div>`;$('#context').innerHTML=`<div class="contextBlock"><h3>Guardrail geográfico</h3><p>Concentración territorial, contexto delictual o proximidad no implican causalidad ni crean una relación entre entidades.</p></div>${sourceContext(['RADAR_SII','RADAR_UAF','RADAR_DELICTUAL'])}`}
async function renderCGRApp(){state={mode:'app-cgr',sector:null,region:null,entity:null,findingType:null};$('#canvas').innerHTML=answer('CGR · contexto administrativo','Cargando 90 eventos reales de Contraloría materializados en Fusion.',null)+`<div class="loadingmini">Cargando archivo CGR…</div>`;try{await ensureCGR();drawCGR()}catch(e){showError('#canvas',e.message)}}
function cgrDecoded(r){return{id:r[0],type:r[1],date:r[2],title:r[3],region:r[4],unresolved:r[5],evidence:r[6],document:r[7],status:r[8]}}
function drawCGR(){const a=cache.cgr.map(cgrDecoded).sort((a,b)=>String(b.date).localeCompare(String(a.date))),S=A.cgr_summary||{};$('#canvas').innerHTML=answer('CGR · contexto administrativo','Auditorías y noticias oficiales. Los nombres no resueltos se conservan como texto y no se promueven automáticamente a Entity Hub.',null,[`${fmt(S.total||a.length)} eventos`,`${fmt(S.audits||0)} auditorías`,`${fmt(S.news||0)} noticias`])+`<div class="kpis">${kpi('Eventos CGR',fmt(a.length),'Fusion')}${kpi('Auditorías',fmt(S.audits||0),'AUDIT_REPORT')}${kpi('Noticias',fmt(S.news||0),'CGR_NEWS')}${kpi('Identidad','Parcial','no se fuerzan matches','amber')}</div>${panel('Eventos','Pincha para revisar contexto y evidencia.',`<div class="tablewrap" style="max-height:550px"><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Título</th><th>Región</th><th>Entidad textual</th></tr></thead><tbody>${a.map(x=>`<tr class="click" onclick="WB.openCGR('${x.id}')"><td>${esc(x.date||'—')}</td><td>${x.type==='AUDIT_REPORT'?'<span class="mark info">Auditoría</span>':'<span class="mini">Noticia</span>'}</td><td><b>${esc(x.title)}</b></td><td>${esc(x.region||'—')}</td><td>${esc(x.unresolved||'—')}</td></tr>`).join('')}</tbody></table></div>`)}`;$('#context').innerHTML=sourceContext(['RADAR_CGR'])}
function openCGR(id){const x=cache.cgr.map(cgrDecoded).find(x=>x.id===id);if(!x)return;$('#context').innerHTML=`<div class="contextBlock"><h3>${x.type==='AUDIT_REPORT'?'Informe de auditoría':'Publicación CGR'}</h3><p><b>${esc(x.title)}</b><br>${esc(x.date||'—')} · ${esc(x.region||'sin región')}</p></div>${x.unresolved?`<div class="evidence"><b>Entidad mencionada — no resuelta</b><p>${esc(x.unresolved)}</p></div>`:''}<div class="actionrow"><button class="actionbtn" onclick="WB.addCase('CGR','${esc(x.id)}','${esc(x.title).replaceAll("'","\\'")}','${esc(x.date)}',{document:'${esc(x.document)}'})">★ Guardar</button>${(x.evidence||[]).length?`<button class="actionbtn" onclick="WB.openEvidence('${esc(x.evidence[0])}')">Abrir evidencia</button>`:''}</div><div class="warnbox">Nombre mencionado en CGR ≠ identidad canónica. Sólo se vincula a una entidad cuando la resolución de identidad cumple las reglas de Fusion.</div>`}
function compareMetric(label,a,b,fmtFn=v=>fmt(v)){return `<div class="metricRow"><span>${esc(label)}</span><b>${fmtFn(a)}</b></div>`}
function renderCompare(){state={mode:'app-compare',sector:null,region:null,entity:null,findingType:null};const s1=D.sectors[0],s2=D.sectors[1];$('#canvas').innerHTML=answer('Laboratorio comparativo','Compara dos sectores o dos regiones usando sólo métricas ya materializadas; no crea benchmarks sintéticos.',null,['Sector ↔ sector','Región ↔ región'])+`<div class="tabs"><button class="on" onclick="WB.compareMode('sector',this)">Sectores</button><button onclick="WB.compareMode('region',this)">Regiones</button></div><div id="compareBody">${compareBody('sector',s1.sector_uaf,s2.sector_uaf)}</div>`;$('#context').innerHTML=`<div class="contextBlock"><h3>Uso recomendado</h3><p>La comparación muestra diferencias descriptivas. No asigna una conclusión de riesgo al objeto con mayor valor.</p></div>${sourceContext()}`}
function compareMode(mode,btn){document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('on',x===btn));const a=mode==='sector'?D.sectors[0].sector_uaf:D.regions.find(x=>x.region!=='Sin información').region,b=mode==='sector'?D.sectors[1].sector_uaf:D.regions.filter(x=>x.region!=='Sin información')[1].region;$('#compareBody').innerHTML=compareBody(mode,a,b)}
function compareBody(mode,aName,bName){const list=mode==='sector'?D.sectors:D.regions.filter(x=>x.region!=='Sin información'),key=mode==='sector'?'sector_uaf':'region';return `<div class="controlbar"><select class="compareSelect" id="cmpA" onchange="WB.compareRefresh('${mode}')">${list.map(x=>`<option ${x[key]===aName?'selected':''}>${esc(x[key])}</option>`).join('')}</select><span>vs</span><select class="compareSelect" id="cmpB" onchange="WB.compareRefresh('${mode}')">${list.map(x=>`<option ${x[key]===bName?'selected':''}>${esc(x[key])}</option>`).join('')}</select></div><div id="compareCols">${compareCols(mode,aName,bName)}</div>`}
function compareRefresh(mode){$('#compareCols').innerHTML=compareCols(mode,$('#cmpA').value,$('#cmpB').value)}
function compareCols(mode,aName,bName){let a,b,rows;if(mode==='sector'){a=idx.sectorByName.get(norm(aName));b=idx.sectorByName.get(norm(bName));rows=x=>[['UAF observados',x.inscritos_uaf_observados],['SII match fuerte',x.universo_sii_match_fuerte],['Brecha potencial',x.potenciales_no_observados_uaf_match_fuerte],['ICP',x.icp_cobertura_potencial_pct,'pct'],['Sanciones',x.sanciones_observadas],['Anomalías',x.anomalias_contextuales]]}else{a=idx.regionByName.get(aName);b=idx.regionByName.get(bName);rows=x=>[['Entidades Fusion',x.entidades_fusion],['UAF observados',x.inscritos_uaf_observados],['SII match fuerte',x.sii_match_fuerte],['Brecha potencial',x.potenciales_no_observados_uaf_match_fuerte],['Sanciones',x.sanciones_observadas],['Anomalías',x.anomalias_contextuales],['Señales AML',x.senales_aml_directas]]}const col=x=>`<div class="compareCol"><h3>${esc(mode==='sector'?x.sector_uaf:x.region)}</h3>${rows(x).map(r=>`<div class="metricRow"><span>${esc(r[0])}</span><b>${r[1]==null?'—':r[2]==='pct'?Number(r[1]).toFixed(2)+'%':fmt(r[1])}</b></div>`).join('')}</div>`;return `<div class="compare">${col(a)}<div class="compareVs">VS</div>${col(b)}</div>`}
function renderCases(){state={mode:'app-cases',sector:null,region:null,entity:null,findingType:null};const a=getCases();$('#canvas').innerHTML=answer('Bandeja de casos analíticos','Colección local para reunir entidades, sociedades de screening, sanciones, CGR y findings durante la sesión. No modifica Fusion.',null,[`${a.length} elemento(s)`,'Persistencia local del navegador'])+`<div class="actionrow"><button class="actionbtn primary" onclick="WB.exportCases()">Exportar casos JSON</button><button class="actionbtn" onclick="WB.clearCases()">Vaciar bandeja</button></div><div style="margin-top:10px">${a.map((c,i)=>`<div class="caseCard"><div class="caseMeta"><span class="caseBadge">${esc(c.kind)}</span><b>${esc(c.title)}</b><span class="grow"></span><select onchange="WB.caseStatus(${i},this.value)" style="font-size:7px;border:1px solid #dfe5ed;border-radius:5px"><option ${c.status==='REVISAR'?'selected':''}>REVISAR</option><option ${c.status==='EN ANALISIS'?'selected':''}>EN ANALISIS</option><option ${c.status==='CERRADO'?'selected':''}>CERRADO</option></select></div><p>${esc(c.subtitle||'')}</p><textarea placeholder="Nota del analista…" oninput="WB.caseNote(${i},this.value)">${esc(c.note||'')}</textarea><div class="actionrow"><button class="actionbtn" onclick="WB.openCase(${i})">Abrir</button><button class="actionbtn" onclick="WB.removeCase(${i})">Quitar</button></div></div>`).join('')||'<div class="missing">La bandeja está vacía. Usa ★ Guardar desde una ficha o evento.</div>'}</div>`;$('#context').innerHTML=`<div class="contextBlock"><h3>Alcance</h3><p>La bandeja es una herramienta de trabajo local; no representa un expediente formal ni altera los datos canónicos.</p></div>${sourceContext()}`}
function showCases(){setAppActive('cases');renderCases()}

function renderPendingSpend(){const cgr=D.analytics.cobertura_radares.find(x=>x.codigo==='RADAR_CGR');state={mode:'spend',sector:null,region:null,entity:null,findingType:null};$('#canvas').innerHTML=answer('Gasto público / proveedor: integración pendiente','Presupuesto Abierto aún no tiene eventos canónicos en este snapshot. La interfaz no fabrica montos ni concentraciones.',null,['Presupuesto Abierto → Fusion'])+`<div class="kpis">${kpi('CGR eventos',fmt(cgr?.eventos||0),'contexto disponible')}${kpi('Presupuesto eventos','0','snapshot v0.6.2')}${kpi('Materialidad','No disponible','sin importes canónicos')}${kpi('Proveedor–organismo','No disponible','adaptador pendiente')}</div>`;$('#context').innerHTML=sourceContext(['RADAR_CGR'])}
function applyFilters(){let s=$('#sector').value,r=$('#region').value;if(s){state={mode:'sector',sector:s,region:r||null,entity:null,findingType:null};renderSector()}else if(r)openRegion(r);else{state={mode:'discovery',sector:null,region:null,entity:null,findingType:null};renderDiscovery()}}
function showHealth(){const e=D.evidence_summary,g=D.graph_summary,geo=D.geo_summary,w=D.workbench_summary;setAppActive('home');$('#canvas').innerHTML=answer('Salud, cobertura y límites del sistema','Una inferencia sólo es tan confiable como la identidad, evidencia, temporalidad y cobertura que la sostienen. Esta vista separa disponibilidad de datos de prioridad AML.',null,[D.manifest.snapshot_id,`Fusion v${D.manifest.version}`,'Gobernanza visible'])+`<div class="kpis">${kpi('Evidencias',fmt(e.total),`${fmt(e.con_url)} con URL`)}${kpi('Entidades mapeadas',fmt(geo.mapped_entities),`${fmt(geo.unmapped_entities)} sin geografía`)}${kpi('Entidades conectadas',fmt(g.connected_entities),`${fmt(g.relationship_records)} relaciones`)}${kpi('Identidad sanciones',fmt(w.kpis.sanciones_resueltas),`${fmt(w.kpis.sanciones_sin_identidad_resuelta)} no resueltas`,'amber')}</div><div class="grid equal">${panel('Calidad de evidencia','Estado informado por las fuentes.',(e.por_calidad||[]).map(x=>factor(x.codigo,x.valor,e.total,fmt(x.valor))).join(''))}${panel('Cobertura por radar','Entidades y eventos materializados.',D.analytics.cobertura_radares.map(x=>`<div class="evidence"><b>${esc(x.nombre)}</b><p>${fmt(x.entidades)} entidades · ${fmt(x.eventos)} eventos</p></div>`).join(''))}</div><div class="grid equal" style="margin-top:10px">${panel('Capacidades de contexto','Disponibilidad, no riesgo.',`<div class="markbar">${mark(`${fmt(geo.communes_with_mapped_entities)} comunas mapeadas`,'good')}${mark(`${fmt(g.component_count)} componentes de red`,'context')}${mark(`${fmt(g.materialized_signal_paths)} rutas a señales`,'context')}${mark(`Delictual ${geo.delictual_latest_year} · ${geo.delictual_freshness_state}`,'warn')}${mark('Presupuesto Abierto · adaptador pendiente','warn')}</div><div class="note">Recencia y materialidad permanecen fuera de IPA 2.0 mientras no exista una capa gobernada suficiente.</div>`)}${panel('Archivos cargados en esta sesión','La arquitectura local mantiene carga progresiva.',`<div class="evidence"><b>Núcleo</b><p>Siempre cargado · ~0,8 MB</p></div><div class="evidence"><b>Índice entidades</b><p>${loaded.has('search')?'cargado':'no cargado'}</p></div><div class="evidence"><b>Sanciones</b><p>${loaded.has('sanctions')?'cargadas':'no cargadas'}</p></div><div class="evidence"><b>Anomalías</b><p>${loaded.has('anomalies')?'cargadas':'no cargadas'}</p></div><div class="evidence"><b>Evidencia URL</b><p>${loaded.has('evidence')?'cargada':'no cargada'}</p></div><div class="evidence"><b>Fiscalización detallada</b><p>${[...loaded].some(x=>String(x).startsWith('fiscal-'))?'algún detalle cargado':'no cargada'}</p></div>`)}</div>`;$('#context').innerHTML=`<div class="contextBlock"><h3>Reglas de lectura</h3><p>Cobertura ≠ riesgo. Confianza de identidad ≠ riesgo. Missing ≠ cero. Contexto territorial ≠ atribución. Relación ≠ propagación de riesgo.</p></div>${sourceContext()}`}
function exportContext(){const obj={snapshot:D.manifest,state,filters:{sector:$('#sector').value,region:$('#region').value,source:$('#source').value,min_sources:$('#minsources').value},loaded:[...loaded],generated_at:new Date().toISOString()};const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='aml_workbench_context.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}

function boot(){if(!D){showError('#canvas','No se pudo leer data/core.js');return}for(const s of D.sectors){idx.sectorById.set(s.sector_id,s);idx.sectorByName.set(norm(s.sector_uaf),s)}for(const r of D.regions)idx.regionByName.set(r.region,r);for(const s of [...D.sectors].sort((a,b)=>a.sector_uaf.localeCompare(b.sector_uaf,'es')))$('#sector').insertAdjacentHTML('beforeend',`<option value="${esc(s.sector_uaf)}">${esc(s.sector_uaf)}</option>`);for(const r of D.regions.filter(x=>x.region!=='Sin información').sort((a,b)=>a.region.localeCompare(b.region,'es')))$('#region').insertAdjacentHTML('beforeend',`<option value="${esc(r.region)}">${esc(r.region)}</option>`);$('#snap').textContent=`${D.manifest.snapshot_id} · Fusion v${D.manifest.version} · Workbench v0.10`;
updateCaseCount();$('#query').addEventListener('keydown',e=>{if(e.key==='Enter')runQuery()});$('#sector').onchange=applyFilters;$('#region').onchange=applyFilters;$('#source').onchange=()=>{if(state.mode==='finding')renderFindingList(state.findingType)};$('#minsources').onchange=()=>{if(state.mode==='finding')renderFindingList(state.findingType)};renderDiscovery()}

window.WB={openSector,openRegion,openEntity,openFinding,openSectorGap,openSectorRegionGap,openRegionGap,openCandidate,gapSearch,gapCommune,gapSector,gapPage,exportGapCSV,loadSectorBreaches:id=>loadSectorFinding('SUPERVISORY_GAP',id),loadSectorSanctions:id=>loadSectorFinding('PRUDENTIAL_SANCTION',id),loadSectorAnomalies,loadRegionMap,loadRegionFinding,loadEntityAnomalies,loadEntityEvidence,runQuery,showHealth,exportContext,showApp,renderFiscalApp,renderSanctionsApp,renderAnomalyApp,renderConvergenceApp,renderNetworkApp,renderTerritoryApp,renderCGRApp,renderCompare,renderCases,showCases,addCase,caseEntity,caseCandidate,removeCase,caseNote,caseStatus,clearCases,exportCases,openCase,exportEntity,showEntityBrief,openEvidence,openFindingEvidence,sanFilter,sanPage,openSanction,anomFilter,anomPage,openCGR,compareMode,compareRefresh}
window.addEventListener('error',ev=>{console.error(ev.error||ev.message);status('Error de detalle',false)});
boot();
})();
