(()=>{
'use strict';
const D=window.WB_CORE, A=window.WB_ADVANCED||{}, RP=window.WB_REPORTABILITY||{}, B=window.WB;
if(!D||!B)return;
const $=s=>document.querySelector(s), fmt=n=>new Intl.NumberFormat('es-CL').format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const sum=a=>a.reduce((x,y)=>x+Number(y||0),0), share=(x,t)=>t?Number(x||0)/t*100:0;
const median=a=>{const b=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!b.length)return null;return b[Math.floor(b.length/2)]};
const pct=n=>n==null?'—':`${Number(n)>0?'+':''}${Number(n).toFixed(1)}%`;

/* ---------- Non-overlapping desktop navigation ---------- */
const navModel={
 home:{label:'Inicio',apps:[['home','Panorama']]},
 supervision:{label:'Supervisión',apps:[['fiscal','Fiscalización'],['reportability','Reportabilidad'],['sanctions','Sanciones 360']]},
 intelligence:{label:'Inteligencia',apps:[['anomalies','Anomalías'],['signals','Señales AML'],['convergence','Convergencia'],['network','Redes']]},
 context:{label:'Contexto',apps:[['territory','Territorio'],['cgr','CGR'],['compare','Comparar']]},
 cases:{label:'Casos',apps:[['cases','Bandeja de casos']]}
};
const appCat={home:'home',fiscal:'supervision',reportability:'supervision',sanctions:'supervision',anomalies:'intelligence',signals:'intelligence',convergence:'intelligence',network:'intelligence',territory:'context',cgr:'context',compare:'context',cases:'cases'};
let navCat='home',navApp='home';
function buildNav(cat=navCat,active=navApp){
 navCat=cat;navApp=active;
 const bar=$('#appsbar');if(!bar)return;
 bar.innerHTML=`<div class="desktopNav">${Object.entries(navModel).map(([k,v])=>`<button class="navCategory ${k===cat?'active':''}" onclick="WBR.selectCategory('${k}')">${v.label}</button>`).join('')}<span class="navDivider"></span><div class="desktopSubnav">${navModel[cat].apps.map(([k,l])=>`<button data-refapp="${k}" class="${k===active?'active':''}" onclick="WB.showApp('${k}')">${l}</button>`).join('')}</div><span class="desktopNavHint">sin menús superpuestos · todas las capacidades disponibles</span></div>`;
}
function selectCategory(cat){const def=navModel[cat].apps[0][0];B.showApp(def)}
function navForApp(app){const cat=appCat[app]||navCat;buildNav(cat,app)}

/* ---------- SVG macro charts ---------- */
function hbar(rows,opt={}){
 const a=rows.filter(x=>Number.isFinite(Number(x.value))).slice(0,opt.limit||10),W=620,H=Math.max(155,a.length*25+24),L=opt.left||190,R=48,T=10,Bt=18,max=Math.max(...a.map(x=>Number(x.value)),1);
 return `<svg class="macroSvg ${opt.compact?'compact':''}" viewBox="0 0 ${W} ${H}">${a.map((x,i)=>{const y=T+i*25,w=(W-L-R)*Number(x.value)/max;return `<text class="macroLabel" x="${L-7}" y="${y+12}" text-anchor="end">${esc(String(x.label).length>31?String(x.label).slice(0,29)+'…':x.label)}</text><rect class="${x.warn?'macroBarWarn':'macroBar'} chartAction" x="${L}" y="${y+3}" width="${Math.max(2,w)}" height="14" rx="3" ${x.onclick?`onclick="${x.onclick}"`:''}><title>${esc(x.label)}: ${esc(x.display??fmt(x.value))}</title></rect><text class="macroValue" x="${Math.min(W-R+3,L+w+5)}" y="${y+13}">${esc(x.display??fmt(x.value))}</text>`}).join('')}</svg>`
}
function vbar(rows,opt={}){
 const a=rows.filter(x=>Number.isFinite(Number(x.value))),W=620,H=205,L=32,R=14,T=12,Bt=30,max=Math.max(...a.map(x=>Number(x.value)),1),step=(W-L-R)/Math.max(1,a.length),bw=Math.max(9,step*.56);
 return `<svg class="macroSvg" viewBox="0 0 ${W} ${H}">${[0,1,2,3,4].map(i=>`<line class="macroAxis" x1="${L}" x2="${W-R}" y1="${T+i*(H-T-Bt)/4}" y2="${T+i*(H-T-Bt)/4}"/>`).join('')}${a.map((x,i)=>{const hh=(H-T-Bt)*Number(x.value)/max,xx=L+i*step+(step-bw)/2,yy=H-Bt-hh;return `<rect class="${x.warn?'macroBarWarn':i%2?'macroBar2':'macroBar'} chartAction" x="${xx}" y="${yy}" width="${bw}" height="${hh}" rx="3" ${x.onclick?`onclick="${x.onclick}"`:''}><title>${esc(x.label)}: ${esc(x.display??fmt(x.value))}</title></rect><text class="macroLabel" x="${xx+bw/2}" y="${H-12}" text-anchor="middle">${esc(String(x.label).slice(-6))}</text>`}).join('')}</svg>`
}
function lineChart(series,opt={}){
 const W=620,H=210,L=34,R=16,T=12,Bt=27,all=series.flatMap(s=>s.values.map(v=>Number(v.value||0))),max=Math.max(...all,1),min=Math.min(...all,0),range=Math.max(1,max-min),n=Math.max(...series.map(s=>s.values.length));
 const X=i=>L+i*(W-L-R)/Math.max(1,n-1),Y=v=>H-Bt-(Number(v)-min)*(H-T-Bt)/range;
 const colors=['#2b6ff3','#1495a3','#c1842c','#7659d6'];
 return `<svg class="macroSvg" viewBox="0 0 ${W} ${H}">${[0,1,2,3,4].map(i=>`<line class="macroAxis" x1="${L}" x2="${W-R}" y1="${T+i*(H-T-Bt)/4}" y2="${T+i*(H-T-Bt)/4}"/>`).join('')}${series.map((s,si)=>`<path d="${s.values.map((v,i)=>(i?'L':'M')+X(i).toFixed(1)+','+Y(v.value).toFixed(1)).join(' ')}" fill="none" stroke="${colors[si%colors.length]}" stroke-width="${si?2:2.7}" ${si?'stroke-dasharray="5 3"':''}/>${s.values.map((v,i)=>`<circle cx="${X(i)}" cy="${Y(v.value)}" r="2.4" fill="${colors[si%colors.length]}"><title>${esc(s.name)} · ${esc(v.label)}: ${fmt(v.value)}</title></circle>`).join('')}`).join('')}${series[0]?.values.map((v,i)=>`<text class="macroLabel" x="${X(i)}" y="${H-9}" text-anchor="middle">${esc(v.label)}</text>`).join('')}</svg><div class="macroLegend">${series.map((s,i)=>`<span><i style="background:${colors[i%colors.length]}"></i>${esc(s.name)}</span>`).join('')}</div>`
}
function scatter(rows,opt={}){
 const a=rows.filter(x=>Number.isFinite(x.x)&&Number.isFinite(x.y)),W=620,H=230,L=38,R=18,T=15,Bt=31,xmin=opt.xmin??Math.min(...a.map(x=>x.x),0),xmax=opt.xmax??Math.max(...a.map(x=>x.x),1),ymin=opt.ymin??Math.min(...a.map(x=>x.y),0),ymax=opt.ymax??Math.max(...a.map(x=>x.y),1);
 const X=x=>L+(x-xmin)/(xmax-xmin||1)*(W-L-R),Y=y=>H-Bt-(y-ymin)/(ymax-ymin||1)*(H-T-Bt);
 return `<svg class="macroSvg" viewBox="0 0 ${W} ${H}">${[0,1,2,3,4].map(i=>`<line class="macroAxis" x1="${L}" x2="${W-R}" y1="${T+i*(H-T-Bt)/4}" y2="${T+i*(H-T-Bt)/4}"/><line class="macroAxis" y1="${T}" y2="${H-Bt}" x1="${L+i*(W-L-R)/4}" x2="${L+i*(W-L-R)/4}"/>`).join('')}${a.map(x=>`<circle class="${x.warn?'macroDotWarn':'macroDot'} chartAction" cx="${X(x.x)}" cy="${Y(x.y)}" r="${Math.max(4,Math.min(12,x.r||6))}" ${x.onclick?`onclick="${x.onclick}"`:''}><title>${esc(x.label)} · x ${x.x.toFixed(1)} · y ${x.displayY??x.y.toFixed(1)}</title></circle>`).join('')}<text class="macroLabel" x="${(L+W-R)/2}" y="${H-6}" text-anchor="middle">${esc(opt.xlabel||'x')}</text><text class="macroLabel" transform="translate(10 ${(T+H-Bt)/2}) rotate(-90)" text-anchor="middle">${esc(opt.ylabel||'y')}</text></svg>`
}
function donut(parts,center,sub){const tot=sum(parts.map(x=>x.value))||1;let acc=0,cols=['#2b6ff3','#1495a3','#c1842c','#7659d6','#7e8b9c'];const stops=parts.map((p,i)=>{let s=acc/tot*100;acc+=p.value;let e=acc/tot*100;return `${cols[i%cols.length]} ${s}% ${e}%`}).join(',');return `<div class="donutWrap"><div class="macroDonut" style="background:conic-gradient(${stops})"><div class="donutCenter"><div><b>${esc(center)}</b><small>${esc(sub||'')}</small></div></div></div><div class="donutLegend">${parts.map((p,i)=>`<div><i style="background:${cols[i%cols.length]}"></i>${esc(p.label)} · <b>${p.display??fmt(p.value)}</b></div>`).join('')}</div></div>`}
function macroPanel(t,p,b){return `<div class="macroPanel"><h3>${t}</h3><p>${p}</p>${b}</div>`}
function analysisBox(text,points=[]){return `<div class="analysisBox"><div class="at"><b>Lectura analítica automática</b><span>determinística</span></div><p>${text}</p>${points.length?`<div class="analysisPoints">${points.map(x=>`<div class="analysisPoint ${x.kind||''}"><i></i><span>${x.text}</span></div>`).join('')}</div>`:''}</div>`}
function strip(items){return `<div class="insightStrip">${items.map(x=>`<div class="insightMini ${x.kind||''}"><b>${x.title}</b><span>${x.text}</span></div>`).join('')}</div>`}
function inject(html){const c=$('#canvas');if(!c||c.querySelector('.macroRefine'))return;const anchor=c.querySelector('.kpis')||c.querySelector('.answer');if(!anchor)return;const w=document.createElement('div');w.className='macroRefine';w.innerHTML=html;anchor.insertAdjacentElement('afterend',w)}
function clearMacro(){document.querySelector('.macroRefine')?.remove()}

/* ---------- Macro analyses ---------- */
function homeMacro(){
 const sectors=[...D.sectors],regs=D.regions.filter(x=>x.region!=='Sin información'),totalB=sum(sectors.map(x=>x.potenciales_no_observados_uaf_match_fuerte)),top=[...sectors].sort((a,b)=>b.potenciales_no_observados_uaf_match_fuerte-a.potenciales_no_observados_uaf_match_fuerte).slice(0,8),top3=sum(top.slice(0,3).map(x=>x.potenciales_no_observados_uaf_match_fuerte));
 const ros=RP.kpis||{}, topReg=[...regs].sort((a,b)=>b.anomalias_contextuales-a.anomalias_contextuales)[0],san=A.sanction_summary||{};
 const text=`El universo de screening está concentrado: los tres sectores con mayor brecha explican <strong>${share(top3,totalB).toFixed(1)}%</strong> de los pares sector–RUT no observados. En reportabilidad, los ROS crecieron <strong>${pct(ros.ros_yoy_pct)}</strong> en 2025, mientras las sanciones materializadas suman <strong>${fmt(san.total||0)}</strong> eventos. ${topReg?`La mayor carga de anomalías contextuales se observa en <strong>${esc(topReg.region)}</strong>.`:''}`;
 const rosSeries=[2021,2022,2023,2024,2025].map(y=>({label:String(y),value:sum((RP.sectors||[]).map(x=>x['ros_'+y]))}));
 inject(`${analysisBox(text,[{text:'Priorice primero concentración + persistencia + convergencia; el volumen aislado no es una conclusión.'},{text:'Los indicadores de reportabilidad son agregados y no identifican autoría individual de ROS.',kind:'warn'}])}<div class="macroGrid">${macroPanel('Brecha supervisiva · concentración sectorial','Top sectores por pares sector–RUT; cada barra abre la ficha sectorial.',hbar(top.map(x=>({label:x.sector_uaf,value:x.potenciales_no_observados_uaf_match_fuerte,onclick:`WB.openSector(${x.sector_id})`})),{limit:8,left:205}))}${macroPanel('ROS recibidos · serie macro','Evolución agregada 2021–2025 sobre datos públicos UAF.',lineChart([{name:'ROS agregados',values:rosSeries}]))}</div>`)
}
function fiscalMacro(){
 const s=[...D.sectors],total=sum(s.map(x=>x.potenciales_no_observados_uaf_match_fuerte)),top=[...s].sort((a,b)=>b.potenciales_no_observados_uaf_match_fuerte-a.potenciales_no_observados_uaf_match_fuerte),icps=s.map(x=>x.icp_cobertura_potencial_pct).filter(x=>x!=null),med=median(icps),top5=sum(top.slice(0,5).map(x=>x.potenciales_no_observados_uaf_match_fuerte)),noIcp=s.filter(x=>x.icp_cobertura_potencial_pct==null).length;
 const scat=s.filter(x=>x.icp_cobertura_potencial_pct!=null&&x.potenciales_no_observados_uaf_match_fuerte>0).map(x=>({label:x.sector_uaf,x:x.icp_cobertura_potencial_pct,y:Math.log10(x.potenciales_no_observados_uaf_match_fuerte+1),displayY:fmt(x.potenciales_no_observados_uaf_match_fuerte),r:4+Math.sqrt(x.sanciones_observadas||0)*1.5,warn:x.icp_cobertura_potencial_pct<(med||0),onclick:`WB.openSector(${x.sector_id})`}));
 inject(`${analysisBox(`Los cinco sectores con mayor brecha concentran <strong>${share(top5,total).toFixed(1)}%</strong> de los pares sector–RUT. La mediana ICP entre sectores comparables es <strong>${med==null?'—':med.toFixed(1)+'%'}</strong>; ${noIcp} sectores no disponen de ICP comparable y deben leerse como cobertura incompleta, no como cero.`,[{text:'El eje vertical del gráfico usa logaritmo para que sectores muy grandes no oculten al resto.'},{text:'Una brecha alta con ICP bajo es un foco de screening, no prueba de falta de inscripción.',kind:'warn'}])}<div class="macroGrid">${macroPanel('Cobertura vs tamaño de brecha','x = ICP; y = brecha (escala log); tamaño ≈ sanciones observadas.',scatter(scat,{xmin:0,xmax:100,xlabel:'ICP cobertura potencial (%)',ylabel:'Brecha · escala log'}))}${macroPanel('Concentración del screening','Top 10 sectores; pincha una barra para profundizar.',hbar(top.slice(0,10).map(x=>({label:x.sector_uaf,value:x.potenciales_no_observados_uaf_match_fuerte,onclick:`WB.openSector(${x.sector_id})`})),{left:205}))}</div>`)
}
function sectorMacro(name){
 const s=D.sectors.find(x=>norm(x.sector_uaf)===norm(name));if(!s)return;let rows=D.matrix.filter(x=>x.sector_id===s.sector_id),totB=sum(rows.map(x=>x.potenciales_no_observados_uaf_match_fuerte)),top=[...rows].sort((a,b)=>b.potenciales_no_observados_uaf_match_fuerte-a.potenciales_no_observados_uaf_match_fuerte).slice(0,8),top3=sum(top.slice(0,3).map(x=>x.potenciales_no_observados_uaf_match_fuerte));
 const comp=D.sectors.filter(x=>x.icp_cobertura_potencial_pct!=null),med=median(comp.map(x=>x.icp_cobertura_potencial_pct)),rank=[...D.sectors].sort((a,b)=>b.potenciales_no_observados_uaf_match_fuerte-a.potenciales_no_observados_uaf_match_fuerte).findIndex(x=>x.sector_id===s.sector_id)+1,breachRate=s.universo_sii_match_fuerte?share(s.potenciales_no_observados_uaf_match_fuerte,s.universo_sii_match_fuerte):null;const regionalMetric=totB>0?'potenciales_no_observados_uaf_match_fuerte':'sii_match_fuerte',regionalTitle=totB>0?'Brecha por región':'Universo SII fuerte por región',regionalDesc=totB>0?'Distribución sector × región; barras clickeables.':'La brecha no está regionalizada en esta actividad; se muestra el universo SII con match fuerte.';
 const rp=(RP.sectors||[]).find(x=>norm(x.sector).includes(norm(s.sector_uaf))||norm(s.sector_uaf).includes(norm(x.sector)));
 const text=`El sector ocupa la posición <strong>${rank} de ${D.sectors.length}</strong> por brecha potencial. ${breachRate==null?'No existe denominador SII fuerte suficiente para estimar proporción de screening.':`La brecha equivale a <strong>${breachRate.toFixed(1)}%</strong> del universo SII con match fuerte.`} ${s.icp_cobertura_potencial_pct==null?'ICP no disponible.':`Su ICP (${s.icp_cobertura_potencial_pct.toFixed(1)}%) está ${s.icp_cobertura_potencial_pct>med?'sobre':'bajo'} la mediana comparable (${med.toFixed(1)}%).`} ${totB?`Las tres regiones principales concentran ${share(top3,totB).toFixed(1)}% de la brecha sectorial.`:''}`;
 const points=[{text:`${fmt(s.sanciones_observadas)} sanciones y ${fmt(s.anomalias_contextuales)} anomalías contextuales están disponibles como dimensiones separadas.`}];if(rp)points.push({text:`Reportabilidad 2025: ${fmt(rp.ros_2025)} ROS agregados; intensidad ${rp.ros_per_registered_2025==null?'no disponible':Number(rp.ros_per_registered_2025).toFixed(3)} ROS/registrado.`,kind:'good'});
 inject(`${analysisBox(text,points)}${strip([{title:'Concentración territorial',text:totB?`Top 3 regiones: ${share(top3,totB).toFixed(1)}% de la brecha`:'Sin brecha regional materializada'},{title:'Contexto sancionatorio',text:`${fmt(s.sanciones_observadas)} eventos observados`,kind:s.sanciones_observadas?'warn':''},{title:'Reportabilidad',text:rp?`${fmt(rp.ros_2025)} ROS 2025 · ${pct(rp.yoy_2025_pct)} 12m`:'Sin reconciliación pública sectorial'}])}<div class="macroGrid">${macroPanel(regionalTitle,regionalDesc,hbar([...rows].sort((a,b)=>Number(b[regionalMetric]||0)-Number(a[regionalMetric]||0)).slice(0,8).map(x=>({label:x.region,value:Number(x[regionalMetric]||0),onclick:`WB.openRegion('${String(x.region).replaceAll("'","\\'")}')`})),{left:160}))}${macroPanel('Composición del sector','UAF observado, brecha y resto del universo SII fuerte.',donut([{label:'UAF observados',value:s.inscritos_uaf_observados},{label:'Brecha potencial',value:s.potenciales_no_observados_uaf_match_fuerte},{label:'Otros / diferencia',value:Math.max(0,s.universo_sii_match_fuerte-s.inscritos_uaf_observados-s.potenciales_no_observados_uaf_match_fuerte)}],fmt(s.universo_sii_match_fuerte),'SII match fuerte'))}</div>`)
}
function regionMacro(name){
 const r=D.regions.find(x=>norm(x.region)===norm(name));if(!r)return;const rows=D.matrix.filter(x=>norm(x.region)===norm(name)),totB=r.potenciales_no_observados_uaf_match_fuerte,top=[...rows].sort((a,b)=>b.potenciales_no_observados_uaf_match_fuerte-a.potenciales_no_observados_uaf_match_fuerte).slice(0,8),top3=sum(top.slice(0,3).map(x=>x.potenciales_no_observados_uaf_match_fuerte)),national=sum(D.regions.filter(x=>x.region!=='Sin información').map(x=>x.potenciales_no_observados_uaf_match_fuerte)),rate=r.entidades_fusion?1000*r.anomalias_contextuales/r.entidades_fusion:null;
 const text=`La región explica <strong>${share(totB,national).toFixed(1)}%</strong> de la brecha territorial materializada. ${totB?`Sus tres sectores principales concentran <strong>${share(top3,totB).toFixed(1)}%</strong> de esa brecha.`:''} La densidad descriptiva de anomalías es ${rate==null?'no calculable':`<strong>${rate.toFixed(1)}</strong> por 1.000 entidades Fusion`}; esta razón es contexto de datos, no una tasa de riesgo.`;
 inject(`${analysisBox(text,[{text:`${fmt(r.sanciones_observadas)} sanciones y ${fmt(r.alertas_fiscalizacion)} alertas de fiscalización están materializadas en la región.`},{text:'El contexto delictual territorial nunca se atribuye a una entidad por domicilio.',kind:'warn'}])}<div class="macroGrid">${macroPanel('Sectores que explican la brecha','Top sectores dentro de la región.',hbar(top.map(x=>({label:x.sector_uaf,value:x.potenciales_no_observados_uaf_match_fuerte,onclick:`WB.openSector(${x.sector_id})`})),{left:205}))}${macroPanel('Composición regional','Entidades, UAF observados y contexto disponible.',donut([{label:'UAF observados',value:r.inscritos_uaf_observados},{label:'SII match fuerte',value:r.sii_match_fuerte},{label:'Anomalías',value:r.anomalias_contextuales}],fmt(r.entidades_fusion),'entidades Fusion'))}</div>`)
}
function reportMacro(){
 const k=RP.kpis||{},groups=RP.broad_groups||[],bank=groups.find(x=>x.group==='Bancario'),fast=[...groups].sort((a,b)=>b.yoy_pct-a.yoy_pct)[0],silent=(RP.sectors||[]).filter(x=>x.registered_2025>0&&x.zero_ros_2025).length,total=k.ros_2025||sum(groups.map(x=>x.ros_2025));
 const years=[2021,2022,2023,2024,2025],series=years.map(y=>({label:String(y),value:sum((RP.sectors||[]).map(x=>x['ros_'+y]))}));
 inject(`${analysisBox(`Los ROS agregados crecieron <strong>${pct(k.ros_yoy_pct)}</strong> en 2025. El grupo bancario concentra <strong>${bank?share(bank.ros_2025,total).toFixed(1):'—'}%</strong> del volumen, mientras <strong>${fast?esc(fast.group):'—'}</strong> presenta la mayor variación interanual (${fast?pct(fast.yoy_pct):'—'}). Existen ${silent} sectores con entidades registradas y 0 ROS agregados en 2025; esa condición no implica incumplimiento individual.`,[{text:'Use intensidad ROS para comparar volumen relativo al tamaño del universo, no como tasa de cumplimiento.'},{text:'ROE sí tiene periodicidad, pero una alerta individual requiere evidencia de presentación por sujeto.',kind:'warn'}])}<div class="macroGrid">${macroPanel('ROS 2021–2025','Serie agregada UAF.',lineChart([{name:'ROS',values:series}]))}${macroPanel('Composición ROS 2025','Grupos amplios de reportabilidad.',donut(groups.map(x=>({label:x.group,value:x.ros_2025})),fmt(total),'ROS 2025'))}</div>`)
}
function reportSectorMacro(name){
 const x=(RP.sectors||[]).find(s=>norm(s.sector)===norm(name))||(RP.sectors||[]).find(s=>norm(name).includes(norm(s.sector))||norm(s.sector).includes(norm(name)));if(!x)return;
 const valid=(RP.sectors||[]).filter(s=>s.registered_2025>0&&s.ros_per_registered_2025!=null),sorted=[...valid].sort((a,b)=>a.ros_per_registered_2025-b.ros_per_registered_2025),idx=sorted.findIndex(s=>s===x),perc=idx>=0?100*idx/Math.max(1,sorted.length-1):null,series=[2021,2022,2023,2024,2025].map(y=>({label:String(y),value:x['ros_'+y]}));
 inject(`${analysisBox(`El sector registra <strong>${fmt(x.ros_2025)}</strong> ROS agregados en 2025 (${pct(x.yoy_2025_pct)} interanual). ${perc==null?'No existe intensidad comparable.':`Su intensidad ROS se ubica aproximadamente en el percentil <strong>${perc.toFixed(0)}</strong> entre sectores con universo registrado comparable.`} ${x.zero_ros_2025?'El agregado 2025 es cero; esto es una alerta de silencio sectorial, no individual.':''}`,[{text:`Periodicidad ROE: ${x.roe_cadence||'no calendarizada'}.`},{text:'No existe dato público de qué RUT generó cada ROS.',kind:'warn'}])}<div class="macroGrid">${macroPanel('Historia ROS del sector','Serie anual 2021–2025.',lineChart([{name:x.sector,values:series}]))}${macroPanel('Posición relativa','Intensidad ROS frente a sectores comparables.',hbar(sorted.slice(Math.max(0,idx-4),Math.min(sorted.length,idx+5)).map(s=>({label:s.sector,value:s.ros_per_registered_2025,warn:s===x,display:Number(s.ros_per_registered_2025).toFixed(3)})),{left:205}))}</div>`)
}
function sanctionsMacro(){
 const s=A.sanction_summary||{},total=s.total||0,res=s.resolved||0,un=s.unresolved||0,top=(s.by_supervisor||[])[0],peak=[...(s.by_year||[])].sort((a,b)=>b[1]-a[1])[0];
 inject(`${analysisBox(`De ${fmt(total)} eventos sancionatorios, <strong>${share(res,total).toFixed(1)}%</strong> tienen identidad resuelta y ${share(un,total).toFixed(1)}% permanecen como candidatos no resueltos. ${top?`<strong>${top[0]}</strong> concentra ${share(top[1],total).toFixed(1)}% de los eventos.`:''} ${peak?`El mayor volumen anual materializado corresponde a ${peak[0]} (${fmt(peak[1])}); 2026 es un año parcial.`:''}`,[{text:'La resolución de identidad condiciona la capacidad de cruzar sanciones con Entity 360.'},{text:'Una sanción administrativa no adquiere semántica LA/FT por el solo hecho de converger con otras fuentes.',kind:'warn'}])}<div class="macroGrid">${macroPanel('Evolución anual','Eventos materializados por año.',vbar((s.by_year||[]).map(x=>({label:x[0],value:x[1],warn:x[0]==='2026'}))))}${macroPanel('Supervisor e identidad','Composición de los 974 eventos.',donut((s.by_supervisor||[]).map(x=>({label:x[0],value:x[1]})),fmt(total),'eventos')+`<div class="macroLegend"><span><i style="background:#278563"></i>Identidad resuelta ${share(res,total).toFixed(1)}%</span><span><i style="background:#c1842c"></i>No resuelta ${share(un,total).toFixed(1)}%</span></div>`)}</div>`)
}
function anomalyMacro(){
 const types=A.anomaly_types||[],regions=A.anomaly_regions||[],total=sum(types.map(x=>x[2])),top=types[0],topR=regions[0];
 inject(`${analysisBox(`Las anomalías SII son marcas contextuales. <strong>${esc(top?.[1]||'—')}</strong> representa ${top?share(top[2],total).toFixed(1):'—'}% del total clasificado. Territorialmente, <strong>${esc(topR?.[0]||'—')}</strong> concentra ${topR?share(topR[1],total).toFixed(1):'—'}%. Estas concentraciones pueden reflejar estructura del universo y cobertura, por lo que requieren denominadores antes de interpretarse.`)}<div class="macroGrid">${macroPanel('Tipos de anomalía','Distribución descriptiva.',hbar(types.slice(0,10).map(x=>({label:x[1]||x[0]||'Sin código',value:x[2]})),{left:205}))}${macroPanel('Concentración territorial','Top regiones por marcas SII.',hbar(regions.slice(0,10).map(x=>({label:x[0],value:x[1]})),{left:175}))}</div>`)
}
function networkMacro(){
 const g=D.graph_summary,adv=A.graph||{},largest=g.largest_component_size||0,connected=g.connected_entities||1,paths=g.materialized_signal_paths||0;
 const comps=(adv.top_components||[]).slice(0,10).map(x=>({label:String(x[0]).slice(-10),value:Number(x[1]),display:`${x[1]} ent.`}));
 inject(`${analysisBox(`El mayor componente reúne <strong>${share(largest,connected).toFixed(1)}%</strong> de las entidades conectadas. Existen <strong>${fmt(g.articulation_point_count)}</strong> puntos de articulación y ${fmt(paths)} rutas materializadas hacia señales. Son propiedades topológicas: describen conectividad, no riesgo heredado.`,[{text:'Los hubs son útiles para priorizar expansión de contexto y búsqueda de relaciones observadas.'},{text:'Shortest path no implica control, conocimiento ni complicidad.',kind:'warn'}])}<div class="macroGrid">${macroPanel('Tamaño de componentes','Principales subredes por número de entidades.',hbar(comps,{left:130}))}${macroPanel('Estructura de la red','Magnitudes principales.',donut([{label:'Conectadas',value:g.connected_entities},{label:'Puntos articulación',value:g.articulation_point_count},{label:'Rutas a señales',value:g.materialized_signal_paths}],fmt(g.relationship_records),'relaciones'))}</div>`)
}
function territoryMacro(){
 const rr=[...D.map_region_metrics].sort((a,b)=>b.mapped_entity_count-a.mapped_entity_count),tot=sum(rr.map(x=>x.mapped_entity_count)),top3=sum(rr.slice(0,3).map(x=>x.mapped_entity_count)),cc=[...D.map_commune_metrics].sort((a,b)=>b.mapped_entity_count-a.mapped_entity_count).slice(0,10);
 inject(`${analysisBox(`Las tres regiones con mayor volumen concentran <strong>${share(top3,tot).toFixed(1)}%</strong> de las entidades georreferenciadas. La lectura territorial debe normalizarse por población/universo sectorial cuando la pregunta sea de intensidad; esta vista muestra presencia y contexto, no riesgo geográfico.`)}<div class="macroGrid">${macroPanel('Entidades mapeadas por región','Volumen territorial; barras clickeables.',hbar(rr.slice(0,10).map(x=>({label:x.region_name,value:x.mapped_entity_count,onclick:`WB.openRegion('${String(x.region_name).replaceAll("'","\\'")}')`})),{left:170}))}${macroPanel('Comunas con mayor presencia','Top 10 por entidades mapeadas.',hbar(cc.map(x=>({label:x.commune_name,value:x.mapped_entity_count,display:fmt(x.mapped_entity_count)})),{left:150}))}</div>`)
}
function cgrMacro(){
 const a=window.WB_CGR||[];if(!a.length)return;const byType=new Map(),byYear=new Map();a.forEach(x=>{byType.set(x[1]||'Sin tipo',(byType.get(x[1]||'Sin tipo')||0)+1);let y=String(x[2]||'').slice(0,4);if(/^20\d\d$/.test(y))byYear.set(y,(byYear.get(y)||0)+1)});const total=a.length,aud=byType.get('CGR_AUDIT')||0,news=byType.get('CGR_NEWS')||0;
 inject(`${analysisBox(`Los ${fmt(total)} eventos CGR materializados se distribuyen entre ${fmt(aud)} auditorías y ${fmt(news)} noticias/antecedentes. La utilidad principal es aportar contexto administrativo y relaciones con organismos; los nombres no resueltos permanecen como candidatos.`)}<div class="macroGrid">${macroPanel('Eventos por año','Fecha materializada en Fusion.',vbar([...byYear.entries()].sort().map(x=>({label:x[0],value:x[1]}))))}${macroPanel('Tipo de antecedente','Composición de la capa CGR.',donut([...byType.entries()].map(x=>({label:x[0].replace('CGR_',''),value:x[1]})),fmt(total),'eventos'))}</div>`)
}
function convergenceMacro(){
 const a=window.WB_FINDINGS_BY_TYPE?.ENTITY_CONVERGENCE||[];if(!a.length)return;const bySources=new Map(),comb=new Map();a.forEach(f=>{let n=Number(f.source_independence_count||1);bySources.set(n,(bySources.get(n)||0)+1);let k=[...(f.producer_ids||[])].sort().map(x=>x.replace('RADAR_','')).join(' + ');comb.set(k,(comb.get(k)||0)+1)});let total=a.length,more3=sum([...bySources].filter(x=>x[0]>=3).map(x=>x[1]));
 inject(`${analysisBox(`De ${fmt(total)} convergencias materializadas, <strong>${share(more3,total).toFixed(1)}%</strong> reúnen tres o más fuentes independientes. La convergencia mejora robustez contextual, pero sigue requiriendo revisar la semántica de cada hecho antes de escalar.`)}<div class="macroGrid">${macroPanel('Número de fuentes independientes','Distribución de convergencias.',vbar([...bySources.entries()].sort((a,b)=>a[0]-b[0]).map(x=>({label:String(x[0])+' fuentes',value:x[1]}))))}${macroPanel('Combinaciones más frecuentes','Productores que coinciden sobre un mismo contexto.',hbar([...comb.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10).map(x=>({label:x[0],value:x[1]})),{left:205}))}</div>`)
}
function signalsMacro(){
 const a=window.WB_FINDINGS_BY_TYPE?.GOVERNED_AML_SIGNAL||[];if(!a.length)return;const scores=a.map(f=>Number((f.decision_scores||{}).EXPLORAR||0)),med=median(scores),prods=new Map();a.forEach(f=>(f.producer_ids||[]).forEach(p=>prods.set(p,(prods.get(p)||0)+1)));
 inject(`${analysisBox(`La capa contiene ${a.length} señales AML gobernadas. El IPA mediano es <strong>${med==null?'—':med.toFixed(1)}</strong>; el score prioriza revisión y no estima probabilidad de delito. En esta familia la semántica AML es directa y por eso debe distinguirse de sanciones, anomalías o contexto territorial.`)}<div class="macroGrid">${macroPanel('Distribución de IPA','Cinco señales gobernadas.',vbar(scores.sort((a,b)=>b-a).map((x,i)=>({label:'Señal '+(i+1),value:x,display:x.toFixed(1)}))))}${macroPanel('Fuentes participantes','Productores de las señales gobernadas.',hbar([...prods.entries()].sort((a,b)=>b[1]-a[1]).map(x=>({label:x[0].replace('RADAR_',''),value:x[1]})),{left:140}))}</div>`)
}
function entityMacro(id){
 let ent=null;for(const shard of Object.values(window.WB_ENTITY_SHARDS||{})){ent=shard.find(x=>x.entity_id===id);if(ent)break}if(!ent)return;const cov=[['Identidad',ent.identity_confidence||0],['Territorio',ent.ubicacion?.geo_confidence||0],['Fuentes',Math.min(1,(ent.fuentes||[]).length/4)],['Evidencia',Math.min(1,(ent.evidence_ids||[]).length/5)],['Red',ent.red?.degree?Math.min(1,ent.red.degree/5):0]];
 const text=`La ficha dispone de <strong>${(ent.fuentes||[]).length}</strong> fuentes, ${fmt(ent.event_count)} eventos, ${(ent.relaciones||[]).length} relaciones observadas y ${(ent.evidence_ids||[]).length} referencias de evidencia. La cobertura de la ficha indica qué tan investigable es la entidad; no es un score de riesgo.`;
 inject(`${analysisBox(text,[{text:`Identidad: ${esc(ent.identity_method_es||ent.identity_method||'—')} · confianza ${Number(ent.identity_confidence||0).toFixed(2)}.`},{text:ent.red?.degree?`Conectividad: grado ${ent.red.degree}; componente ${ent.red.component_id||'—'}.`:'Sin relaciones de grafo materializadas.',kind:'good'}])}<div class="macroGrid">${macroPanel('Cobertura investigativa','Disponibilidad por dimensión; no riesgo.',hbar(cov.map(x=>({label:x[0],value:x[1]*100,display:(x[1]*100).toFixed(0)+'%'})),{left:120}))}${macroPanel('Composición de la ficha','Hechos observables disponibles.',donut([{label:'Eventos',value:ent.event_count||0},{label:'Relaciones',value:(ent.relaciones||[]).length},{label:'Evidencias',value:(ent.evidence_ids||[]).length},{label:'Señales',value:(ent.senales||[]).length}],esc(ent.rut||'Entidad'),'Entity 360'))}</div>`)
}

function enhance(app,arg){clearMacro();if(app==='home')homeMacro();else if(app==='fiscal')fiscalMacro();else if(app==='reportability')reportMacro();else if(app==='sanctions')sanctionsMacro();else if(app==='anomalies')anomalyMacro();else if(app==='convergence')convergenceMacro();else if(app==='network')networkMacro();else if(app==='territory')territoryMacro();else if(app==='cgr')cgrMacro();else if(app==='signals')signalsMacro();else if(app==='sector')sectorMacro(arg);else if(app==='region')regionMacro(arg);else if(app==='reportSector')reportSectorMacro(arg);else if(app==='entity')entityMacro(arg)}

/* ---------- Wrap existing routes, preserving all functionality ---------- */
const origShow=B.showApp, origSector=B.openSector, origRegion=B.openRegion, origEntity=B.openEntity, origReportSector=B.openReportSector, origReportRegion=B.openReportRegion, origReportTab=B.reportTab;
B.showApp=async name=>{navForApp(name);const r=origShow(name);await Promise.resolve(r);setTimeout(()=>enhance(name),0);return r};
B.openSector=async(...a)=>{buildNav('supervision','sector');const r=origSector(...a);await Promise.resolve(r);setTimeout(()=>enhance('sector',D.sectors.find(x=>Number(x.sector_id)===Number(a[0]))?.sector_uaf||a[0]),0);return r};
B.openRegion=async(...a)=>{buildNav('context','region');const r=origRegion(...a);await Promise.resolve(r);setTimeout(()=>enhance('region',a[0]),0);return r};
B.openEntity=async(...a)=>{buildNav('intelligence','entity');const r=origEntity(...a);await Promise.resolve(r);setTimeout(()=>enhance('entity',a[0]),0);return r};
if(origReportSector)B.openReportSector=(name)=>{buildNav('supervision','reportability');const r=origReportSector(name);setTimeout(()=>enhance('reportSector',name),0);return r};
if(origReportRegion)B.openReportRegion=(...a)=>{buildNav('supervision','reportability');const r=origReportRegion(...a);setTimeout(()=>enhance('region',a[0]),0);return r};
if(origReportTab)B.reportTab=tab=>{const r=origReportTab(tab);setTimeout(()=>{if(tab==='ros')enhance('reportability')},0);return r};

/* Filter changes can re-render sector/region through internal base handlers; observe canvas and reinject when needed. */
let reinjectTimer=null;const mo=new MutationObserver(()=>{clearTimeout(reinjectTimer);reinjectTimer=setTimeout(()=>{if(document.querySelector('.macroRefine'))return;const h=$('#canvas .answer h1')?.textContent||'';if(navApp==='fiscal'&&$('#sector').value)enhance('sector',$('#sector').value);else if(navApp==='territory'&&$('#region').value)enhance('region',$('#region').value)},80)});if($('#canvas'))mo.observe($('#canvas'),{childList:true});

window.WBR={selectCategory,buildNav,enhance};
buildNav('home','home');
setTimeout(()=>homeMacro(),0);
const snap=$('#snap');if(snap)snap.textContent=`${D.manifest.snapshot_id} · Fusion v${D.manifest.version} · Workbench v0.11 DESKTOP`;
})();
