(()=>{
'use strict';
const D=window.WB_CORE, RP=window.WB_REPORTABILITY||{}, BASE=window.WB;
if(!D||!BASE){console.error('Workbench enhancements: base unavailable');return}
const $=s=>document.querySelector(s), fmt=n=>new Intl.NumberFormat('es-CL').format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const pct=n=>n==null?'—':`${Number(n)>0?'+':''}${Number(n).toFixed(1)}%`;
const typeLabel={GOVERNED_AML_SIGNAL:'Señal AML gobernada',SUPERVISORY_GAP:'Brecha supervisiva',PRUDENTIAL_SANCTION:'Sanción',CONTEXTUAL_ANOMALY:'Anomalía contextual',ENTITY_CONVERGENCE:'Convergencia multifuente'};
const prodLabel={RADAR_SII:'SII',RADAR_UAF:'UAF',RADAR_SANCIONES:'Sanciones',RADAR_CGR:'CGR',RADAR_DELICTUAL:'Delictual',RADAR_OSFL:'OSFL'};

/* ---------- Shell & navigation ---------- */
const back=document.createElement('button'); back.id='backBtn'; back.className='backbtn'; back.innerHTML='← <span>Volver</span>'; back.disabled=true; back.onclick=()=>goBack();
$('.header').insertBefore(back,$('.brand'));

const sheetBack=document.createElement('div'); sheetBack.className='sheetback'; sheetBack.id='sheetBack'; sheetBack.onclick=()=>closeSheet();
const sheet=document.createElement('aside'); sheet.className='summarySheet'; sheet.id='summarySheet'; sheet.innerHTML='<div class="sheetHead"><div><small>FICHA RESUMIDA</small><b id="sheetTitle">Detalle</b></div><button onclick="WB.closeSheet()">×</button></div><div class="sheetBody" id="sheetBody"></div>';
document.body.append(sheetBack,sheet);

function openSheet(title,html){$('#sheetTitle').textContent=title;$('#sheetBody').innerHTML=html;sheetBack.classList.add('on');sheet.classList.add('on')}
function closeSheet(){sheetBack.classList.remove('on');sheet.classList.remove('on')}

const old={};
const oldRunQuery=BASE.runQuery;
['showApp','openSector','openRegion','openEntity','openSectorGap','openSectorRegionGap','openRegionGap','openCandidate','openSanction','openCGR','showEntityBrief'].forEach(k=>old[k]=BASE[k]);
let stack=[], current={kind:'base',fn:'showApp',args:['home']}, replaying=false;
function updateBack(){back.disabled=!stack.length;back.title=stack.length?`Volver (${stack.length})`:'Sin historial'}
function routeBase(fn,args){if(!replaying){stack.push(current);if(stack.length>40)stack.shift()}current={kind:'base',fn,args};updateBack();return old[fn](...args)}
function routeCustom(fn,args,renderer){if(!replaying){stack.push(current);if(stack.length>40)stack.shift()}current={kind:'custom',fn,args};updateBack();return renderer(...args)}
function replay(r){replaying=true;closeSheet();try{current=r;if(r.kind==='base')old[r.fn](...(r.args||[]));else if(r.fn==='reportability')renderReportability(...(r.args||[]));else if(r.fn==='reportSector')renderReportSector(...(r.args||[]));else if(r.fn==='reportRegion')renderReportRegion(...(r.args||[]));}finally{replaying=false;updateBack()}}
function goBack(){if(!stack.length)return;const r=stack.pop();replay(r)}

BASE.showApp=(name)=> name==='reportability'?routeCustom('reportability',['ros'],renderReportability):routeBase('showApp',[name]);
BASE.openSector=(...a)=>routeBase('openSector',a); BASE.openRegion=(...a)=>routeBase('openRegion',a); BASE.openEntity=async(...a)=>{const r=routeBase('openEntity',a);await Promise.resolve(r);decorateEntityReportability();return r};
BASE.openSectorGap=(...a)=>routeBase('openSectorGap',a); BASE.openSectorRegionGap=(...a)=>routeBase('openSectorRegionGap',a); BASE.openRegionGap=(...a)=>routeBase('openRegionGap',a);
// Candidate, sanctions, CGR and quick entity are summaries rather than full route changes.
BASE.openCandidate=(...a)=>{old.openCandidate(...a);setTimeout(()=>openSheet('Sociedad en screening',$('#context').innerHTML),0)};
BASE.openSanction=(...a)=>{old.openSanction(...a);setTimeout(()=>openSheet('Evento sancionatorio',$('#context').innerHTML),0)};
BASE.openCGR=(...a)=>{old.openCGR(...a);setTimeout(()=>openSheet('Antecedente CGR',$('#context').innerHTML),0)};
BASE.showEntityBrief=(...a)=>{old.showEntityBrief(...a);setTimeout(()=>openSheet('Ficha analítica rápida',$('#context').innerHTML),0)};

/* ---------- Simplified grouped navigation ---------- */
function groupedNav(){
 const bar=$('#appsbar'); if(!bar)return;
 bar.innerHTML=`
 <button class="appbtn on" data-app="home" onclick="WB.showApp('home')">⌂ Inicio</button>
 <div class="navgroup"><button class="navmain" onclick="WB.toggleGroup(this)">◎ Supervisión <span>⌄</span></button><div class="navmenu">
   <button data-app="fiscal" onclick="WB.showApp('fiscal')">Fiscalización <small>117k</small></button>
   <button data-app="reportability" onclick="WB.showApp('reportability')">Reportabilidad <small>ROS / ROE</small></button>
   <button data-app="sanctions" onclick="WB.showApp('sanctions')">Sanciones 360 <small>974</small></button>
 </div></div>
 <div class="navgroup"><button class="navmain" onclick="WB.toggleGroup(this)">◆ Inteligencia <span>⌄</span></button><div class="navmenu">
   <button data-app="anomalies" onclick="WB.showApp('anomalies')">Anomalías <small>12,7k</small></button>
   <button data-app="signals" onclick="WB.showApp('signals')">Señales AML <small>5</small></button>
   <button data-app="convergence" onclick="WB.showApp('convergence')">Convergencia <small>8,9k</small></button>
   <button data-app="network" onclick="WB.showApp('network')">Redes <small>1,7k</small></button>
 </div></div>
 <div class="navgroup"><button class="navmain" onclick="WB.toggleGroup(this)">⌖ Contexto <span>⌄</span></button><div class="navmenu">
   <button data-app="territory" onclick="WB.showApp('territory')">Territorio <small>345 comunas</small></button>
   <button data-app="cgr" onclick="WB.showApp('cgr')">CGR <small>90</small></button>
   <button data-app="compare" onclick="WB.showApp('compare')">Comparar</button>
 </div></div>
 <button class="appbtn" data-app="cases" onclick="WB.showApp('cases')">★ Casos <span class="appcount" id="caseCount2">0</span></button>
 <div class="navhint">Todo sigue disponible · menos navegación</div>`;
}
function toggleGroup(btn){const g=btn.closest('.navgroup');document.querySelectorAll('.navgroup.open').forEach(x=>{if(x!==g)x.classList.remove('open')});g.classList.toggle('open')}
document.addEventListener('click',e=>{if(!e.target.closest('.navgroup'))document.querySelectorAll('.navgroup.open').forEach(x=>x.classList.remove('open'))});
function setActive(name){document.querySelectorAll('[data-app]').forEach(x=>x.classList.toggle('active',x.dataset.app===name));document.querySelectorAll('.navgroup').forEach(g=>g.classList.toggle('hasactive',!!g.querySelector(`[data-app="${name}"]`)));const c=$('#caseCount2');if(c){try{const a=JSON.parse(localStorage.getItem('aml_workbench_cases_v090')||'[]');c.textContent=a.length}catch(e){c.textContent='0'}}}
const oldShow=BASE.showApp;BASE.showApp=(name)=>{document.querySelectorAll('.navgroup.open').forEach(x=>x.classList.remove('open'));setActive(name);return oldShow(name)};

/* ---------- Mobile primary navigation ---------- */
const mobile=document.createElement('nav');mobile.className='mobilebar';mobile.innerHTML=`<button onclick="WB.showApp('home')"><b>⌂</b><span>Inicio</span></button><button onclick="WB.showApp('reportability')"><b>↗</b><span>Reportes</span></button><button onclick="WB.showApp('fiscal')"><b>◎</b><span>Fiscalizar</span></button><button onclick="WB.openMobileMenu()"><b>☰</b><span>Más</span></button>`;document.body.appendChild(mobile);
function openMobileMenu(){openSheet('Todas las aplicaciones',`<div class="mobileGrid">
<button onclick="WB.closeSheet();WB.showApp('fiscal')">◎<b>Fiscalización</b></button><button onclick="WB.closeSheet();WB.showApp('reportability')">↗<b>Reportabilidad</b></button><button onclick="WB.closeSheet();WB.showApp('sanctions')">⚖<b>Sanciones</b></button><button onclick="WB.closeSheet();WB.showApp('anomalies')">⌁<b>Anomalías</b></button><button onclick="WB.closeSheet();WB.showApp('signals')">◆<b>Señales AML</b></button><button onclick="WB.closeSheet();WB.showApp('convergence')">✣<b>Convergencia</b></button><button onclick="WB.closeSheet();WB.showApp('network')">◉<b>Redes</b></button><button onclick="WB.closeSheet();WB.showApp('territory')">⌖<b>Territorio</b></button><button onclick="WB.closeSheet();WB.showApp('cgr')">▣<b>CGR</b></button><button onclick="WB.closeSheet();WB.showApp('compare')">⇄<b>Comparar</b></button><button onclick="WB.closeSheet();WB.showApp('cases')">★<b>Casos</b></button><button onclick="WB.closeSheet();WB.showHealth()">●<b>Salud datos</b></button></div>`)}


function decorateEntityReportability(){const c=$('#canvas');if(!c||c.querySelector('.entityReportability'))return;const isUaf=[...c.querySelectorAll('.mark')].some(x=>/UAF observado|Sujeto obligado/i.test(x.textContent||''));const box=document.createElement('section');box.className='card panel entityReportability';box.style.marginTop='10px';box.innerHTML=`<div class="ph"><div><b>Reportabilidad individual</b><p>Disponibilidad pública en la ficha del sujeto.</p></div></div><div class="metrics2"><div><b>${isUaf?'Sí':'No / no observado'}</b><span>Sujeto obligado UAF en Fusion</span></div><div><b>Reservado</b><span>autoría/cantidad ROS individual</span></div><div><b>No evaluable</b><span>cumplimiento ROE individual</span></div><div><b>Pendiente</b><span>sector/cadencia ROE a nivel entidad</span></div></div><div class="warnbox">No se genera una marca “no reportó ROS”. Para alertar ROE vencido se requiere materializar sector, periodicidad y evidencia de presentación por sujeto.</div><button class="button" onclick="WB.showApp('reportability')">Abrir Observatorio de reportabilidad</button>`;c.appendChild(box)}

/* ---------- Summary cards / clickable scores ---------- */
function scoreInfo(v){openSheet(`IPA 2.0 · ${Number(v).toFixed(1)}`,`<div class="quickScore"><div class="scoreRing">${Number(v).toFixed(1)}</div><div><b>Prioridad analítica</b><p>Ordena revisión. No es probabilidad de delito, LA/FT ni incumplimiento.</p></div></div><div class="sheetSection"><h3>Qué entra al IPA 2.0</h3>${scoreFactor('Fuerza de regla','35–45% según perspectiva')}${scoreFactor('Fuentes independientes','15–30%')}${scoreFactor('Evidencia','10–20%')}${scoreFactor('Recurrencia','15–20%')}${scoreFactor('Contexto de red','5–15%')}</div><div class="warnbox">Recencia y materialidad no forman parte del score hasta contar con capas gobernadas suficientes.</div>`)}
function scoreFactor(n,v){return `<div class="metricRow"><span>${esc(n)}</span><b>${esc(v)}</b></div>`}
function previewFinding(id,type){const f=(window.WB_FINDINGS_BY_TYPE?.[type]||[]).find(x=>x.finding_id===id);if(!f)return old.openFinding(id,type);const score=Number(f.decision_scores?.EXPLORAR||0);const features=f.decision_features||{},facts=f.decision_facts||{},eid=f.scope?.entity_ids?.[0];openSheet(typeLabel[type]||type,`<div class="brief"><b>${esc(f.title)}</b><br>${esc(f.explanation||'')}</div><div class="quickScore" onclick="WB.openScoreInfo(${score})"><div class="scoreRing">${score.toFixed(1)}</div><div><b>IPA 2.0 · pincha para explicar</b><p>${esc(f.region||'Sin región')} · ${f.source_independence_count||1} fuente(s)</p></div></div><div class="markbar">${(f.producer_ids||[]).map(x=>`<span class="mark info">${esc(prodLabel[x]||x)}</span>`).join('')}</div><div class="sheetSection"><h3>Hechos observables</h3><div class="metrics2"><div><b>${facts.evidence_count??0}</b><span>evidencias</span></div><div><b>${facts.sanctions??0}</b><span>sanciones</span></div><div><b>${facts.contextual_anomalies??0}</b><span>anomalías</span></div><div><b>${facts.observed_relationships??0}</b><span>relaciones</span></div></div></div><div class="sheetSection"><h3>Factores</h3>${Object.entries(features).map(([k,v])=>`<div class="factor"><span>${esc(k.replaceAll('_',' '))}</span><div class="track"><i style="width:${Math.min(100,Number(v||0))}%"></i></div><b>${Number(v||0).toFixed(0)}</b></div>`).join('')}</div><div class="actionrow">${eid?`<button class="actionbtn primary" onclick="WB.closeSheet();WB.openEntity('${esc(eid)}')">Abrir Entity 360</button>`:''}<button class="actionbtn" onclick="WB.closeSheet();WB.openFinding('${esc(id)}','${esc(type)}')">Abrir análisis</button></div><div class="warnbox">${esc(f.guardrail||'Prioridad analítica ≠ conclusión de LA/FT.')}</div>`)}
function previewSector(id){const s=D.sectors.find(x=>Number(x.sector_id)===Number(id));if(!s)return;const rp=findRPSector(s.sector_uaf);openSheet(s.sector_uaf,`<div class="metrics2"><div><b>${fmt(s.inscritos_uaf_observados)}</b><span>UAF observados</span></div><div><b>${fmt(s.universo_sii_match_fuerte)}</b><span>SII match fuerte</span></div><div><b>${fmt(s.potenciales_no_observados_uaf_match_fuerte)}</b><span>brecha screening</span></div><div><b>${s.icp_cobertura_potencial_pct==null?'—':Number(s.icp_cobertura_potencial_pct).toFixed(1)+'%'}</b><span>ICP</span></div></div>${rp?`<div class="sheetSection"><h3>Reportabilidad UAF 2025</h3><div class="metricRow"><span>ROS</span><b>${fmt(rp.ros_2025)}</b></div><div class="metricRow"><span>Entidades registradas</span><b>${fmt(rp.registered_2025)}</b></div><div class="metricRow"><span>Intensidad ROS/entidad</span><b>${rp.ros_per_registered_2025==null?'—':rp.ros_per_registered_2025.toFixed(3)}</b></div></div>`:''}<div class="actionrow"><button class="actionbtn primary" onclick="WB.closeSheet();WB.openSector(${s.sector_id})">Abrir sector</button>${rp?`<button class="actionbtn" onclick="WB.closeSheet();WB.openReportSector('${esc(rp.sector).replaceAll("'","\\'")}')">Reportabilidad</button>`:''}</div>`)}
function previewRegion(name){const r=D.regions.find(x=>x.region===name);if(!r)return;const rr=findRPRegion(name);openSheet(name,`<div class="metrics2"><div><b>${fmt(r.entidades_fusion)}</b><span>entidades Fusion</span></div><div><b>${fmt(r.inscritos_uaf_observados)}</b><span>UAF observados</span></div><div><b>${fmt(r.potenciales_no_observados_uaf_match_fuerte)}</b><span>brecha screening</span></div><div><b>${fmt(r.anomalias_contextuales)}</b><span>anomalías</span></div></div>${rr?`<div class="sheetSection"><h3>Registro UAF 2025</h3><div class="metricRow"><span>Entidades privadas registradas</span><b>${fmt(rr.registered)}</b></div><div class="metricRow"><span>Participación nacional</span><b>${rr.share_pct.toFixed(2)}%</b></div></div>`:''}<div class="actionrow"><button class="actionbtn primary" onclick="WB.closeSheet();WB.openRegion('${esc(name).replaceAll("'","\\'")}')">Abrir territorio</button>${rr?`<button class="actionbtn" onclick="WB.closeSheet();WB.openReportRegion('${esc(rr.region).replaceAll("'","\\'")}')">Reportabilidad</button>`:''}</div>`)}


function smartQuery(){const q=norm($('#query')?.value||'');if(!q)return oldRunQuery();const rs=(RP.sectors||[]).find(x=>q.includes(norm(x.sector)));if(q.includes('roe')){if(rs)return routeCustom('reportSector',[rs.sector],renderReportSector);BASE.showApp('reportability');setTimeout(()=>BASE.reportTab('roe'),0);return}if(q.includes('ros')||q.includes('reportabilidad')||q.includes('reportes')||q.includes('no reporte')||q.includes('no reporta')){if(rs)return routeCustom('reportSector',[rs.sector],renderReportSector);BASE.showApp('reportability');if(q.includes('no reporte')||q.includes('no reporta')||q.includes('silencio'))setTimeout(()=>BASE.reportTab('alerts'),0);return}return oldRunQuery()}

/* ---------- Reportability ---------- */
const aliases={
 'metropolitana de santiago':'metropolitana de santiago','metropolitana':'metropolitana de santiago',
 "libertador general bernardo o higgins":"libertador general bernardo o higgins","o higgins":"libertador general bernardo o higgins",
 'aysen del general carlos ibanez del campo':'aysen del general carlos ibanez del campo','aysen':'aysen del general carlos ibanez del campo',
 'magallanes y de la antartica chilena':'magallanes y de la antartica chilena','magallanes':'magallanes y de la antartica chilena'
};
function rkey(x){let n=norm(x);return aliases[n]||n}
function findRPRegion(name){return (RP.regions_registered_2025||[]).find(x=>rkey(x.region)===rkey(name))}
function findDRegion(name){return D.regions.find(x=>rkey(x.region)===rkey(name))}
function findRPSector(name){let n=norm(name);return (RP.sectors||[]).find(x=>norm(x.sector)===n)||null}
function findDSector(name){let n=norm(name);return D.sectors.find(x=>norm(x.sector_uaf)===n)||null}
function appSet(name){setActive(name);document.querySelectorAll('.navgroup.open').forEach(x=>x.classList.remove('open'))}
function card(label,value,sub,cls=''){return `<div class="card kpi reportKpi" ${cls}><small>${label}</small><b>${value}</b><span>${sub}</span></div>`}
function pan(t,s,b,extra=''){return `<section class="card panel"><div class="ph"><div><b>${t}</b>${s?`<p>${s}</p>`:''}</div><span class="grow"></span>${extra}</div>${b}</section>`}
function sourceLinks(){return `<div class="contextBlock"><h3>Fuentes oficiales UAF</h3>${(RP.sources||[]).map(x=>`<div class="evidence"><b>${esc(x.title)}</b><p>${esc(x.published||'Fuente vigente')}</p><a href="${esc(x.url)}" target="_blank" rel="noopener">Abrir fuente ↗</a></div>`).join('')}</div>`}
function reportTabs(tab){return `<div class="reportTabs"><button class="${tab==='ros'?'on':''}" onclick="WB.reportTab('ros')">ROS · intensidad</button><button class="${tab==='roe'?'on':''}" onclick="WB.reportTab('roe')">ROE · calendario</button><button class="${tab==='alerts'?'on':''}" onclick="WB.reportTab('alerts')">Alertas analíticas</button></div>`}
function renderReportability(tab='ros'){
 appSet('reportability');
 $('#sector').value='';$('#region').value='';
 let body=tab==='roe'?roeHome():tab==='alerts'?reportAlerts():rosHome();
 $('#canvas').innerHTML=`<section class="card answer"><div class="answerTop"><div><div class="eyebrow">Supervisión · datos oficiales UAF</div><h1>Observatorio de reportabilidad</h1><p>ROS y ROE se presentan con semánticas distintas. La intensidad ROS es agregada por sector; el envío individual de ROS es confidencial. ROE es periódico y su alerta individual requerirá un feed operacional de presentaciones.</p></div></div><div class="chips"><span class="chip blue">UAF 2025</span><span class="chip">55 actividades</span><span class="chip">ROS ≠ cumplimiento</span><span class="chip warn">ROE individual · feed pendiente</span></div></section>${reportTabs(tab)}${body}`;
 $('#context').innerHTML=`<div class="contextBlock"><h3>Semántica</h3><p><b>Intensidad ROS:</b> ROS recibidos / entidades registradas del sector. No es porcentaje de entidades que reportó.</p><p style="margin-top:6px"><b>Silencio ROS:</b> cero ROS agregados en un sector. Es señal analítica, no prueba de incumplimiento.</p><p style="margin-top:6px"><b>ROE:</b> obligación periódica. Una alerta individual sólo es válida con evidencia de presentación/no presentación.</p></div>${sourceLinks()}`;
}
function rosHome(){
 const k=RP.kpis||{}, top=[...(RP.sectors||[])].filter(x=>x.registered_2025>0).sort((a,b)=>(b.ros_2025||0)-(a.ros_2025||0));
 return `<div class="kpis">${card('ROS 2025',fmt(k.ros_2025),`${pct(k.ros_yoy_pct)} vs 2024`)}${card('Entidades registradas',fmt(k.registered_total_2025),`${fmt(k.registered_private_2025)} privadas · ${fmt(k.registered_public_2025)} públicas`)}${card('ROS con indicios',fmt(k.ros_indicios_2025),'resultado agregado UAF')}${card('ROS 2021–2025',fmt(k.ros_2021_2025),'serie acumulada')}</div>
 <div class="grid two">${pan('Reportabilidad por sector','Pincha cualquier sector para desagregarlo.',reportSectorTable(top))}${pan('Composición ROS 2025','Participación y variación por macrogrupo.',(RP.broad_groups||[]).map(g=>`<div class="metricRow big"><span><b>${esc(g.group)}</b><small>${pct(g.yoy_pct)} interanual</small></span><b>${fmt(g.ros_2025)}</b></div>`).join(''))}</div>
 <div class="grid equal" style="margin-top:10px">${pan('Base reportante por región','Registro privado UAF a 31/12/2025. No implica distribución regional de ROS.',reportRegionTable(RP.regions_registered_2025||[]))}${pan('Cómo leer la tasa','La métrica útil es intensidad, no cumplimiento.',`<div class="definition"><b>Intensidad ROS sectorial</b><div class="formula">ROS 2025 ÷ entidades registradas 2025</div><p>Sirve para comparar órdenes de magnitud y tendencias. No identifica quién reportó, cuántos sujetos reportaron ni si un sujeto incumplió.</p></div><button class="button" onclick="WB.reportTab('alerts')">Ver silencios sectoriales →</button>`)}</div>`}
function reportSectorTable(a){return `<div class="tablewrap" style="max-height:560px"><table><thead><tr><th>Sector</th><th>Registrados</th><th>ROS 2025</th><th>ROS/entidad</th><th>12m</th><th>ROE</th><th>Marca</th></tr></thead><tbody>${a.map(x=>`<tr class="click" onclick="WB.openReportSector('${esc(x.sector).replaceAll("'","\\'")}')"><td><b>${esc(x.sector)}</b></td><td>${fmt(x.registered_2025)}</td><td>${fmt(x.ros_2025)}</td><td><button class="scorelink" onclick="event.stopPropagation();WB.explainIntensity('${esc(x.sector).replaceAll("'","\\'")}')">${x.ros_per_registered_2025==null?'—':Number(x.ros_per_registered_2025).toFixed(x.ros_per_registered_2025>=10?1:3)}</button></td><td class="${x.yoy_2025_pct!=null&&x.yoy_2025_pct>25?'red':''}">${pct(x.yoy_2025_pct)}</td><td><span class="cadence ${String(x.roe_cadence).toLowerCase()}">${esc(x.roe_cadence||'—')}</span></td><td>${x.registered_2025>0&&x.zero_ros_5y?'<span class="mark alert">Silencio 5a</span>':x.registered_2025>0&&x.zero_ros_2025?'<span class="mark warn">0 ROS 2025</span>':'<span class="mark good">Actividad ROS</span>'}</td></tr>`).join('')}</tbody></table></div>`}
function reportRegionTable(a){return `<div class="tablewrap"><table><thead><tr><th>Región</th><th>Registrados</th><th>% nacional</th><th>Fusion UAF obs.</th></tr></thead><tbody>${[...a].sort((x,y)=>y.registered-x.registered).map(x=>{const d=findDRegion(x.region);return `<tr class="click" onclick="WB.openReportRegion('${esc(x.region).replaceAll("'","\\'")}')"><td><b>${esc(x.region)}</b></td><td>${fmt(x.registered)}</td><td>${Number(x.share_pct).toFixed(2)}%</td><td>${d?fmt(d.inscritos_uaf_observados):'—'}</td></tr>`}).join('')}</tbody></table></div>`}
function spark5(x){const vals=[x.ros_2021,x.ros_2022,x.ros_2023,x.ros_2024,x.ros_2025].map(Number),W=520,H=190,p=28,m=Math.max(...vals,1),gap=(W-p*2)/4;return `<svg class="chart" viewBox="0 0 ${W} ${H}">${[0,1,2,3].map(i=>`<line class="gridline" x1="${p}" x2="${W-p}" y1="${p+i*(H-p*2)/3}" y2="${p+i*(H-p*2)/3}"/>`).join('')}<polyline points="${vals.map((v,i)=>`${p+i*gap},${H-p-v/m*(H-p*2)}`).join(' ')}" fill="none" stroke="#2b6ff3" stroke-width="3"/>${vals.map((v,i)=>`<circle cx="${p+i*gap}" cy="${H-p-v/m*(H-p*2)}" r="4" fill="#2b6ff3"><title>${2021+i}: ${v}</title></circle><text class="axistext" x="${p+i*gap-10}" y="${H-7}">${2021+i}</text>`).join('')}</svg>`}
function renderReportSector(name){
 appSet('reportability'); const x=findRPSector(name);if(!x)return renderReportability('ros');const d=findDSector(name), rows=d?D.matrix.filter(r=>Number(r.sector_id)===Number(d.sector_id)).sort((a,b)=>b.inscritos_uaf_observados-a.inscritos_uaf_observados):[];
 $('#canvas').innerHTML=`<section class="card answer"><div class="answerTop"><div><div class="eyebrow">Reportabilidad sectorial · UAF</div><h1>${esc(x.sector)}</h1><p>La lectura combina serie ROS pública, universo registrado, periodicidad ROE y contexto Fusion. No identifica emisores individuales de ROS.</p></div></div><div class="chips"><span class="chip blue">${fmt(x.ros_2025)} ROS 2025</span><span class="chip">${fmt(x.registered_2025)} registrados</span><span class="chip">ROE ${esc(x.roe_cadence)}</span>${x.zero_ros_2025?'<span class="chip warn">Silencio ROS 2025</span>':''}</div></section>
 <div class="kpis">${card('ROS 2025',fmt(x.ros_2025),`${pct(x.yoy_2025_pct)} vs 2024`)}${card('Registrados',fmt(x.registered_2025),'UAF 31/12/2025')}${card('Intensidad',x.ros_per_registered_2025==null?'—':Number(x.ros_per_registered_2025).toFixed(x.ros_per_registered_2025>=10?1:3),'ROS por entidad registrada')}${card('Participación ROS',Number(x.ros_share_2025_pct).toFixed(2)+'%','del total privado 2025')}</div>
 <div class="grid two">${pan('Serie ROS 2021–2025','Datos agregados oficiales UAF.',spark5(x))}${pan('Ficha de reportabilidad','Indicadores que sí están disponibles.',`<div class="metricRow"><span>ROS acumulados 5 años</span><b>${fmt(x.ros_5y)}</b></div><div class="metricRow"><span>ROE requerido</span><b>${x.roe_required?'Sí':'No / no calendarizado'}</b></div><div class="metricRow"><span>Periodicidad ROE</span><b>${esc(x.roe_cadence)}</b></div>${d?`<div class="metricRow"><span>UAF observados en Fusion</span><b>${fmt(d.inscritos_uaf_observados)}</b></div><div class="metricRow"><span>Brecha screening Fusion</span><b>${fmt(d.potenciales_no_observados_uaf_match_fuerte)}</b></div>`:''}<div class="actionrow">${d?`<button class="actionbtn primary" onclick="WB.openSector(${d.sector_id})">Abrir ficha Fusion</button><button class="actionbtn" onclick="WB.openSectorGap(${d.sector_id})">Ver brecha</button>`:''}</div>`)}</div>
 ${pan('Desagregación territorial de la base UAF','La UAF pública permite observar población registrada; no publica ROS por entidad/región. Fusion aporta la distribución de sujetos observados por sector y región.',rows.length?`<div class="tablewrap"><table><thead><tr><th>Región</th><th>UAF observados Fusion</th><th>SII fuerte</th><th>Brecha screening</th><th>ROS regional</th></tr></thead><tbody>${rows.map(r=>`<tr class="click" onclick="WB.openReportRegion('${esc(r.region).replaceAll("'","\\'")}', '${esc(x.sector).replaceAll("'","\\'")}')"><td><b>${esc(r.region)}</b></td><td>${fmt(r.inscritos_uaf_observados)}</td><td>${fmt(r.sii_match_fuerte)}</td><td>${fmt(r.potenciales_no_observados_uaf_match_fuerte)}</td><td><span class="mini">No público</span></td></tr>`).join('')}</tbody></table></div>`:'<div class="missing">No existe matriz sector×región materializada para este sector.</div>')}
 <div class="card panel subjectBoundary"><b>Nivel sujeto obligado</b><p>La ficha individual puede mostrar identidad, sector/contexto y obligación ROE cuando esa relación esté materializada; <strong>no puede mostrar “no reportó ROS”</strong> porque el ROS individual es confidencial y no tiene periodicidad obligatoria.</p><div class="actionrow"><button class="actionbtn" onclick="document.querySelector('#query').focus()">Buscar RUT / entidad</button><button class="actionbtn" onclick="WB.reportTab('roe')">Ver vigilancia ROE</button></div></div>`;
 $('#context').innerHTML=`<div class="contextBlock"><h3>Interpretación</h3><p><b>${esc(x.sector)}</b> generó ${fmt(x.ros_2025)} ROS en 2025 sobre ${fmt(x.registered_2025)} entidades registradas. La intensidad ${x.ros_per_registered_2025==null?'no es calculable':`es ${Number(x.ros_per_registered_2025).toFixed(3)} ROS/entidad`}; no equivale a una tasa de cumplimiento.</p></div>${sourceLinks()}`;
}
function renderReportRegion(name,sectorName=''){
 appSet('reportability'); const r=findRPRegion(name),d=findDRegion(name);if(!r)return renderReportability('ros');const sup=(RP.supervision_2025?.regions||[]).find(x=>rkey(x[0])===rkey(name));const ds=sectorName?findDSector(sectorName):null;const sr=ds?D.matrix.find(x=>Number(x.sector_id)===Number(ds.sector_id)&&rkey(x.region)===rkey(name)):null;const regionSectors=d?[...D.matrix].filter(x=>rkey(x.region)===rkey(d.region)).sort((a,b)=>b.inscritos_uaf_observados-a.inscritos_uaf_observados).slice(0,18):[];
 $('#canvas').innerHTML=`<section class="card answer"><div class="answerTop"><div><div class="eyebrow">Reportabilidad territorial · UAF</div><h1>${esc(r.region)}</h1><p>La región se caracteriza por su base registrada y contexto Fusion. La distribución regional de ROS no está publicada como dato general de sujeto/sector.</p></div></div><div class="chips"><span class="chip blue">${fmt(r.registered)} registrados privados</span><span class="chip">${Number(r.share_pct).toFixed(2)}% nacional</span>${sectorName?`<span class="chip warn">${esc(sectorName)}</span>`:''}</div></section>
 <div class="kpis">${card('Registrados 2025',fmt(r.registered),'sector privado UAF')}${card('Participación nacional',Number(r.share_pct).toFixed(2)+'%','registro privado')}${card('UAF observados Fusion',d?fmt(d.inscritos_uaf_observados):'—','snapshot actual')}${card('Supervisiones 2025',sup?fmt(sup[1]):'0','UAF oficial')}</div>
 ${sr?`<div class="card panel reportSectorRegion"><b>${esc(sectorName)} · ${esc(r.region)}</b><p class="mutedP">Desagregación sector×región disponible en Fusion: ${fmt(sr.inscritos_uaf_observados)} UAF observados · ${fmt(sr.sii_match_fuerte)} SII match fuerte · ${fmt(sr.potenciales_no_observados_uaf_match_fuerte)} brecha. ROS regional por RUT no es público.</p><div class="actionrow"><button class="actionbtn" onclick="WB.openSectorRegionGap(${sr.sector_id},'${esc(sr.region).replaceAll("'","\\'")}')">Individualizar brecha</button></div></div>`:''}<div class="grid two">${pan('Contexto Fusion','Complementa la base UAF sin atribuir reportes.',d?`<div class="metricRow"><span>Entidades Fusion</span><b>${fmt(d.entidades_fusion)}</b></div><div class="metricRow"><span>Brecha de screening</span><b>${fmt(d.potenciales_no_observados_uaf_match_fuerte)}</b></div><div class="metricRow"><span>Sanciones observadas</span><b>${fmt(d.sanciones_observadas)}</b></div><div class="metricRow"><span>Anomalías contextuales</span><b>${fmt(d.anomalias_contextuales)}</b></div><div class="actionrow"><button class="actionbtn primary" onclick="WB.openRegion('${esc(d.region).replaceAll("'","\\'")}')">Abrir territorio</button><button class="actionbtn" onclick="WB.openRegionGap('${esc(d.region).replaceAll("'","\\'")}')">Brecha individual</button></div>`:'<div class="missing">Región no reconciliada con Fusion.</div>')}${pan('Disponibilidad de reportabilidad','Qué puede y no puede responderse hoy.',`<div class="availability yes"><b>✓</b><span>Entidades registradas por región</span></div><div class="availability yes"><b>✓</b><span>Supervisiones UAF agregadas</span></div><div class="availability partial"><b>~</b><span>ROE bancario: sólo algunas participaciones regionales publicadas</span></div><div class="availability no"><b>×</b><span>ROS individual/regional por RUT: confidencial / no publicado</span></div>`)}</div>${regionSectors.length?pan('Sectores UAF observados en la región','Base Fusion; pincha para revisar reportabilidad sectorial.',`<div class="tablewrap"><table><thead><tr><th>Sector</th><th>UAF obs.</th><th>Brecha</th><th>ROS 2025 nacional</th></tr></thead><tbody>${regionSectors.map(x=>{const rp=findRPSector(x.sector_uaf);return `<tr class="click" onclick="WB.openReportSector('${esc(x.sector_uaf).replaceAll("'","\\'")}')"><td><b>${esc(x.sector_uaf)}</b></td><td>${fmt(x.inscritos_uaf_observados)}</td><td>${fmt(x.potenciales_no_observados_uaf_match_fuerte)}</td><td>${rp?fmt(rp.ros_2025):'—'}</td></tr>`}).join('')}</tbody></table></div>`):''}`;
 $('#context').innerHTML=`<div class="contextBlock"><h3>Guardrail</h3><p>Una baja intensidad nacional de un sector no puede trasladarse automáticamente a una región ni a un sujeto obligado sin datos que lo soporten.</p></div>${sourceLinks()}`;
}
function explainIntensity(name){const x=findRPSector(name);if(!x)return;openSheet('Intensidad ROS sectorial',`<div class="definition"><b>${esc(x.sector)}</b><div class="formula">${fmt(x.ros_2025)} ROS ÷ ${fmt(x.registered_2025)} registrados = <strong>${x.ros_per_registered_2025==null?'—':Number(x.ros_per_registered_2025).toFixed(3)}</strong></div><p>Esta razón mide volumen agregado por tamaño del universo. No informa qué entidades enviaron ROS ni qué porcentaje reportó.</p></div><div class="warnbox">No usar como “tasa de cumplimiento”.</div><div class="actionrow"><button class="actionbtn primary" onclick="WB.closeSheet();WB.openReportSector('${esc(x.sector).replaceAll("'","\\'")}')">Abrir sector</button></div>`)}
function reportAlerts(){const z25=(RP.sectors||[]).filter(x=>x.registered_2025>0&&x.zero_ros_2025),z5=(RP.sectors||[]).filter(x=>x.registered_2025>0&&x.zero_ros_5y);return `<div class="kpis">${card('Sectores con 0 ROS 2025',fmt(z25.length),'con entidades registradas')}${card('Silencio persistente 5a',fmt(z5.length),'ROS 2021–2025 = 0')}${card('ROE individual','No disponible','feed operativo requerido')}${card('Guardrail','Activo','silencio ≠ incumplimiento')}</div><div class="grid two">${pan('Silencio ROS 2025','Alertas analíticas sobre agregados públicos.',alertSectorList(z25,'0 ROS durante 2025'))}${pan('Silencio persistente','Cinco años sin ROS agregados y con universo registrado.',alertSectorList(z5,'0 ROS en 2021–2025'))}</div><div class="card panel" style="margin-top:10px"><b>Alerta individual de no reporte</b><p class="mutedP">No se genera para ROS. Para ROE, el motor está conceptualmente preparado: sujeto + periodicidad + ventana + evidencia de envío. Mientras no exista el feed de presentaciones, el estado permanece <span class="mark warn">NO EVALUABLE</span>.</p><button class="button" onclick="WB.reportTab('roe')">Abrir calendario ROE</button></div>`}

function previewReportAlert(name,label){const x=findRPSector(name);if(!x)return;openSheet('Alerta analítica de reportabilidad',`<div class="brief"><b>${esc(x.sector)}</b><br>${esc(label)}</div><div class="metrics2"><div><b>${fmt(x.registered_2025)}</b><span>registrados 2025</span></div><div><b>${fmt(x.ros_2025)}</b><span>ROS 2025</span></div><div><b>${fmt(x.ros_5y)}</b><span>ROS 5 años</span></div><div><b>${esc(x.roe_cadence)}</b><span>periodicidad ROE</span></div></div><div class="warnbox">Silencio ROS sectorial ≠ incumplimiento individual. ROS se reporta cuando existe una operación sospechosa y su envío es confidencial.</div><div class="actionrow"><button class="actionbtn primary" onclick="WB.closeSheet();WB.openReportSector('${esc(x.sector).replaceAll("'","\\'")}')">Abrir sector</button></div>`)}
function alertSectorList(a,label){return a.length?`<div class="alertList">${a.map(x=>`<div class="alertItem" onclick="WB.previewReportAlert('${esc(x.sector).replaceAll("'","\\'")}','${esc(label).replaceAll("'","\\'")}')"><span class="alertDot"></span><div><b>${esc(x.sector)}</b><p>${esc(label)} · ${fmt(x.registered_2025)} entidad(es) registradas</p></div><span>→</span></div>`).join('')}</div>`:'<div class="missing">Sin sectores en esta condición.</div>'}
function nextWindow(cad){const key=cad==='MENSUAL'?'monthly':cad==='TRIMESTRAL'?'quarterly':'semiannual',now=RP.as_of||'2026-08-14',a=RP.roe?.calendar_2026?.[key]||[],w=a.find(x=>x[1]>=now);if(!w)return null;const status=now>=w[0]&&now<=w[1]?'EN VENTANA':'PRÓXIMA';return {start:w[0],end:w[1],status}}
function roeHome(){const k=RP.kpis||{}, wM=nextWindow('MENSUAL'),wQ=nextWindow('TRIMESTRAL'),wS=nextWindow('SEMESTRAL');return `<div class="kpis">${card('ROE 2025',fmt(k.roe_2025),`${pct(k.roe_yoy_pct)} vs 2024`)}${card('Bancos', '70,2%','participación ROE 2025')}${card('Transporte valores','12,4%','participación ROE 2025')}${card('Notarios','9,9%','participación ROE 2025')}</div><div class="grid two">${pan('Calendario ROE','Ventanas oficiales según periodicidad.',roeWindow('Mensual · Bancos',wM)+roeWindow('Trimestral · 29 actividades',wQ)+roeWindow('Semestral · 24 actividades',wS))}${pan('Evolución ROE','Reportes recibidos por la UAF.',roeBars())}</div><div class="grid equal" style="margin-top:10px">${pan('Participación 2025','Distribución pública agregada.',(RP.roe?.sector_shares_2025||[]).map(x=>`<div class="metricRow big"><span>${esc(x.sector)}</span><b>${Number(x.share_pct).toFixed(1)}%</b></div>`).join(''))}${pan('Vigilancia individual ROE','Diseñada, pero no se simula sin feed de cumplimiento.',`<div class="roeState pending"><b>NO EVALUABLE</b><p>Para producir “ROE vencido/no presentado” se requiere identificar al sujeto, su calendario aplicable y la evidencia de presentación. OSINT público no contiene ese estado individual.</p></div><div class="definition"><b>Regla futura</b><div class="formula">obligado + periodo vencido + sin presentación observada = alerta</div><p>La alerta deberá conservar evidencia del periodo y estado de envío.</p></div>`)}</div>`}
function roeWindow(label,w){if(!w)return'';return `<div class="roeWindow ${w.status==='EN VENTANA'?'active':''}"><span>${w.status}</span><b>${esc(label)}</b><p>${esc(w.start)} → ${esc(w.end)}</p></div>`}
function roeBars(){const a=RP.roe?.annual||[],m=Math.max(...a.map(x=>x.reports),1);return `<div class="roeBars">${a.map(x=>`<div><span>${fmt(x.reports)}</span><i style="height:${Math.max(8,x.reports/m*125)}px"></i><b>${x.year}</b></div>`).join('')}</div>`}

/* ---------- Exported functionality ---------- */
BASE.runQuery=smartQuery;BASE.toggleGroup=toggleGroup;BASE.openMobileMenu=openMobileMenu;BASE.openSheet=openSheet;BASE.closeSheet=closeSheet;BASE.goBack=goBack;BASE.openScoreInfo=scoreInfo;BASE.previewFinding=previewFinding;BASE.previewSector=previewSector;BASE.previewRegion=previewRegion;
BASE.reportTab=tab=>{current={kind:'custom',fn:'reportability',args:[tab]};renderReportability(tab);updateBack()};
BASE.openReportSector=name=>routeCustom('reportSector',[name],renderReportSector);BASE.openReportRegion=(name,sectorName='')=>routeCustom('reportRegion',[name,sectorName],renderReportRegion);BASE.explainIntensity=explainIntensity;BASE.previewReportAlert=previewReportAlert;

/* Patch active state after old renderers. */
const oldHealth=BASE.showHealth;BASE.showHealth=(...a)=>{setActive('health');return routeBaseHealth(oldHealth,a)};
function routeBaseHealth(fn,args){if(!replaying){stack.push(current);current={kind:'base',fn:'showApp',args:['home']};updateBack()}return fn(...args)}

/* Rebuild compact nav and improve focus cards without altering underlying components. */
groupedNav();
// Existing focus cards can be previewed through event delegation.
$('#focusList')?.addEventListener('click',e=>{});
// Rewrite app metadata visible after base boot.
const snap=$('#snap');if(snap)snap.textContent=`${D.manifest.snapshot_id} · Fusion v${D.manifest.version} · Workbench v0.10`;
updateBack();setActive('home');
})();
