import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const cors={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const DOC_TYPES=new Set(["CONSTITUCION","MODIFICACION","TRANSFORMACION","FUSION","DIVISION","RECTIFICACION_SANEAMIENTO","DISOLUCION","MIGRACION","PODER","ACCIONISTAS","OTRO"]);
const REL_TYPES=new Set(["SOCIO_DE","ACCIONISTA_CONSTITUYENTE_DE","ACCIONISTA_DE","ADMINISTRA","REPRESENTA","DIRECTOR_DE","APODERADO_DE","LIQUIDADOR_DE"]);
const REL_STATUS=new Set(["VIGENTE_CONFIRMADO","HISTORICO","INDETERMINADA"]);
const ENTITY_TYPES=new Set(["PERSON","COMPANY","UNKNOWN"]);
const ALLOWED_SOURCE_HOSTS=new Set(["registrodeempresasysociedades.cl","www.registrodeempresasysociedades.cl","datos.gob.cl","www.datos.gob.cl"]);
function json(data:any,status=200){return new Response(JSON.stringify(data),{status,headers:cors});}
function cleanRut(v:any){return String(v||"").toUpperCase().replace(/[^0-9K]/g,"");}
function validRut(v:any){const s=cleanRut(v);if(s.length<2)return false;const body=s.slice(0,-1),dv=s.slice(-1);if(!/^\d+$/.test(body))return false;let sum=0,m=2;for(let i=body.length-1;i>=0;i--){sum+=Number(body[i])*m;m=m===7?2:m+1;}const r=11-(sum%11),expected=r===11?"0":r===10?"K":String(r);return dv===expected;}
function formatRut(v:any){const s=cleanRut(v);return validRut(s)?`${s.slice(0,-1)}-${s.slice(-1)}`:null;}
function isoDate(v:any){const s=String(v||"").trim();return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:null;}
function text(v:any,max=600){const s=String(v||"").trim();return s?s.slice(0,max):null;}
function number(v:any){if(v===null||v===undefined||v==="")return null;const n=Number(v);return Number.isFinite(n)?n:null;}
function sourceUrl(v:any){const raw=String(v||"").trim();if(!raw)return null;try{const u=new URL(raw);if(u.protocol!=="https:"||!ALLOWED_SOURCE_HOSTS.has(u.hostname.toLowerCase()))return null;return u.toString();}catch{return null;}}
async function digest(value:string){const bytes=new TextEncoder().encode(value);const hash=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("");}
async function actor(req:Request){const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))throw new Error("AUTH_REQUIRED");const token=auth.slice(7);const userClient=createClient(Deno.env.get("SUPABASE_URL")||"",Deno.env.get("SUPABASE_ANON_KEY")||"",{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:auth}}});const {data,error}=await userClient.auth.getUser(token);if(error||!data.user)throw new Error("AUTH_INVALID");return data.user;}
function admin(){return createClient(Deno.env.get("SUPABASE_URL")||"",Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",{auth:{persistSession:false,autoRefreshToken:false}});}
async function allowed(db:any,userId:string){const {data,error}=await db.from("aml_allowed_users").select("user_id,enabled").eq("user_id",userId).eq("enabled",true).maybeSingle();if(error)throw error;return !!data;}
async function resolveCompany(db:any,entityId:any,rut:any){const rutKey=cleanRut(rut);if(!validRut(rutKey))throw new Error("COMPANY_RUT_INVALID");let q=db.from("aml_entity_master_v0553").select("entity_id,rut,rut_key,name,entity_type,res_available").eq("rut_key",rutKey);if(entityId)q=q.eq("entity_id",String(entityId));const {data,error}=await q.maybeSingle();if(error)throw error;if(!data)throw new Error("COMPANY_ENTITY_NOT_RESOLVED_BY_EXACT_RUT");return data;}
async function resolveRelated(db:any,rut:any){if(!rut)return null;const rutKey=cleanRut(rut);if(!validRut(rutKey))throw new Error("RELATED_RUT_INVALID");const {data,error}=await db.from("aml_entity_master_v0553").select("entity_id,rut,rut_key,name,entity_type").eq("rut_key",rutKey).maybeSingle();if(error)throw error;return data||{entity_id:null,rut:formatRut(rutKey),rut_key:rutKey,name:null,entity_type:null};}
Deno.serve(async(req)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({ok:false,error:"METHOD_NOT_ALLOWED"},405);
  let user:any;try{user=await actor(req);}catch(e){return json({ok:false,error:String((e as Error).message||e)},401);}const db=admin();try{if(!(await allowed(db,user.id)))return json({ok:false,error:"USER_NOT_ALLOWED"},403);}catch(e){return json({ok:false,error:String((e as Error).message||e)},500);}
  const body=await req.json().catch(()=>({}));const action=String(body.action||"");
  if(action==="health")return json({ok:true,service:"aml-res-evidence",write_policy:"allowed-authenticated-users",identity_policy:"RUT_EXACTO_ONLY",source_policy:"LINK_ONLY_NO_FETCH",website_scraping:false});
  if(action==="review"){const documentId=text(body.document_id,180),status=String(body.review_status||"");if(!documentId||!new Set(["REVIEWED","REJECTED"]).has(status))return json({ok:false,error:"REVIEW_INPUT_INVALID"},400);const now=new Date().toISOString();const {data,error}=await db.from("aml_res_document_evidence").update({review_status:status,reviewed_by:user.id,reviewed_at:now,refreshed_at:now}).eq("document_id",documentId).select("document_id,entity_id,review_status").maybeSingle();if(error)return json({ok:false,error:error.message},500);if(!data)return json({ok:false,error:"DOCUMENT_NOT_FOUND"},404);await db.from("aml_res_actuation").update({evidence_status:status,refreshed_at:now}).eq("source_document_id",documentId);if(status==="REJECTED")await db.from("aml_res_relationship").update({requires_review:true,refreshed_at:now}).eq("source_document_id",documentId);return json({ok:true,document:data});}
  if(action!=="submit")return json({ok:false,error:"UNKNOWN_ACTION"},400);
  try{
    const document=body.document||{},relations=Array.isArray(body.relations)?body.relations:[];if(relations.length>50)throw new Error("TOO_MANY_RELATIONS");const company=await resolveCompany(db,body.entity_id,body.company_rut);
    const docType=String(document.document_type||"").toUpperCase();if(!DOC_TYPES.has(docType))throw new Error("DOCUMENT_TYPE_INVALID");const actuationType=text(document.actuation_type,120)||docType;const actuationDate=isoDate(document.actuation_date),registryDate=isoDate(document.registry_date);const url=sourceUrl(document.source_url);if(!url)throw new Error("SOURCE_URL_NOT_ALLOWED");const sourceDomain=new URL(url).hostname.toLowerCase();const title=text(document.document_title,240),cve=text(document.cve,160),notes=text(document.notes,1200),legalName=text(document.legal_name,280);
    if(!company.res_available&&!legalName)throw new Error("LEGAL_NAME_REQUIRED_FOR_NEW_RES_ENTITY");const canonical=JSON.stringify({company_rut_key:company.rut_key,docType,actuationType,actuationDate,registryDate,url,cve});const h=await digest(canonical);const documentId=`RES-DOC-${company.rut_key}-${h.slice(0,32)}`;const now=new Date().toISOString();
    if(!company.res_available){const {error:ce}=await db.from("aml_res_company").upsert({rut:company.rut,rut_key:company.rut_key,source_record_id:cve,legal_name:legalName,constitution_date:docType==="CONSTITUCION"?actuationDate:null,registry_date:docType==="CONSTITUCION"?registryDate:null,source_year:actuationDate?Number(actuationDate.slice(0,4)):null,source_snapshot_id:null,source_payload:{collection_mode:"MANUAL_STRUCTURED",document_id:documentId,source_url:url,website_scraping:false},last_seen_at:now,refreshed_at:now},{onConflict:"rut",ignoreDuplicates:false});if(ce)throw ce;}
    const {error:be}=await db.from("aml_res_entity_bridge").upsert({rut:company.rut,entity_id:company.entity_id,match_method:"RUT_EXACTO",confidence:1,refreshed_at:now},{onConflict:"rut",ignoreDuplicates:false});if(be)throw be;
    const docRow={document_id:documentId,company_rut:company.rut,company_rut_key:company.rut_key,entity_id:company.entity_id,document_type:docType,actuation_type:actuationType,actuation_date:actuationDate,registry_date:registryDate,document_title:title,source_url:url,source_domain:sourceDomain,cve,document_hash:h,ingestion_method:"MANUAL_STRUCTURED",extraction_status:"PENDING",review_status:"PENDING",notes,structured_payload:{relationship_input_count:relations.length,identity_method:"RUT_EXACTO",source_mode:"LINK_ONLY_NO_FETCH",website_scraping:false},submitted_by:user.id,submitted_at:now,refreshed_at:now};const {error:de}=await db.from("aml_res_document_evidence").upsert(docRow,{onConflict:"document_id",ignoreDuplicates:false});if(de)throw de;
    const actuationId=`RES-DOC-ACT-${company.rut_key}-${h.slice(0,24)}`;const {error:ae}=await db.from("aml_res_actuation").upsert({actuation_id:actuationId,rut:company.rut,rut_key:company.rut_key,actuation_type:actuationType,actuation_date:actuationDate,registry_date:registryDate,source_record_id:cve,source_snapshot_id:null,public_document_url:url,source_document_id:documentId,evidence_status:"PENDING",structured_payload:{document_id:documentId,document_type:docType,cve,collection_mode:"MANUAL_STRUCTURED",website_scraping:false},refreshed_at:now},{onConflict:"actuation_id",ignoreDuplicates:false});if(ae)throw ae;
    const out:any[]=[];for(let i=0;i<relations.length;i++){const r=relations[i]||{},relatedName=text(r.related_name,260);if(!relatedName)throw new Error(`RELATED_NAME_REQUIRED_${i+1}`);const relType=String(r.relationship_type||"").toUpperCase();if(!REL_TYPES.has(relType))throw new Error(`RELATIONSHIP_TYPE_INVALID_${i+1}`);const relStatus=String(r.relationship_status||"INDETERMINADA").toUpperCase();if(!REL_STATUS.has(relStatus))throw new Error(`RELATIONSHIP_STATUS_INVALID_${i+1}`);const requestedType=String(r.related_entity_type||"UNKNOWN").toUpperCase();if(!ENTITY_TYPES.has(requestedType))throw new Error(`RELATED_ENTITY_TYPE_INVALID_${i+1}`);const resolved=await resolveRelated(db,r.related_rut);const ownership=number(r.ownership_pct),shares=number(r.shares_count);if(ownership!==null&&(ownership<0||ownership>100))throw new Error(`OWNERSHIP_PCT_INVALID_${i+1}`);if(shares!==null&&shares<0)throw new Error(`SHARES_INVALID_${i+1}`);const relatedRut=resolved?.rut||formatRut(r.related_rut);const relatedEntityId=resolved?.entity_id||null;let entityType=requestedType;if(entityType==="UNKNOWN"&&resolved?.entity_type){const t=String(resolved.entity_type).toUpperCase();entityType=t.includes("PERSON")?"PERSON":t.includes("COMP")||t.includes("EMPRESA")||t.includes("JURID")?"COMPANY":"UNKNOWN";}const rh=await digest(`${documentId}|${i}|${relType}|${relatedRut||""}|${relatedName.toUpperCase()}`);const relationId=`RES-REL-${rh.slice(0,36)}`;const requiresReview=!relatedEntityId||relStatus==="INDETERMINADA";const row={relationship_id:relationId,company_rut:company.rut,related_entity_id:relatedEntityId,related_rut:relatedRut,related_name:relatedName,related_entity_type:entityType,relationship_type:relType,role_label:text(r.role_label,180),ownership_pct:ownership,shares_count:shares,valid_from:isoDate(r.valid_from)||actuationDate,valid_to:isoDate(r.valid_to),relationship_status:relStatus,relationship_basis:"DOCUMENTO_EXPLICITO",source_actuation_id:actuationId,source_document_id:documentId,source_document_url:url,extraction_method:"MANUAL_STRUCTURED",confidence:1,requires_review:requiresReview,evidence:{document_id:documentId,cve,document_review_status:"PENDING",identity_method:relatedEntityId?"RUT_EXACTO":"NOMBRE_DOCUMENTAL_SIN_VINCULO",submitted_by:user.id},refreshed_at:now};const {error:re}=await db.from("aml_res_relationship").upsert(row,{onConflict:"relationship_id",ignoreDuplicates:false});if(re)throw re;out.push({relationship_id:relationId,related_entity_id:relatedEntityId,requires_review:requiresReview});}
    const {error:fe}=await db.from("aml_res_document_evidence").update({extraction_status:"STRUCTURED",structured_payload:{relationship_input_count:relations.length,relationship_written_count:out.length,actuation_id:actuationId,identity_method:"RUT_EXACTO",source_mode:"LINK_ONLY_NO_FETCH",website_scraping:false},refreshed_at:new Date().toISOString()}).eq("document_id",documentId);if(fe)throw fe;return json({ok:true,document_id:documentId,entity_id:company.entity_id,actuation_id:actuationId,relationships:out,review_status:"PENDING"});
  }catch(e){return json({ok:false,error:String((e as Error).message||e)},400);}
});
