-- ATLAS AML 0.65.0 · Padrón SII completo + Entity Master + potenciales SO
-- Migración productiva aplicada en Supabase el 2026-08-25.
--
-- Objetivo: separar el universo jurídico/tributario completo del subconjunto
-- histórico de entidades ya observadas por radares. La identidad se forma sólo
-- por RUT chileno válido y canónico.
--
-- Objetos productivos:
--   aml_sii_registry_snapshot
--   aml_sii_registry_company
--   aml_sii_registry_activity
--   aml_uaf_sii_screening_policy_v0650
--   aml_uaf_potential_registry_snapshot_v0650
--   aml_v_uaf_potential_registry_summary_v0650
--   aml_entity_master_v0650
--   refresh_aml_uaf_potential_registry_v0650()
--
-- Fuentes oficiales SII:
--   https://www.sii.cl/estadisticas/nominas/PUB_NOMBRES_PJ.zip
--   https://www.sii.cl/estadisticas/nominas/PUB_NOM_ACTECOS.zip
-- Política explicable:
--   Radar_SII/config/uaf_sii_screening_policy.csv
--
-- Semántica del cálculo:
--   1. Padrón SII completo de personas jurídicas => universo tributario.
--   2. Actividades vigentes SII => evidencia observable por RUT.
--   3. Política A/B/C => clasifica fuerza de compatibilidad con sectores UAF.
--   4. Anti-join exacto contra aml_uaf_obligated_subject_snapshot (10.294 RUT).
--   5. Término de giro queda separado; no se cuenta como activo.
--   6. RES se usa como contexto de constitución/forma societaria, no como prueba
--      de actividad regulada ni de obligación UAF.
--
-- Cifras publicables una vez normalizados los tres insumos:
--   potential_a_not_uaf   = A_STRONG activos, cifra estricta de screening.
--   potential_ab_not_uaf  = A+B activos, universo respaldado.
--   potential_all_not_uaf = A+B+C activos, screening ampliado.
--
-- Guardarraíles:
--   RUT_EXACTO_ONLY
--   NO_NAME_IDENTITY_PROMOTION
--   POTENTIAL_SO != LEGAL_BREACH
--   TERMINATED_AS_PUBLISHED excluded from active headline
--   SECURITY_INVOKER views + RLS + allowed users
--
-- La DDL canónica está registrada en el historial de migraciones de Supabase
-- bajo: atlas_v0650_sii_registry_entity_master.
